### ISSUE TITLE
initial cycle point on command line only?

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc#1000]
https://github.com/cylc/cylc/pull/997#issuecomment-47302861
https://github.com/cylc/cylc/pull/997#issuecomment-47328047

Pre cylc-6, initial cycle time (ICT) was optional in the suite definition; it could be given or overridden on the command line for suite start-up.  Other suite parsing commands (e.g. validate) did not need the CLI option because a sensible default ICT could always be chosen.  In other words, under the old cycling paradigm a suite's validity could be determined without reference to a concrete initial cycle time.

For cylc-6 this isn't the case - a sensible default ICPoint can't be determined in general. So our options are:
1. retain the CLI option and give it to all suite parsing commands, or 
2. **require** an ICP in the suite definition

My preference is to require an ICP in the suite definition.  It is simpler, and I don't like the idea of suite definitions not being valid until extra external information is supplied.  I expect we have some users who rely on the command line ICT, but: cylc-6 changes the game a bit; it's not hard to edit a suite definition; and if really necessary a Jinja2 variable can be set from the command line (and that's already supported by all suite-parsing commands, I think).

Thoughts?

**Comment by hjoliver** [comment]
Closing as no biggie.

**Comment by hjoliver** [comment]
(however, we should check: if no ICP in the suite definition, can it be supplied on the CLI for all uses (run, graph, list, etc.)

**Comment by hjoliver** [comment]
Reopen - we should check: if no ICP in the suite definition, can it be supplied on the CLI for all uses (run, graph, list, etc.)

**Comment by matthewrmshin** [comment]
I think these are the CLI commands we need to worry about:

- [ ] diff
- [ ] get-suite-config
- [ ] graph
- [ ] graph-diff
- [ ] jobscript
- [ ] list
- [X] run
- [ ] submit
- [X] validate
