### ISSUE TITLE
special notation for initial and final cycle points

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc#1038]
(to consider after #996 is merged)

We can currently start (and end) recurrences at the initial (and final) cycle point using our simplified "in suite context" notation, which omits the end points entirely from the appropriate recurrence form.  This works and is well defined *but* is not exactly easy to read at a glance particularly for the "fourth recurrence form" and final cycle point.

Should we consider either requiring or allowing explicit ```^``` and ```$``` characters to represent suite initial and final points in recurrences, instead of omission - that would be easy to read and consistent with our in-graph notation (at least for initial point ... as I recall we didn't see a use case for in-graph final point notation yet).

@benfitzpatrick - thoughts?

**Comment by arjclark** [comment]
There are a few cases where a notation for final cycle point would be useful - for example in trials where you want to run final cycle housekeeping/verification/archiving tasks.
