### ISSUE TITLE
#119: cycler unit tests

### ISSUE THREAD

**Issue by benfitzpatrick** [cylc/cylc#1045]
We should have some `lib/cylc/cycling/*` unit tests.

**Comment by hjoliver** [comment]
@benfitzpatrick - we do seem to have some tests in these files. Can this be closed?

**Comment by hjoliver** [comment]
@benfitzpatrick - ping.

**Comment by benfitzpatrick** [comment]
There are tests in there, but I don't think they are ever invoked by the test battery. To be honest, I'm happy with the range of regression tests that cover this, coupled with the inbuilt isodatetime tests. Happy to close it.

**Comment by matthewrmshin** [comment]
I believe these functional tests were added by #937.
