### ISSUE TITLE
Migrate Rose Bush into cylc

### ISSUE THREAD

**Issue by matthewrmshin** [cylc/cylc#1052]
We have agreed that Rose Bush should become part of cylc.

~~This is probably dependent on #992~~. 

(It will need a new name.)
- `cylc weblog`? (See comment 2 in #992.)
- `cylc moth`? (MOnitor Tasks via HTTP.)
  )

**Comment by kaday** [comment]
Upgrade to Bootstrap3 to be able to do cool things like @matthewrmshin and I discussed with reference to: metomi/rose#1609

**Comment by hjoliver** [comment]
Agreed to "lift and shift" it from Rose soon.  We'll probably make more out of it after the activity to improve the communication API.

**Comment by oliver-sanders** [comment]
Linking this with #1873 to reflect the eventual ambition to encapsulate this suite reporting in the cylc gui.
