### ISSUE TITLE
Find nearby cycle points without iterating from sequence start

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc#1053]
In several places in the new ISO8601 cycling implementation we find an on-sequence point at or near to some other point X by iterating from the sequence start point until at or beyond X.  This is not efficient if X is a long way beyond the sequence start point.  It should be (I hope) possible to find a nearby on-sequence more directly, like in the old (otherwise vastly inferior!) cycling modules.  See https://github.com/cylc/cylc/pull/1044#discussion_r15726399, https://github.com/cylc/cylc/pull/1044#issuecomment-50953586, and https://github.com/cylc/cylc/pull/1044#issuecomment-51002160.

**Comment by benfitzpatrick** [comment]
This is causing some problems, so I'd like to address this in the next couple of weeks.

**Comment by hjoliver** [comment]
@benfitzpatrick - should this be closed now, or do you think we can still do better in the future? (in #1850 you wrote "This addresses part of #1053".)

**Comment by benfitzpatrick** [comment]
I think we can close it - as it's written, it's addressed by #1850.
