### ISSUE TITLE
reference tests: add built-in graphing support

### ISSUE THREAD

**Issue by arjclark** [cylc/cylc#1068]
`test_header` has had functionality added in for checking suite graphing (see `graph_suite()`).

It would be useful to have this functionality built in to `--reference-log` and `--reference-test` in order to auto-generate and use the approriate files as part of testing.

**Comment by hjoliver** [comment]
[meeting] - ok as-is.

**Comment by oliver-sanders** [comment]
Do we close this?

**Comment by matthewrmshin** [comment]
Yes, assuming that we now have a way to print graph as text for tests.

**Comment by oliver-sanders** [comment]
`cylc graph --reference`?

**Comment by matthewrmshin** [comment]
I think this is good to close. Note: The original description of this issue also appears to contradict with #830.
