### ISSUE TITLE
Ideas for more efficient scheduling of very large suites

### ISSUE THREAD

**Issue by cylc** [cylc/cylc#108]
First, see Issue #107 (more efficient scheduling of large ensembles).

Currently the scheduling algorithm works like this: every task in the suite is represented by its own task proxy.  Every time a task proxy changes state (usually after receiving a progress message from the real task) each task proxy communicates its completed outputs to a broker, then each task proxy asks the broker to satisfy its prerequisites - by literal string matching of unsatisfied prerequisites to completed outputs. The broker simply dumps its outputs and starts again each time through the loop. To prevent the task pool from growing indefinitely spent tasks are eliminated from the pool as soon as cylc decides they are not needed to satisfy any other task's prerequisites anymore.

**Comment by hjoliver** [comment]
I think we can close this Issue as superseded.  For the points above:

 1. doesn't matter
 2. was investigated in #1428, follow-up #1902
 3. and 4. - obvious things to do if profiling shows a bottleneck
 5. done by #1688 
 6. superseded by #1689
