### ISSUE TITLE
cylc gui: filtering by input & output dependencies of a task/tasks

### ISSUE THREAD

**Issue by benfitzpatrick** [cylc/cylc#1086]
It would be good to be able to filter down to a particular task's
or tasks' immediate graph - i.e. just the nodes that the task
depends on, the task node, and the nodes that depend on the
task.

**Comment by hjoliver** [comment]
c.f. rosie graph

**Comment by oliver-sanders** [comment]
[meeting 2017] - Displaying a graph "n" levels deep starting from a particular node was discussed in combination with #1873.

**Comment by hjoliver** [comment]
Closing as superseded by https://github.com/cylc/cylc/issues/1873#issuecomment-330254260
