### ISSUE TITLE
Modify runtime configuration on retry (XCPU)

### ISSUE THREAD

**Issue by matthewrmshin** [cylc/cylc#1105]
Users are requesting that we implement an ability to distinguish between a normal failure to a failure that is triggered by a signal such as `XCPU`. E.g. In the case of `XCPU`, the suite should be able to re-submit the same task, but with a longer wall clock limit.

See also #970.

**Comment by hjoliver** [comment]
[meeting]
 * would definitely be useful
 * list of successive wall-clock limits? (how to specify these?)

**Comment by matthewrmshin** [comment]
> would definitely be useful

Unfortunately, it looks like neither PBS nor SLURM sends XCPU on reaching execution time limit. Therefore, this functionality will be of limited use for us right now.

> list of successive wall-clock limits? (how to specify these?)

We can expand the new *execution time limit* setting to accept a list.

**Comment by benfitzpatrick** [comment]
> We can expand the new execution time limit setting to accept a list.

:+1:

**Comment by matthewrmshin** [comment]
Superseded by #2415.
