### ISSUE TITLE
parsec should ignore unknown items, not abort

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc#1113]
At least for global config (need to think about implications for suites...) This would make global config parsing forward-compatible.

**Comment by hjoliver** [comment]
(I forgot about this - I'll attempt to revisit it soon).

**Comment by matthewrmshin** [comment]
(This would have been useful while we are introducing new site/user global configuration.)

**Comment by hjoliver** [comment]
(It would be useful here too - I could make it my top priority once current pull requests done with).

**Comment by hjoliver** [comment]
Document the workaround: each version needs its own site file.

**Comment by matthewrmshin** [comment]
We have now got a solution for rolling out different `$CYLC_DIR/conf/global.rc` for different versions of cylc. The problem remains for `~/.cylc/global.rc`, however, if a user wants to run multiple versions of cylc at the same time.

**Comment by hjoliver** [comment]
(solved by #2661 - allows separate user global.rc for each version)
