### ISSUE TITLE
Port GUIs from PyGTK/Gnome-2 to PyGobject/Gnome-3

### ISSUE THREAD

**Issue by cylc** [cylc/cylc#112]
Software is a moving target ... The latest PyGTK release is the last of the line. The release announcement says:

> New users wishing to develop Python applications using GTK+ are 
> recommended to use the GObject-Introspection features available
> in PyGObject.  Existing authors of PyGTK applications are also 
> recommended to port their applications to PyGObject to take 
> advantage of new features appearing in GTK-3 and beyond. 
> More information on PyGObject and GObject-Introspection can 
> be found at http://live.gnome.org/PyGObject.
> PyGTK-2.24 will be the final major release of PyGTK."

**Comment by matthewrmshin** [comment]
(Or move to another modern GUI technology?)

**Comment by hjoliver** [comment]
> (Or move to another modern GUI technology?)

Any suggestions?  I imagine that upgrading the existing GUI to pygobject and gtk-3 will be relatively easy, but making a completely new GUI that can compete with the current one would be a BIG job - we have invested a lot of effort in it so far.

**Comment by hjoliver** [comment]
(discussion of web UI technologies taken offline)

**Comment by hjoliver** [comment]
Agreed:
 * we can't do this until Pygobject (comes with Gnome3) is available on all distros that we need to support.

**Comment by hjoliver** [comment]
@cylc/core - extreme difficulty of installing PyGTK is frequently reported by those who don't have it available out of the box on there systems.  Any updates on previous comment re going to PyGobject in the short term?

**Comment by matthewrmshin** [comment]
This issue should cover `cylc gui`, `cylc gscan` and `cylc gpanel`, so #570 is really a duplicate.

**Comment by hjoliver** [comment]
Haven't we more or less decided not to do this, and go straight (within the next year, maybe) to web tech?

**Comment by matthewrmshin** [comment]
Superseded by #1873.
