### ISSUE TITLE
cylc CLI: prompt for commands with a regex for task?

### ISSUE THREAD

**Issue by benfitzpatrick** [cylc/cylc#1186]
A user asks:
```
If I run:
cylc hold MY_SUITE 'REGEX' 2014101612

There might be some danger that an unexpected task is picked up. Is there any way
to make this expand and bring up a list of the tasks that will receive an action, then
have a confirmation request?
```

This could be:
 * a default behaviour whether the expression exactly matches a single task or not
 * a default behaviour only when the expression is not a task name (a regular expression)
 * a behaviour triggered by an extra option (e.g. `--prompt`)

This is related to our communication refactor and e.g. #423.

**Comment by hjoliver** [comment]
Absorbing this into #423
