### ISSUE TITLE
Use sphinx or similar to generate useful reports from suite definitions

### ISSUE THREAD

**Issue by cylc** [cylc/cylc#121]
"Sphinx is a tool that makes it easy to create intelligent and beautiful documentation": http://sphinx.pocoo.org/
 There's also "sphinx-report": http://code.google.com/p/sphinx-report/.

It was suggested at MPI, as I recall, that something like this would be good for generating human-readable metadata describing the suite as a whole, for archiving with experiment results.

Luis, would you like to add to this?

**Comment by benfitzpatrick** [comment]
We're not sure that users need this kind of annotation to the few cylc builtin configuration options. There isn't a lot extra that could be added, as most options are fairly descriptive and people can add comments.

Closing for the moment - issue can be reopened based on demand.
