### ISSUE TITLE
cylc db: secondary db failure robustness and recovery 

### ISSUE THREAD

**Issue by arjclark** [cylc/cylc#1213]
Reminder issue.

Having a secondary database for access by external suite utilities should lead to a reduction of load on the primary database and reduce opportunities for writer starvation. However, if a failure to write to the secondary database occurs, it will still result in the suite stopping.

We should make it so the secondary, publicly viewable, database can fail to be written to without impact on the suite and only a failure of the primary database results in a suite stop.

Accompanying that, we should have a utility to synchronise the two databases (though what's involved in this will obviously be affected by any changes to the datastructure).

**Comment by hjoliver** [comment]
#1295 solved the issue of missing db ops on restart after  shutdown due to a locked db.

Still to consider: can we allow the suite to continue running for longer if the public viewable db is locked.

**Comment by arjclark** [comment]
Closed based on the following:
>We should make it so the secondary, publicly viewable, database can fail to be written to without impact on the suite and only a failure of the primary database results in a suite stop.

This is nigh on impossible to sensibly do unless we're willing to cut off any external processes using the public db. However, we have increased tolerance to locking of the public database in #1479. Future integration of rose like suite-hooks into cylc to carry out file retrieval should reduce the need for external processes to access the databases.

>Accompanying that, we should have a utility to synchronise the two databases (though what's involved in this will obviously be affected by any changes to the datastructure).

This should now be unnecessary following #1295 as uncommitted db ops are dumped out on suite shutdown and loaded back in on restart. In an absolute worst case scenario, the private database can currently be manually copied over the public one to resynchronise them. This may no longer be appropriate once we revisit the datamodel and what information should be stored where.

**Comment by hjoliver** [comment]
See also #1493, which solves the problem of recovery from a locked public db.
