### ISSUE TITLE
Memory use in large suites

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc#1222]
To run very large suites (say >10k tasks) we'll need to minimize use of memory by task proxies,  understand how cylc interacts with Python's memory management system, and possibly invoke garbage collection deliberately at certain points such as before and/or after a suite reload (which currently replaces all task proxy objects).

**Comment by hjoliver** [comment]
As I recall, my experimentation above suggested that there is little benefit to be gained from  attempting to manipulate Python's memory management and garbage collection.  If a suite is using a large amount of memory we're likely to get a high-water effect resulting from memory fragmentation (i.e. the memory use may go up but it is unlikely to go down).

On that basis, I think we need to concentrate on minimizing task proxy memory use.

**Comment by hjoliver** [comment]
Assigned low priority label - no one will be running 20k-task suites any time soon (?)

**Comment by arjclark** [comment]
#1776 relates after a fashion in that large numbers of dependencies between tasks can produce surprisingly large memory overheads, where the number of interdependencies between different families' members is the driving usage of memory as opposed to the number of task proxies themselves.

**Comment by hjoliver** [comment]
This can probably be superseded by #1689
