### ISSUE TITLE
Operate (e.g. trigger) on just failed family members

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc#1238]
It would be useful to have this as an option.  Currently you have to retrigger (or reset etc.) all members of a family regardless of their current state, or otherwise do each member manually.

**Comment by matthewrmshin** [comment]
The syntax discussed in https://github.com/cylc/cylc/issues/960#issuecomment-121634220 is related.

**Comment by hjoliver** [comment]
I'm closing this as a duplicate of #960 (which also has all the comments on the topic; but I'll expand its scope a little bit, beyond just "triggering" of failed members).
