### ISSUE TITLE
Automatic distribution of suite passphrase to remote accounts?

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc#124]
Ssh keys must be installed on remote task hosts in order to run remote tasks, which means cylc already has the access required to automatically install the suite passphrase to any remote task hosts. Manual passphrase installation would then only be required for other remote control accounts.

**Comment by matthewrmshin** [comment]
#1705 (*Also* bullet point 1):
* on 1st submit to a remote job host, install passphrase file (with cylc-suite-env) to its run directory.

I think the change in #1705 solves the original description of this issue (but probably not everything discussed). I think this issue should be closed.
