### ISSUE TITLE
cylc gscan: add failed information

### ISSUE THREAD

**Issue by kaday** [cylc/cylc#1244]
From  issue1164 part two:
" Request from BOM:

 * in cases where the suite has failed task, the name of the failed task (for multiple failed tasks, I suppose it could be either the first failed task or number of the failed tasks)"

**Comment by hjoliver** [comment]
On hover-over, gscan now shows the number of tasks in each state (including failed).

Names of failed tasks - maybe that's worth doing, I'm not sure.  Is failed fundamentally more important than all the other states (it certainly is quite important, but what about submit-failed, expired, retrying, ...).  We can't list them all in gscan hover-over, for big suites.   @cylc/core - opinions on whether to close this or not?

**Comment by kaday** [comment]
I think that failed is far more important especially after having just started a 50:50 secondment where I am working closer to the operational side and I am seeing how they are using gscan. If the rest of the @cylc/core agree I will make this a priority now.

**Comment by matthewrmshin** [comment]
I think a good interface for this is to print out a list of, say, the most recent 10 (configurable?) task IDs that fall into each category. For failed tasks, the total should be a small number, so would normally display everything relevant. Otherwise, we can print the 10 most recent task IDs, then say something like e.g. *and 62438 more*.

**Comment by arjclark** [comment]
As this list can get potentially quite long and render the hover overs useless, what might be nicer instead would be to have the ability to get a quick listing of tasks in a particular state of interest via a right click menu or something that opens up a popup with a scroll bar window if needed.

**Comment by matthewrmshin** [comment]
(To elaborate my comment above, I am thinking of a hover-over for *each* state, instead of an overall hover-over, like we do now.)

**Comment by kaday** [comment]
Matt's idea is what I was considering but I had not thought to limit it, which I think is an ace idea and will allow the hover to still work.

**Comment by hjoliver** [comment]
Yeah, limiting to a max number of tasks makes  the hover-over workable.  We could do both: hover-over for minimal info about a max of 10 tasks, right click menu to get more detailed information about all tasks in that state in a popup window?

**Comment by kaday** [comment]
The PSA's here said it would really help them if the 10 most recently failed tasks were listed in the hover-over.

**Comment by hjoliver** [comment]
@kaday - 'scuse my ignorance, but a "PSA"?

**Comment by benfitzpatrick** [comment]
(Our acronym for operational suite controller)
