### ISSUE TITLE
cylc graph: long startup times when no initial and final cycle points provided

### ISSUE THREAD

**Issue by arjclark** [cylc/cylc#1256]
We've noticed that cylc graph appears to start up slower when no initial and final cycle points are provided.

Testing with an hourly cycling suite I've got knocking around with ISO cycling, no visulization settings and no final cycle point defined in the suite.rc file:

```
time cylc graph SUITE                        

real	0m55.264s
user	0m53.452s
sys	0m0.259s
```
and with a CLI provided initial and final cycle point:
```
time cylc graph SUITE 20141201T12 20141201T14

real	0m11.726s
user	0m10.171s
sys	0m0.204s
```
(in both cases allowing ~1sec for me to close the gui again).

**Comment by hjoliver** [comment]
@arjclark - in the "unbounded" case we should be generating number of cycle points equal to ```[visualization]number of cycle points```, which defaults to merely 3.

In a quick test here I couldn't see this effect.  Can you confirm it is still happening at your end, and if so provide a suite definition that exhibits the problem?

**Comment by benfitzpatrick** [comment]
I guess this may not be replicable any more?

**Comment by arjclark** [comment]
Unable to replicate any more. If this is raised again I'll re-open the issue.
