### ISSUE TITLE
constraining the initial cycle point?

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc#1279]
Cycling suites typically require the initial cycle point to be constrained in some way, but recurrence expression start points can be an unwieldy way to do this.  E.g. for a 6-hourly cycling suite, the initial cycle point typically has to end in 00, 06, 12, or 18 hours.  The most efficient way to specify this would be just ```R//PT6H``` plus the aforementioned constraint (specified in some way yet to be determined), but as it is we have to use ```R/T00/PT6H, R/T06/PT6H, R/T12/PT6H, R/T18/PT6H``` which is mostly redundant information and could potentially affect performance in large suites (computing with multiple recurrences instead of one).  One option, as posted to the cylc mailing list, is a Jinja2 filter that causes the suite parser to abort if the initial cycle point is invalid ... but it might be good to provide built-in support for this.

Is there a general way to specify this kind of constraint on the initial cycle point ... maybe a finite recurrence expression:

```initial cycle point constraint = R4/T00/PT6H```

**Comment by hjoliver** [comment]
Actually, a better way to do this might be an extended recurrence expression that specifies alternate start points, something like this:

```
R/(T00,T06,T12,T18)/PT6H
```
which would represent a single sequence starting at the first T00, T06, T12, or T18 at or after the initial cycle point. 

@benfitzpatrick - thoughts?

**Comment by benfitzpatrick** [comment]
> initial cycle point constraint = R4/T00/PT6H

Having a constraint option is a great idea! What about a list of possible regular expressions to search for:

```
initial cycle point constraints = T00, T06, T12, T18
```

We could probably include a final cycle point constraint just for completeness.

> Actually, a better way to do this might be an extended recurrence expression that specifies alternate 
> start points, something like this:
>
> ```
R/(T00,T06,T12,T18)/PT6H
```
>which would represent a single sequence starting at the first T00, T06, T12, or T18 at or after the
> initial cycle point. 

I had been thinking about this, as I think it might be the one important thing missing at the
moment. It needs a 'minimum' feel to it. Maybe just:
```
R/min(T00,T06,T12,T18)/PT6H
```


Actually, I wonder if:

```
[[[T00+PT6H/PT6H,T06+PT6H,T12+PT6H,T18+PT6H]]]
```
would work?

**Comment by arjclark** [comment]
Interesting, related design problem I've encountered recently was where a user wanted to do an R1 task at the first occurrence in a list of possible dates:

```
R1/T03, R1/T09, R1/T15, R1/T21
```
but hadn't realised that the task would run once at each of these points.

I think the above `min()` suggestion would be useful for that as:
```
R1/min(T03, T09, T15, T21)
```

Restrictions on the initial cycle point would likely be useful here too because if you could write:
```
initial cycle point constraints = T03, T09, T15, T21
```

which would probably allow me to reduce the R1/min down to a regular R1 section.

**Comment by arjclark** [comment]
I'm taking a crack at the `initial cycle point constraints = ` part of this

**Comment by arjclark** [comment]
I've split Ben's R1/min(...) suggestion into a separate ticket at #1355
