### ISSUE TITLE
Discussion: Check for atd running before trying to submit to at

### ISSUE THREAD

**Issue by arjclark** [cylc/cylc#1280]
We've recently experienced a problem with the at daemon not running but tasks still being submitted to the atq.

A possibility is to see if the at daemon is running when looking to submit and submit failing if not running.

**Comment by matthewrmshin** [comment]
@hjoliver We would like to propose that if something like `pgrep atd` does not return `0`, then a normal `at` job submission (one without a command template) should be marked as a `submit-failed`. Can you think of any potential issues?

**Comment by hjoliver** [comment]
Sounds good. We've had the same problem several times.
