### ISSUE TITLE
cylc stop --quick: functionality lost

### ISSUE THREAD

**Issue by arjclark** [cylc/cylc#1282]
It's been pointed out that we lost `--quick` functionality from cylc stop. We've tracked this back to #1117 where it snuck in.

From what I can tell, the difference between `--quick` (at cylc 5.4.14) and `--now` (cylc 6+) is that `--quick` meant event hooks still got ran but `--now` means they don't. Trying to test this is somewhat difficult as there seems to be an element of timing involved in whether you see any difference in behaviour.

As a second part, gcylc still has a "Quickly" option under "Stop Suite", which is broken.

I can't quite work out from `scheduler.py` whether task proxies with event handlers due to run will run them or not - again though it looks like a timing of the command will affect whether or not the event hooks would be run.

@hjoliver - thoughts/comments?

**Comment by matthewrmshin** [comment]
We also identified some (minor?) issues while testing this.
* On shut down now, scripts run by the event hooks will continue to run. This may be seen as untidy, but may have other implications on restart.
* On restart after a shut down now, the suite does not re-run event hooks that did not have a chance to run before the shut down.
* Results of event hooks are not very visible to users.
* There is no easy way to trigger an event hook again if it did not run.

**Comment by hjoliver** [comment]
@matthewrmshin - on the additional issues identified while testing:

> On shut down now, scripts run by the event hooks will continue to run. This may be seen as untidy, but may have other implications on restart.

IMO "shutdown now" is about shutting down the suite daemon immediately, regardless of any current suite activity.  We don't kill running tasks either on shutdown now.    Maybe we want an option (like ```shutdown --kill``` for tasks) to do this.

> On restart ... the suite does not re-run event hooks that did not ... run before the shut down

True, but it's not clear to me that it should do that.  Event handlers are typically (or often, at least) time-sensitive.  You wouldn't want a out-of-date task failure warning to trigger on restarting a suite that has been down for a month.

> Results of event hooks are not very visible to users.

We do now capture task event handler stdout and stderr to ```job-activity.log```.   Do you think we should expose this via the GUI or something?

> There is no easy way to trigger an event hook again if it did not run.

Yes, this might be useful.

**Comment by hjoliver** [comment]
Terminology:  I think of an "event hook" as the bit of cylc internals to which the user can attach an "event handler" script, whereas you guys seem to call the handler script the "event hook".  Can we straighten this out to avoid the continual (if minor) translation effort?  My terminology makes more sense to me, but I'm not sure which is more standard!

**Comment by hjoliver** [comment]
Given that (as I've argued above) it's not obvious what to do about event handlers at shutdown:

* for event handlers that are already queued but yet to run at shutdown, we could just list these to suite stdout, with full command lines, at shutdown. Then the user can choose to run them manually (cut-n-paste to the terminal) or ignore them.

* for event handlers that are still running at shutdown, we could just list their PIDs (perhaps with their full command lines too, to allow discovery of purpose) to suite stdout at shutdown.  Then the user can choose to kill them or not.

**Comment by hjoliver** [comment]
> the difference between ```--quick``` (at cylc 5.4.14) and ```--now``` (cylc 6+) is that ```--quick``` meant event hooks still got ran but ```--now``` means they don't.

I think that's right, although we had ```--now``` at cylc-5 too; we've just lost the ```--quick``` behaviour.  I have a feeling that we actually lost it on the change from threads to process pool (the change "snuck in" above was probably just cleaning up some left-over cruft) and that I had discussed this (probably with Matt) via email.  Clearly the benefits of multiprocessing outweigh this loss ... but is there now a need to restore this functionality? (perhaps modified as a result of comments above...).

**Comment by matthewrmshin** [comment]
I think if we can have a way to re-trigger unfinished event handlers on restart and/or on demand, then the `--quick` functionality is probably redundant.

**Comment by arjclark** [comment]
> I have a feeling that we actually lost it on the change from threads to process pool (the change "snuck in" above was probably just cleaning up some left-over cruft) 

@hjoliver - that was my thought too. I also had it in mind that we'd had "fun" with shutdowns on the move to the process pool.

> ...and that I had discussed this (probably with Matt) via email.

@dpmatthews and I were of a mind that there'd been various discussions round this but neither he nor I had any records of it or if this was the final intended state.

**Comment by hjoliver** [comment]
The "gcylc inconsistency" part of this is fixed by #1291.

**Comment by hjoliver** [comment]
[meeting] - we agreed: the default `--now` shutdown should run queued event handlers etc., but provide an option to skip these.

**Comment by hjoliver** [comment]
Need to decide: 
 * run handlers before shutdown or after restart?
 * before shutdown, wait for process pool to finish with anything queued to it (not done now?)
 * empty the queue, ignore job submits, run event handlers (and poll and kill?) before exiting.

**Comment by matthewrmshin** [comment]
This is best done after #1827. We can then add a database table to store information on any uncompleted event handlers for current tasks. On restart, these event handlers can then be re-triggered.

**Comment by hjoliver** [comment]
@matthewrmshin - did you decided that running the event handlers before shutdown is more difficult for some reasons, or that doing it on restart is more general because it'll work for any kind of shutdown (e.g. hard kill of suite daemon)?

**Comment by matthewrmshin** [comment]
I think we should still try to do both.

**Comment by hjoliver** [comment]
Good, agreed.
