### ISSUE TITLE
cylc gui: simulation mode doesn't stop

### ISSUE THREAD

**Issue by kaday** [cylc/cylc#1284]
When running in simulation mode using the `stop` button in teh GUI does nothing. It has to be shutdown via command line using `shutdown --now`.

**Comment by arjclark** [comment]
@kaday - I'm not able to reproduce this with a simple suite. Do you have an exemplar where it does break?

(Mine for reference)
```
[scheduling]
    initial cycle point = 20100101T00
    [[dependencies]]
        [[[T00]]]
            graph = foo[-P1D] => foo

[runtime]
    [[foo]]
        command scripting = sleep 5; echo a message; sleep 5
        [[[remote]]]
            host = $(rose host-select)
```

ran as:
```
cylc run <SUITE> --mode=simulation
cylc gui <SUITE>
```
and pressed the stop button. Suite stopped once the running task finished.

**Comment by kaday** [comment]
An example suite is to follow.
More information:
 * If a task state is changed to failed then the `stop` button in the GUI then the suite does not stop once the running task has finished. This was done to check graphing functionality.

**Comment by hjoliver** [comment]
In a simple test suite with a linear task graph, resetting a succeeded task to failed doesn't prevent the suite shutting down on the 'stop' command after the next task succeeds (tested in simulation mode)... so we need a reproducible test case.

**Comment by kaday** [comment]
@hjoliver 
This is the suite which it breaks:
```
[scheduling]
    initial cycle point = 20150108T02Z
    [[dependencies]]
       [[[T02, T08, T14, T19]]]
          graph = """
                  A:fail => !B & !D
                  A => B
                  B:fail | A:fail => !C
                  B:fail | C => D
                  B => C
                 """
```
Manually fail task B, then press the stop button.
The suite keeps running in simulation mode. It does eventually stop, but not for a many cycles.

**Comment by hjoliver** [comment]
@kaday - thanks for the example. It seems we're not preventing (simulated) submission of simulation mode tasks prior to shutdown. The suite eventually shuts down in spite of this if there happens to be no active tasks at a point in time.  After hitting 'stop' real tasks that are ready to run still get queued to the process pool, i.e. the 'ready' state, but will not be submitted.  I'll simulate this process for simulation mode tasks...

**Comment by kaday** [comment]
@hjoliver - works in my environment and passes the test battery.
