### ISSUE TITLE
port files should contain host name

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc#1285]
On a facility with a shared filesystem (such as at NIWA), the port file (visible from all hosts) prevents a user from accidentally starting a suite that is already running on another host, but (a) it doesn't tell the user which host the suite is already running on, and (b) if a suite suffers a hard kill, the user may have to use "cylc scan" and/or "ps" on multiple hosts before manually deleting a left-over port file.

So I think it would be useful to have suite port files contain host name as well as port number.

**Comment by matthewrmshin** [comment]
See also #1050.

**Comment by hjoliver** [comment]
(this is in progress)

**Comment by hjoliver** [comment]
See #1699 for another consequence of this problem on shared filesystems.

**Comment by hjoliver** [comment]
@matthewrmshin - here's the long-forgotten branch that I started this on:

https://github.com/hjoliver/cylc/commits/1285.port-file-hostname

It looks like I made two commits, the first is for PEP8 changes that will now be irrelevant, the second looks like a first quick hack at adding the hostname to the port file (on two lines, it probably should be host:port)  The commit name suggests it was "working on localhost" and therefore presumably unfinished or untested for remote hosts.

This is probably pretty straightforward but I didn't get time to return to it today.  Let me know if you want to do it today (you can take or leave my initial hack at it), otherwise I'll try to get back on to it tomorrow.

**Comment by matthewrmshin** [comment]
@hjoliver Thanks for looking into this. I'll take a look at combining your ideas with some of mine.

**Comment by hjoliver** [comment]
OK, reassigning this to you.
