### ISSUE TITLE
Hold task after killing its job to avoid immediate retry

### ISSUE THREAD

**Issue by matthewrmshin** [cylc/cylc#1308]
When a user issue a command to kill a job of a task (with (submission) retries configured), the task can end up retrying with the same undesirable configuration (which prompted the user to kill the job in the first place).

A more desirable logic is to hold the task while issuing the kill to prevent it from retrying.

Is there any use cases of kill where the current logic is the more desirable behaviour?

**Comment by hjoliver** [comment]
> Is there any use cases of kill where the current logic is the more desirable behaviour?

I don't think so; the current logic fails to take manual job kill into account IMO.
