### ISSUE TITLE
cylc directives: add scripting interface

### ISSUE THREAD

**Issue by benfitzpatrick** [cylc/cylc#1318]
We should support something like:

``` ini
[runtime]
    [[foo]]
        ...
        [[[directives]]]
            --ll_res_id=$(grep /some/path/to/reservation.txt)
```

or

``` ini
[runtime]
    [[foo]]
        ...
        [[[directives]]]
            --time=$(( 10 + CYLC_TASK_TRY_NUMBER  ))
```

**Comment by matthewrmshin** [comment]
The 2nd use case is related to #1105.

Is shell syntax the correct interface?

**Comment by hjoliver** [comment]
Would need to execute on the task host.

**Comment by hjoliver** [comment]
What about a run-time templating system?  (task run-time, as opposed to suite parse-time). Directives could include variables whose values are supplied at runtime (somehow or other) just before the job script is generated.

**Comment by matthewrmshin** [comment]
(As an aside..., now that we bundle Jinja2 with cylc, I have been thinking of generating the job script with Jinja2. Not sure if this will help or not.)

**Comment by hjoliver** [comment]
Superceded by #2415
