### ISSUE TITLE
gcylc dot-view: collapse and expand individual namespaces

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc#132]
Currently in the dot-view we can collapse all tasks completely, with member task states shown in hover-over tool-tips, or expand them all completely.  We should probably be able to expand and collapse individual families and tasks, including intermediate namespaces,  as for the other two views.  This is a new feature request though, not a bug, so long as the right-click menu is adapted for the current situation before the next release (#133).

**Comment by oliver-sanders** [comment]
This feature would not work in transpose view.

**Comment by hjoliver** [comment]
Really - why not?
