### ISSUE TITLE
gcylc right-click menu specificity

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc#1321]
The gcylc right-click menu should be task state specific.  E.g. there's no point in attempting to poll or kill a task that is not currently active.

**Comment by benfitzpatrick** [comment]
We should also disallow launching the "Trigger" menu items for already-running jobs (if the 'running' status is wrong, users can just poll or reset the task).

**Comment by matthewrmshin** [comment]
> We should also disallow launching the "Trigger" menu items for already-running jobs

Or at least we should make it a lot more difficult to do than now.

**Comment by arjclark** [comment]
Am part way through sorting this.

**Comment by arjclark** [comment]
Closed by #1709
