### ISSUE TITLE
gcylc right-click view logs fails for a remote gcylc

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc#1329]
Viewing of suite server logs works however, because it uses the ```cat-log``` command.  We should do the same for task logs (originally ```cat-log``` didn't handle task logs, but now it does).

**Comment by matthewrmshin** [comment]
It works at our site. Perhaps I am misunderstanding the problem description?

**Comment by hjoliver** [comment]
I mean running gcylc on a remote host and attempting to view the logs of a task that runs on the suite host (i.e. not a remote task as far as the suite daemon is concerned).

**Comment by matthewrmshin** [comment]
Now I see what you meant!
