### ISSUE TITLE
User Guide: add section on changing task behaviour

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc#1334]
Maybe a small section on changing task behaviour in a running suite, including:
- [x] reload
- [x] broadcast
- [x] edit-runs

**Comment by arjclark** [comment]
@hjoliver - have re-opened as #1404 only covers edit-runs and not all the above mentioned methods.

**Comment by matthewrmshin** [comment]
https://cylc.github.io/cylc/html/multi/cug-htmlse12.html#x13-20300012.16 already covers reload.
https://cylc.github.io/cylc/html/multi/cug-htmlse12.html#x13-20600012.19 already covers broadcast.

Should this be closed?

**Comment by matthewrmshin** [comment]
I think this should be closed. Please reopen if necessary.
