### ISSUE TITLE
Fix initial cycle point conditional trigger processing

### ISSUE THREAD

**Issue by benfitzpatrick** [cylc/cylc#1340]
A graph line like this: 

```
foo[^] | bar => baz
```

will currently fail validation with:

```
ERROR: name 'foo_' is not defined
'"foo_^_ | bar"'
```

This is due to some conditional-expression regex-safety processing at the end of
cylc.config.config.generate_triggers.

**Comment by hjoliver** [comment]
Note these conditional expression labels are seen by the user in ```cylc show SUITE TASK_ID``` and *View -> prerequisites and outputs*.  E.g. when running the example of https://github.com/cylc/cylc/issues/1340#issue-57823066 on this branch:
```
$ cylc show foo baz.20140201T0000+13
TASK baz.20140201T0000+13 in suite foo:
  
PREREQUISITES (- => not satisfied):
  -     LABEL: bar = bar.20140201T0000+13 succeeded
  -     LABEL: foo_leftsquarebracket__caret__rightsquarebracket_ = foo.20140201T0000+13 succeeded
  - CONDITION: foo_leftsquarebracket__caret__rightsquarebracket_ | bar
```

 It might be better to convert conditional expression labels to something simple like "A", "B", etc. for this purpose, to give for the example above:
```
$ cylc show foo baz.20140201T0000+13
TASK baz.20140201T0000+13 in suite foo:
  
PREREQUISITES (- => not satisfied):
  -     LABEL: A = bar.20140201T0000+13 succeeded
  -     LABEL: B = foo.20140201T0000+13 succeeded
  - CONDITION: A | B
```

However, you've definitely fixed a bug and improved the internals, so I'll bang up a new issue for this.

**Comment by benfitzpatrick** [comment]
> Note these conditional expression labels are seen by the user in cylc show SUITE TASK_ID and View -> prerequisites and outputs. 

I didn't think of that! I guess we could back-convert the expressions for display purposes if we had to. I do like the idea of keeping the `[^]` part in cylc show.

**Comment by hjoliver** [comment]
[UPDATE - the comment @benfitzpatrick was responding to was deleted and moved to the pull request that I had intended to write it on in the first place :grimacing: https://github.com/cylc/cylc/pull/1345#issuecomment-75518007]
