### ISSUE TITLE
simulation mode: occasional "sticking"

### ISSUE THREAD

**Issue by arjclark** [cylc/cylc#1348]
Raising this as an awareness.

A small number of users have experienced issues with suites getting stuck while running in simulation mode. A task will get to the running state but never proceed from there.

At this time we've been unable to reproduce the bug and it doesn't seem consistently reproducible.

I believe this has stopped being broken at some point between cylc 6.1.2 and 6.3.0 but cannot say for sure. Code tidy at #1294 may relate.

If no-one experiences the problem post our site-wide adoption of 6.3.0 I'll close the issue.

@hjoliver - have any of your users reported anything like this?

**Comment by hjoliver** [comment]
We haven't seen this, but I think simulation mode is not heavily used here.  I have a feeling #1294 might have fixed this too, but I haven't even been able to reproduce the problem at an earlier version.  A test suite that consistently stalls in this way after a while would be nice.

**Comment by arjclark** [comment]
>  A test suite that consistently stalls in this way after a while would be nice.

Agreed, unfortunately consistency has thus far proven elusive. I'll see what I can do.

**Comment by arjclark** [comment]
There haven't been any reports of this in some time and we weren't able to create a recipe for reproducing it, so closing as invalid.
