### ISSUE TITLE
Cycling syntax: `T00` *after* the initial cycle point?

### ISSUE THREAD

**Issue by benfitzpatrick** [cylc/cylc#1353]
It would be very useful if we could specify e.g. `[[[ T00 ]]]` task after (but not including) the
initial cycle point. This is addressed one way through the `[[[ +PT6H/PT6H ]]]` approach (
see #1278), but this doesn't work if we cannot constrain the initial cycle point and have
different behaviour for particular times.

This is strongly linked to #1279, which suggests a `min(` syntax for a related problem.

Some ideas for shooting down (I dislike all of these, but the last one the least):
```
        [[[T00>]]]
```
```
        [[[T00>^]]]
```
```
        [[[icp_gt(T00)]]]
```
```
        [[[not_icp(T00)]]]
```
```
        [[[^+T00]]]
```

**Comment by hjoliver** [comment]
I suppose we can't just say this is a solved problem once we *can* constrain the ICP?  For instance we might want to constrain the ICP to be any one of 00, 06, 12, or 18, but still have a task that starts at the next T00 regardless of which it is (so +PT6H won't do it).

I think I prefer your second notation, as "+" (in the last example) is suggestive of adding a fixed interval.

**Comment by benfitzpatrick** [comment]
:+1: from a user for this

**Comment by benfitzpatrick** [comment]
:+1: again

**Comment by benfitzpatrick** [comment]
Let's discuss this when we meet up

**Comment by benfitzpatrick** [comment]
[[[T00!^]]] is what we've decided on. !  can be used to specify gaps in recurrences as well...

Make sure it's OK for syntax highlighting
