### ISSUE TITLE
Removing a task doesn't immediately trigger a run-db update.

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc#1358]
Just noticed in our operation: a failed task proxy was removed (without spawning) from a running suite in which nothing else was happening at the time. Gsummary continued to display the failed task even though it no longer existed.  Nudging the suite fixed the problem.

**Comment by arjclark** [comment]
I'd have thought removing a task wasn't relevant to the run-db? Or is this just a case of how things are bundled together?

**Comment by hjoliver** [comment]
I guess ```cylc gsummary``` interrogates the run-db, not the suite daemon, to set what tasks exist in what state.  So, in the case described above, gsummary says there is a failed task in the suite when that is in fact no longer true.

**Comment by matthewrmshin** [comment]
I had a quick discussion with @benfitzpatrick about this. `cylc gsummary` uses `cylc cat-state`, so we are not sure why this is related to the run DB.

**Comment by hjoliver** [comment]
You're right, it is the internal suite state that isn't being updated.  To test this, btw:
```
[scheduling]
    [[dependencies]]
            graph = foo => bar & baz

[runtime]
    [[foo]]
        command scripting = false
```
Run the, remove the failed task, then run ```cylc cat-state```.

**Comment by hjoliver** [comment]
A nudge does it, so this will be an easy fix.
