### ISSUE TITLE
Extended targetting of multiple task proxies by cylc commands?

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc#1359]
Currently cylc commands that interact with a suite daemon can select multiple tasks by family name or regular expression, for a given single cycle point.  Users have occasionally requested the ability to target multiple task instances (at different cycle points) at once.  We could potentially allow more general targetting in several ways, e.g. multiple task IDs, multiple task names, task name regex, multiple cycle points, cycle point range.  Presumably if names and points were given separately, we'd need to convolve them together to get a list of specific task IDs.

**Comment by matthewrmshin** [comment]
The syntax discussed in https://github.com/cylc/cylc/issues/960#issuecomment-121634220 is related.
