### ISSUE TITLE
[cylc] job submission error with pbs overriding

### ISSUE THREAD

**Issue by w21085** [cylc/cylc#1371]
I added pbs overriding  to `suite.rc` file. (cylc 6.2.0 later)

for example,
```cfg
[[[job submission]]]
  method = pbs
  command template = qsub -V %s
```

if overriding `command template` in `suite.rc`, the error of submission will be occurred.

I saw a defect after inspecting codes, 
(I have just little knowledge for Python. I've studied for only two days. Please consider my poor ability of python.)

In my opinion, line 312 in `lib/cylc/batch_sys_manager.py` is wrong. 
Please review the codes.

I seem It be right as following:
```python
            batch_sys_cmd = batch_submit_cmd_tmpl % job_file_path
```

If not fixed, in case of overriding pbs command template, the job_file_path will include `{job:   }` and therefore can not find the job script file.

What I know another solution is to change the overriding syntax.
(user guide seems to be modified)

example)
in suite.rc.
```cfg
[[[job submission]]]
  method = pbs
  command template = qsub -V '%(job)s'
```

**Comment by matthewrmshin** [comment]
@w21085 This appears to be a documentation issue. The logic is deliberate to force the path name of the job file to be explicit in the template.

The alternate way of specifying `-V` is to use a directive instead. (You will get a `#PBS -V` line in the job file.) E.g.:
```cfg
[[[job submission]]]
    method = pbs
[[[directives]]]
    -V =
```
