### ISSUE TITLE
Deprecate "command scripting" to "script" or "scripting"?

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc#1384]
The term "command scripting" annoys me.  Primarily, the word "command" is unnecessary.  Secondarily (and much less annoyingly) the word "scripting" was originally chosen to imply a piece of the job script, not an entire script in itself, but just "script" would probably do (especially as it is often just used to invoke an external script).

So: @matthewrmshin et. al. - would you agree to the following changes, possibly with ```ing``` appended to each? (deprecations, of course, so it won't break anything):
 * ```command scripting``` to ```script```
 * ```pre-command scripting``` to ```pre-script```
 * ```post-command scripting``` to ```post-script```
 * ```environment scripting``` to ```env-script```
 * ```initial scripting``` to ```init-script```

**Comment by matthewrmshin** [comment]
I agree to the change.
