### ISSUE TITLE
cylc validate: cycle point but no cycles defined bad error

### ISSUE THREAD

**Issue by kaday** [cylc/cylc#1387]
When the `suite.rc` has a cycle point defined but no cycles the error is:
[FAIL] cylc validate -v --strict mi-ad904 # return-code=1, stderr=
[FAIL] Incompatible value for <class 'cylc.cycling.integer.IntegerPoint'>: 20130204T0000: invalid literal for int() with base 10: '20130204T0000'
If initial/final cycle point has been defined but no cycles then the suite should fail validation with an appropriate error.

This was a single cycling suite and needed an [[[R1]]] section, it was not a integer cycling suite.
An initial cycle point had been provided but no cycling sections.

**Comment by matthewrmshin** [comment]
Example:

```cfg
[scheduling]
    initial cycle point = 2015-01-01
    final cycle point = 2015-01-01
    [[dependencies]]
#        [[[R1]]]  # <==== need this
            graph = foo
```

**Comment by matthewrmshin** [comment]
Similar problem:

```
[scheduling]
    cycling mode = gregorian
    initial cycle point = 2015-01-01
    final cycle point = 2015-01-01
    [[dependencies]]
#        [[[R1]]]  # <==== need this
            graph = foo
```

gives:

```
Conflicting syntax: post-cylc-6 syntax (cycle point: [scheduling]initial cycle point = 2015-01-01) vs pre-cylc-6 syntax ([scheduling][[dependencies]]graph: mixed with date-time cycling)
```

**Comment by kaday** [comment]
@benfitzpatrick and I have decided that the last one is a suitable error and should not be changed.
