### ISSUE TITLE
Prevent traceback on scheduler error, unless --debug

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc#1408]
Runtime exceptions currently cause a knarly-looking traceback that scares some users.  Most of the time this is unnecessary - e.g. on SuiteConfigError - essentially a validation error - just printing the error message would be better, unless ```--debug``` was used.

**Comment by matthewrmshin** [comment]
(Agreed, but only known errors that are caught. Errors that are not caught should still result in a traceback - there is nothing more cryptic that a random Python error string.)

**Comment by hjoliver** [comment]
[closing] we now agree with @matthewrmshin

**Comment by matthewrmshin** [comment]
(Mark as invalid. Will open individual issues on a case by case basis.)
