### ISSUE TITLE
Task proxies should remember their log files across restarts.

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc#1411]
https://github.com/cylc/cylc/pull/1401#issuecomment-91056516

(can we just assume standard logs exists in the standard location, based on task state?)

**Comment by matthewrmshin** [comment]
> (can we just assume standard logs exists in the standard location, based on task state?)

Yes, we can.

(This is somewhat related to #992, i.e. the plan to migrate to cylc the functionality of `rose suite-hook`, which writes locations of job logs to an sqlite file for Rose Bush.)
