### ISSUE TITLE
Command to cancel suite stop?

### ISSUE THREAD

**Issue by benfitzpatrick** [cylc/cylc#1427]
Should we have a command to abort a suite stopping? Stopping is not always quick, and people change their minds...

**Comment by matthewrmshin** [comment]
> Stopping is not always quick, and people change their minds...

@benfitzpatrick Please change your mind about this...

**Comment by benfitzpatrick** [comment]
It's @steoxley's mind to begin with!

How about if we get another 'no' from a team member, we'll close the issue?

**Comment by hjoliver** [comment]
I'm not a definite "no", but it doesn't make me hugely happy.  We'd have to make each part of the extended shutdown process reversible.  Which may be easy enough, but I'm not sure offhand.

**Comment by kaday** [comment]
I am also a "no". They can restart if they want. @benfitzpatrick I say close it.

**Comment by arjclark** [comment]
3rd no from me - @kaday's answer is pretty much spot on what should be done.

**Comment by matthewrmshin** [comment]
Enough votes. I'll close this.
