### ISSUE TITLE
Task name filtering should filter out graph base nodes too.

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc#1440]
(currently it doesn't)

**Comment by matthewrmshin** [comment]
@hjoliver I have totally forgotten the context of this issue. Could you please elaborate?

**Comment by hjoliver** [comment]
When I put this issue up, name filtering removed live nodes from the graph view as expected, but not the empty "base nodes" with filtered-out names.  This suite shows the problem **at cylc-6.4.1** on filtering for `foo|baz` for example:
```
[scheduling]
    cycling mode = integer
    initial cycle point = 1
    [[dependencies]]
        [[[P1]]]
            graph = """foo => bar & baz => qux
                bar[-P1] => bar"""
```

However, it seems that this probably has been fixed in the ~18 months since then!  Closing...
