### ISSUE TITLE
cylc validate: ( foo & bar => baz not fail validation

### ISSUE THREAD

**Issue by kaday** [cylc/cylc#1442]
Examples:
```cfg
[scheduling]
    [[dependencies]]
                    graph = """
                        (foo | bar => baz
                    """
```
fails validation as expected, but
```cfg
[scheduling]
    [[dependencies]]
                    graph = """
                        (foo & bar => baz
                    """
```
does not.

**Comment by kaday** [comment]
Check for pairs of brackets, i.e. the number of "(" matches the number of ")".

**Comment by arjclark** [comment]
Does something like this fail validation:
```
[scheduling]
    [[dependencies]]
    ...
        [[[T00]]]
                    graph = """
                        (foo & bar[-P1D] => baz
                    """
```
(Am kind of hoping so or the code for the pre-initial cycle dependencies filtering isn't working as intended)

**Comment by kaday** [comment]
This is covered and would fail validation as it counts left and right brackets to see if the number of them is equal.
