### ISSUE TITLE
Suite log, out, err rotation should be synchronized

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc#1446]
Currently these are rotated independently according to file size.  It would be better to rotate all files with the log (which is biggest), so that the content matches across them all.

**Comment by arjclark** [comment]
+1 - Very much agreed.

**Comment by matthewrmshin** [comment]
See also #386.

**Comment by matthewrmshin** [comment]
I must admit I am a bit confused by the current setting with these multiple modules:
* `cylc.suite_logging`, which deals with `log` and `err`.
* `cylc.suite_log_interface`, which provides a Pyro interface to `err` via `cylc.suite_logging`.
* `cylc.suite_output`, which deals with `out` and `err`.

We need to do something to rationalise these.

**Comment by hjoliver** [comment]
(a late-night look-in here)

> We need to do something to rationalise these.

Yes, hence #386 (2 yrs old, gack).

In historical context it's not completely insane, however: ```cylc.suite_logging``` just configures the standard python logging facility (log message format etc.), which (as configured) happens to write WARNING and CRITICAL messages to stderr as well as the event log;  ```cylc.suite_output``` redirects ```sys.std(out|err)``` to the suite log directory (this was added when the server became daemonizable?); and ```cylc.suite_log_interface``` is the new(ish) Pyro interface to the err log (this is used only by the gcylc info bar to highlight warnings and errors).

**Comment by matthewrmshin** [comment]
See also #846.

**Comment by hjoliver** [comment]
Agreed this should still be done.
