### ISSUE TITLE
Refactor task prequisites/outputs.

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc#1468]
The old code for handling task prerequisites and outputs (which are closely related) is over-complicated. 

 * The prerequisite code is pretty much duplicated between non-conditional and conditional prerequisites, because when conditional triggers were first allowed they were handled differently, by transforming them into Python expressions and using ```eval``` to get the Python interpreter to evaluate them.  We should just treat all trigger expressions the same way, avoiding use of eval at the last minute, for non-conditional expressions, if that provides any performance advantage.

 * (moved to #1604)

**Comment by matthewrmshin** [comment]
Sounds like a good plan.
