### ISSUE TITLE
cylc reload: higher verbosity in logs

### ISSUE THREAD

**Issue by arjclark** [cylc/cylc#1484]
When carrying out a reload it can be difficult to determine what is being reloaded and when in relation to other events occurring in a suite based on the current logs.

We should look to increase the verbosity of what is recorded to make it easier to discern what's going on when trying to identify problems occurring during a reload.

**Comment by arjclark** [comment]
It may also be useful to have gcylc display the bouncing back and forth loading bar for while a reload is happening (as per shutting down).

**Comment by hjoliver** [comment]
@arjclark - maybe you tested this on an outdated branch?  On current master:

![reload-log](https://cloud.githubusercontent.com/assets/2362137/7983337/6f3e4274-0b13-11e5-82b5-58a35de91465.png)

![reload-progbar](https://cloud.githubusercontent.com/assets/2362137/7983342/78f49962-0b13-11e5-9d5d-9925be9794ee.png)

(I should lowercase the task reload lines though)

**Comment by arjclark** [comment]
Well that's reassured me I wasn't going mad at least - was sure the gui already did that but we couldn't make it do it this morning!

I'll take a look through and check there's nothing else we wanted for the logs, but you're right already looks like what we want's there (the curse of having so many different versions on the go!).

**Comment by hjoliver** [comment]
Maybe you're even less mad than you think.  This looks suspiciously like a variant of #1485 - a final cycle point, and hence gcylc status "running to ... " and the progress bar doesn't show up.  You wanna take a look at this?

**Comment by arjclark** [comment]
Yeah, I'll have a dig and see if I can work out what's going on here.
