### ISSUE TITLE
gcylc:  pause button missing when started with --hold

### ISSUE THREAD

**Issue by kaday** [cylc/cylc#1485]
Example:
```
[cylc]
    UTC mode = True

[scheduling]
    initial cycle point = 20150501T00
    final cycle point   = 20150601T00
    max active cycle points = 1
    [[dependencies]]
        [[[T00]]]
        graph = A => B => C & D & E & F

[runtime]
  [[A,B,C,D,E,F]]
    command scripting = echo "hello"
```
`
cylc run --hold
`
Press play, this works, however you cannot hold the suite again.

**Comment by kaday** [comment]
Actually it has gone when I try to run the suite with not options.

**Comment by hjoliver** [comment]
This seems to happen only when the suite defines a final cycle point.

**Comment by hjoliver** [comment]
My fault, in 6b8296058a2c42f27e93737dcb85774b41dea037 for #1395 (after last release, fortunately).
