### ISSUE TITLE
Gsummary should use the new port scanning functionality.

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc#1488]
From #1480  ```cylc scan``` can retrieve task state totals directly from all suite daemons on all scanned hosts, without requiring authentication.  ```cylc gsummary``` needs to be updated to use the same information.  Currently it gets task state totals from ```cylc cat-state```, which requires file access rights (we will still need this for suite stop summaries, however).

@benfitzpatrick - as the architect of gsummary, can you knock this one off?  It should be a fairly extensive simplification, as ```cylc scan``` now prints out exactly the required information.

**Comment by hjoliver** [comment]
[update: now on #1480 scan only reports state-totals if publicly available on a per-suite basis (or if you have the passphrases).  Gsummary should probably do the same, even if states are available via the filesystem, so that private suites are kept private.]

**Comment by hjoliver** [comment]
For this issue, we should add a new scan option, e.g. ```cylc scan --raw```, to print all scan information in an easy-to-parse format.

**Comment by hjoliver** [comment]
After this, gsummary will be essentially a nice scan GUI - so can we change (or deprecate, or at least alias) the command name from ```cylc gsummary``` to ```cylc gscan```?

**Comment by matthewrmshin** [comment]
> so can we change (or deprecate, or at least alias) the command name from `cylc gsummary` to `cylc gscan`?

Sounds good. (It can even be `cylc scan --gui`.)
