### ISSUE TITLE
Task expiry times?

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc#1491]
An interesting idea from Milton Woods (BoM): 

> It could be useful to skip tasks if their results are not required when the suite is late. For example, we often generate files and transfer them to remote systems, overwriting previous results with the latest data. It may save time during a catchup run (after an outage) if only the final files were transferred. Obviously this logic could be included in the task scripts, but I would prefer to capture all of the time dependencies in the suite definition.

 We could allow tasks to have an expiry time expressed (like clock trigger times) as an offset from their own cycle point.  When a task triggers, if the difference between wall clock time and cycle point is greater than the expiry time, the task should not submit.  It would be very easy to implement this if we can just log a message and put the expired task into the 'succeeded' state.  However, it might be preferable to create a new 'expired' state (and have any downstream tasks expire too?).

@cylc/core - any thoughts on this?

**Comment by arjclark** [comment]
Interesting idea, it'll be how we handle downstream tasks that'll be the interesting problem. I'm not sure setting to succeeded is the correct behaviour though as the task hasn't actually succeeded, it has been bypassed/skipped, so 'expired' is preferable (though that adds another state to the system to handle).

**Comment by kaday** [comment]
Agreed, this is interesting. I agree with Andy that they should not be set to succeeded, but am not sure what they should be set to, maybe 'expired'?

**Comment by arjclark** [comment]
> and have any downstream tasks expire too?

On further reflection, I think I'd leave them alone unless they were part of the "expire after=FOO" like settings.

**Comment by arjclark** [comment]
Just to note though, that going against adding an "expired" state is that we'd have to update all the guis, utilities etc.
