### ISSUE TITLE
Efficient management of multiple task jobs

### ISSUE THREAD

**Issue by matthewrmshin** [cylc/cylc#1505]
The current system can be quite inefficient (to system resources) for managing task jobs. E.g. an operation to poll or kill all task jobs can create a system load storm due to multiple SSH + batch system calls.

We can probably group job submits (or poll or kill) for each (host, batch system), so that we can issue a single SSH command (and where possible a single batch system command) for each (host, batch system).

See also #474 and #1307.

**Comment by hjoliver** [comment]
Excellent idea.
