### ISSUE TITLE
Cylc monitor shows different status when suite is restarted vs. run normally

### ISSUE THREAD

**Issue by trwhitcomb** [cylc/cylc#1508]
I'm used to running suites with no end time showing `R_U_N_N_I_N_G` as the suite is running in the monitor display.

However, if I shut down the suite, and then use `cylc restart` to get it going again, the monitor shows `S_T_O_P_P_I_N_G__A_T__None` rather than a running state.  Everything appears to be fine, but this display isn't what I expect.  Looking at the logic, I'm not sure how this happens since an actual `None` should evaluate to a logical False in the `cylc-monitor` script - perhaps a string "None" is getting through somehow?  I traced it back to the Pyro calls where I'm quickly out of my league.

I realize this is a nitpick but what are issue trackers for if not to deprioritize trivial things like this :)

**Comment by hjoliver** [comment]
Yeah, I've noticed this several times myself, then forgotten about it (an equal number of times, evidently!).

Reproduced on current master.  It also affects the GUI ("running to None" in the status bar).
