### ISSUE TITLE
Creation of zombie (defunct) processes by background jobs.

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc#1510]
Batch scheduler job submission commands tell the batch server (PBS or whatever) to queue a job, then they detach immediately.  To submit such a job in cylc, a process pool worker runs the submission command in a subprocess and then calls ```proc.wait()``` (or ```proc.communicate()```) which blocks until the job submission command completes and then collects its exits status and output - thus preventing the job submission command process from becoming a zombie).

There is no detaching job submission command for a background job - it is just the job itself (or rather ```cylc job-submit JOB_FILE```).  We try to fake a detaching mechanism for background jobs by simply having our multi-processing pool workers run the job in the background (duh) - and not calling ```proc.wait()``` as above, which would block until the job itself finished.  This means a single worker can submit new backgrounds job without waiting for previous jobs to finish.  However, it also means every background job submission command becomes a zombie until the same process pool worker actions the next command (in small test suites this is more obvious for failed tasks just because they're more likely to stall the suite and prevent the next job submission).

Actually, it seems somewhat surprising that the zombies disappear at next job submission - presumably multiprocessing process internals must poll for finished child processes and call ```proc.wait()``` on them at that point (but not regularly, in between jobs)??

Ideas on what to do about this:

 1. Just document the creation of temporary (till next job submission) zombie processes as  a "feature" of background job submission.  They don't use system resources, so it's just an annoyance. 
 2. Call ```proc.wait()``` straight away on background jobs, as for batch scheduler job submission commands.  This eliminates zombies, but the max number of background jobs that could run at once would then be equal to the number of pool workers (and a full pool would block other non-background jobs from submitting too).
 3. Create some kind of daemonizing wrapper for background jobs: launch the job as a daemon, report its PID, and then exit immediately??
 4.  Maybe we can hack the guts of the ```multiprocessing``` package to make workers poll regularly for finished child processes and then call ```wait()``` on them, even between job submissions.

@cylc/core - thoughts?

**Comment by hjoliver** [comment]
Here's suite that demonstrates the problem. The clock trigger stalls the suite with one succeeded task that can't be removed yet.
```
[cylc]
    cycle point format = %Y-%m-%dT%H
[scheduling]
    initial cycle point = now
    max active cycle points = 1
    [[special tasks]]
        clock-trigger = bar(P1D)
    [[dependencies]]
        [[[T00]]]
            graph = foo => bar
[runtime]   
    [[root]]
        script = "sleep 20"
```
Result with process pool size 1:

![zombie1](https://cloud.githubusercontent.com/assets/2362137/8246596/6c546e34-1695-11e5-9638-32249f93e505.png)
![zombie2](https://cloud.githubusercontent.com/assets/2362137/8246599/70c907ae-1695-11e5-874d-d38a40248fd2.png)

If I trigger the succeeded task again, the zombie process is replaced.  With a bigger pool size, zombies persist until their own parent worker process gets hit with another job submission.

**Comment by benfitzpatrick** [comment]
I like 3), if we can figure it out. zombies **α** bigger pool size would explain why @trwhitcomb saw so many

**Comment by matthewrmshin** [comment]
I had previously discussed this with @dpmatthews but never got round to raise an issue, but we were going to introduce a new job submission method to run the job file with something like the `nohup` or `setsid` command. This is probably not so different to point 3.

If I remember correctly, the reason why we don't detach the `background` job is to handle a requirement of some sites where users' background jobs are killed as soon as they are detached. My guess is that these sites are encouraging all jobs to be submitted to the designated batch systems? If this is the case, our current `background` logic is really encouraging them to break their local rules...

**Comment by matthewrmshin** [comment]
See also #445.

**Comment by hjoliver** [comment]
> If I remember correctly, the reason why we don't detach the background job is to handle a requirement of some sites where users' background jobs are killed as soon as they are detached. 

That's right.

> If this is the case, our current background logic is really encouraging them to break their local rules...

Agreed.  We could reverse this.  The 'at' scheduler is almost universally available as an alternative anyway.

**Comment by matthewrmshin** [comment]
Yes, I think a `background` job should normally detach. (The easiest way to implement is to invoke the job script with `nohup`.) We can perhaps support a non-detach mode as well - suitable for jobs that return instantaneously or for jobs that can hang (e.g. an install task that the whole suite depends on).
