### ISSUE TITLE
Poll tasks when "allow resurrection" is True.

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc#1514]
From Milton Woods (BoM):

> One more possible item for your list came up in our discussion with Ben. It was about a problem with job pre-emption by PBS, where the same signal is used to terminate the job whether it is pre-empted or killed. So cylc will mark the job as failed even when it is pre-empted. If the task starts running after pre-emption, cylc will ignore messages from the task unless an "allow resurrection" option is enabled. We agreed that it would probably be confusing for operators to see a task fail and then start running magically. As a solution to this problem, Ben mentioned another idea that I liked. For tasks where "allow resurrection" is true, cylc could poll the task status in PBS to determine what had happened.

**Comment by matthewrmshin** [comment]
This is a particular problem for us as well. There are several related problems.
* Retry is not handled.
* PBS may hang on to a job for a while after a normal kill, so a poll may not tell the full story.

**Comment by matthewrmshin** [comment]
If a task job receives a signal, we need to ensure that:
* It is not killed by the user via the suite.
* It has fully exited the batch system.

Retry and dependency on failed status can only be triggered if there is no job associated with the task in the batch system. A poll with some delay can probably determine what is happening:
* Job is in batch system and is in queue or running state, then its status at the suite should be reset to submitted or running respectively.
* Job is in batch system, but is exiting, then try polling again later.
* Job is no longer in batch system - it has really died, we can now safely set the task to fail or retry.

**Comment by benfitzpatrick** [comment]
This is a tricky issue, but our workaround is to disable resurrection and configure PBS to not restart pre-empted jobs. If a site reports this as an ongoing issue, we can bump up the priority and take a look.

**Comment by matthewrmshin** [comment]
Superseded by #1792.
