### ISSUE TITLE
cylc.rundb: new table for current broadcasts settings

### ISSUE THREAD

**Issue by matthewrmshin** [cylc/cylc#1519]
The `broadcasts` table added in #1493 records all broadcast events. Although it is possible to use it to determine the current broadcast settings, it is not the easiest thing to do. We should probably rename the table as `broadcast_events` and add a new table called `broadcast_states` for the current broadcast settings (c.f. `task_events` and `task_states`).

**Comment by hjoliver** [comment]
Sounds good.   (But do you have any use-case in mind, for needing to get current broadcast settings other than via the suite daemon?)

**Comment by matthewrmshin** [comment]
Nothing immediate. However, we can potentially do the following:
* On restart, load broadcasts from suite run time database, instead of from pickle in state file.
* Display current broadcasts in Rose Bush (or its successor).

**Comment by hjoliver** [comment]
(note you have not assigned this for review yet... just checking that is intentional)

**Comment by hjoliver** [comment]
(re deleted comment - thought I was on the associated pull request page :grimacing: )
