### ISSUE TITLE
Family timing information.

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc#1524]
Another user request:

> Currently families show no timing information in cylc. Would it be possible to add this? T-submit & T-start would come from the first task in that family to startup; T-finish from the last to finish.
> [and ...] we could see how long an entire cycle took to complete.

I'm not sure this would be very useful at whole-cycle level, but it would be good for task families.

**Comment by matthewrmshin** [comment]
Timing and other metrics can be very useful for questions such as:
* What are the total and elapsed times consumed by a cycle?
  * ... for jobs submitted to a given batch system?
* And for other resources, if they are collectable.

**Comment by hjoliver** [comment]
This isn't trivial as task families are virtual - currently we don't actually know when a family is finished, because family syntax is expanded in terms of member tasks when the suite is parsed.

**Comment by hjoliver** [comment]
Closing as superseded by #1894
