### ISSUE TITLE
Pre-initial dependence problem in warm starts.

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc#1540]
```
[scheduling]
    initial cycle point = 2015
    [[dependencies]]
        [[[R1]]]
            graph = start
        [[[P1Y]]]
            graph = start[^] => foo
```
After a cold start, every instance of ```foo``` depends on ```start[2015]```.   After a warm start at a later cycle, that dependence gets ignored forever because it is wiped out by our pre-initial-dependence handling.

**Comment by hjoliver** [comment]
(slightly off topic, but related)

Ignoring pre-initial dependence is really just a trick to allow suite writers to be lazy in their thinking about suite start-up.   This suite would stall at start-up if we did not ignore ```foo[2014]```:
```
[scheduling]
    initial cycle point = 2015
    [[dependencies]]
        [[[R1]]] # first cycle point
            graph = start => foo
        [[[P1Y]]]  # every cycle point (including the first)
            graph = foo[-P1Y] => foo
```
Since cylc-6 though, we have the ability to handle any start-up scenario correctly without ignoring pre-initial dependence:
```
[scheduling]
    initial cycle point = 2015
    [[dependencies]]
        [[[R1]]] # first cycle point
            graph = start => foo
        [[[R/+P1Y/P1Y]]]  # second and subsequent points
            graph = foo[-P1Y] => foo
```

IMO we should **deprecate ignoring of pre-initial dependence** and require users to think properly about suite start-up.  It is the sort of trick that could prove to have anticipated side effects in edge cases (I can't really think of any, but arguably the warm start problem above is one ... although we could treat warm starts differently). 

However, I'm not expecting this to be a popular idea :grimacing:!

**Comment by hjoliver** [comment]
Back to warm starts.  It seems to me we have to either:
 * insert pre-warm-start tasks in the 'held' state as suggested above, or
 * further complicate pre-initial handling by distinguishing between cold and warm starts, and temporary (e.g. ```foo[-P1Y] => foo```) and permanent (e.g. ```start[^] => foo```) pre-initial dependence ... and still insert the permanent ones as held or succeeded in warm starts.

**Comment by hjoliver** [comment]
BTW a warm start is technically a restart without reference to a prior state, so really the correct way to handle it is not to assume anything about what happened prior to the warm start - i.e. put prior tasks - that are depended on by new tasks - in in the `held` state and let the operator say what should happen.

**Comment by hjoliver** [comment]
Interestingly the gcylc graph view doesn't behave properly either, for a warm start with `start[^] => foo` - a `start` base node appears, but for the wrong cycle point, and its cycle point changes as the suite evolves.

**Comment by hjoliver** [comment]
[NOTE - I have move comments on ignoring pre-initial tasks to #1544 and edited them out of this issue]

**Comment by hjoliver** [comment]
Another unfortunate side-effect of our pre-initial handling in warm starts:
```
[scheduling]
    initial cycle point = 2015
    [[dependencies]]
        [[[R1]]]
            graph = """INSTALL
                   install_1 => install_2 & install_3"""
        [[[P1Y]]]
            graph = INSTALL[^] => foo
[runtime]
   [[INSTALL]]
   [[[install_1, install_2, install_3]]]
        inherit = INSTALL
```
(i.e. an initial R1 family with internal dependencies).

After a warm start I need to rebuild a model used by the running suite.  I should be able to insert INSTALL again and trigger it, BUT our pre-initial handling at warm start also wipes out the internal dependencies among the INSTALL family members.

**Comment by arjclark** [comment]
As a thought, if the warm start time is recorded somewhere (see e.g. #1587) and kept separate from the initial cycle point, I *believe* it would be a relatively easy change to the existing code to make only pre-initial cycle dependencies get pruned and keep pre-warm but post-initial ones around on performing a manual insert.

Conversely, after a warm-start has been carried out, any tasks that exist before the warm start point in the pool must have been manually inserted in some way, so shouldn't have dependencies fixed. Should be similarly easy to fix, and probably the better way to go, as it would allow an inserted task to cycle forward, maintaining dependencies, up to the warm cycle point.

**Comment by hjoliver** [comment]
[meeting] 
 * on reflection, the first comment above isn't really a problem unless `start` hasn't finished when you do a warm start 
  * it's not unreasonable to assume that a warm start implies all previous cycle points have finished
 * we can solve the family insertion problem above pretty easily by *only wiping out pre-start dependencies that cross the start point*. 

Therefore, this issue more or less evaporates :neutral_face:. Supersede with #1905 for the family (or workflow) insert problem.
