### ISSUE TITLE
Allow state reset of individual message outputs. 

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc#1550]
As argued in #1551, we should not assume that all message outputs need to be completed when a task finishes.  Therefore we need to able to manually reset the state (completed or not) of  individual message triggers, not just just force them all to completed when the task state is reset to succeeded.

**Comment by matthewrmshin** [comment]
I guess the task state in our current logic should really be only be considered as a summary of the furthest point reached by the task. Perhaps we can represent the full picture by a dict with keys being the names of available states and outputs and values being timestamps when the states are done, like this?

```python
{
    "submit": TIME-STAMP,
    "submit-fail": TIME-STAMP,
    "start": TIME-STAMP,
    "custom-output-1": TIME-STAMP,
    # ... and so on
}
```

**Comment by hjoliver** [comment]
That seems a good idea.

**Comment by hjoliver** [comment]
Note https://github.com/cylc/cylc/pull/1551#issuecomment-124285305
