### ISSUE TITLE
cylc gui: separator between 'poll' and 'kill'

### ISSUE THREAD

**Issue by benfitzpatrick** [cylc/cylc#1566]
We should have more of a separation between 'Poll' and 'Kill' in the task
right-click menu.

**Comment by matthewrmshin** [comment]
Is this a case for a confirmation prompt before a kill?

**Comment by hjoliver** [comment]
Is the reason for this issue that users are accidentally killing tasks?   Poll and Kill were grouped together because unlike other commands/menu-items they act on real task jobs rather than just manipulating suite daemon state in some way.

**Comment by benfitzpatrick** [comment]
> Is the reason for this issue that users are accidentally killing tasks?

Yes, and I've just done it myself!
