### ISSUE TITLE
gcylc - hold button doesn't change during a long reload?

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc#1569]
Reported by a user: if a suite reload is yet to complete because some tasks are running, clicking on the "hold" button in the GUI does cause the suite to hold, but the button doesn't change to the "play/release" state.

**Comment by arjclark** [comment]
@hjoliver - been trying to reproduce this for a user here. Was a problem in earlier releases but doesnt appear to be broken on current head (double checked and fine at 6.10.1 - not working at 6.8.1 though which was my reference version). Can we close this?

**Comment by hjoliver** [comment]
@arjclark - thanks for the heads up.   Closed by #1806 / #1805
