### ISSUE TITLE
cylc syntax highlighting: support multiline Jinja2

### ISSUE THREAD

**Issue by benfitzpatrick** [cylc/cylc#1573]
It would be nice if all the syntax highlighting configurations supported multiline Jinja2 - e.g. support:
```
{# My comment starts here
# and ends here #}
```

**Comment by hjoliver** [comment]
@benfitzpatrick - it works in Vim (however, I may be using an improved vim syntax file that I've never pushed to the repostory, will check soon...)

**Comment by oliver-sanders** [comment]
Comments of the form:
```
{# foo
 # bar #}
```
confirmed as working for vim, emacs, kate and gedit

Comments of form:
```
{# foo
   bar #}
```
confirmed as broken for kate and emacs
