### ISSUE TITLE
gcylc - connection polling should reset after any user activity

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc#1576]
If a gcylc instance has reduced connection polling (suite was down for a while), then the suite is restarted from the CLI (say), then changing views etc. (even running commands such as 'nudge' from the GUI) does not result in suite data reappearing.

**Comment by arjclark** [comment]
@matthewrmshin - could this be what Howard was reporting?

**Comment by matthewrmshin** [comment]
Clicking on `View > Reset Connection Polling` works?

**Comment by hjoliver** [comment]
> Clicking on View > Reset Connection Polling works?

That works, but it has to occur to the user that the GUI "isn't working" because the connection polling has slowed up after a period of inactivity.  This even catches me out sometimes.   If the user starts messing with view settings, I think we could take that as indicator to reset the connection polling.  If the suite really isn't running, polling will settle down again soon enough.

**Comment by matthewrmshin** [comment]
Perhaps it is worth making `View > Reset Connection Polling` (and the next poll time) more visible? (A countdown to the next poll?)

**Comment by hjoliver** [comment]
That's not a bad idea.

**Comment by benfitzpatrick** [comment]
>  If the user starts messing with view settings, I think we could take that as a reason to reset the connection polling

:+1:

**Comment by benfitzpatrick** [comment]
Fully closed by #1877.
