### ISSUE TITLE
cylc trigger: report error if task is missing from task pool

### ISSUE THREAD

**Issue by benfitzpatrick** [cylc/cylc#1577]
No error is reported when triggering a task that's been removed from the task pool (e.g. if it had succeeded and been cleanup-cutoff'ed).

**Comment by benfitzpatrick** [comment]
For example, this suite:

```ini
[cylc]
    UTC mode = True
[scheduling]
    initial cycle point = 1
    final cycle point = 6
    cycling mode = integer
    [[dependencies]]
        [[[P1]]]
            graph = foo[-P1] => foo
[runtime]
    [[foo]]
        script = """
if [[ $CYLC_TASK_CYCLE_POINT -eq 4 ]]; then
    cylc trigger -f $CYLC_SUITE_NAME foo 1
fi
"""
```

will only run `foo.1` once, not twice.

**Comment by hjoliver** [comment]
Probably the same for other commands too, if targeting a non-existent task proxy (should check at least).

**Comment by arjclark** [comment]
You may want to see what I documented for the communications API for things that weren't returning anything to try identify other similarly affected commands (bit out of date now)

**Comment by benfitzpatrick** [comment]
I'll close this as a duplicate of #1330.
