### ISSUE TITLE
record warm start times for restarts

### ISSUE THREAD

**Issue by arjclark** [cylc/cylc#1587]
It would potentially be quite useful for restarts to have knowledge of prior warm start cycle points.

This would address the problem of restarting following a warm start when not all the tasks in a suite have cycled. In that situation a suite currently stalls as the restart rebuilds dependencies that the warm start had previously ignored.

Relates to #1585 and #1286

**Comment by hjoliver** [comment]
@arjclark - see #1540 and #1544.  IMO this is just another unfortunate consequence of ignoring pre-initial triggers instead of using the full power of the new graph syntax to handle suite start-up properly.

**Comment by arjclark** [comment]
Yeah, aware of those two. It's all related in various ways...

**Comment by arjclark** [comment]
Waiting on #1570 to be merged as that touches on code I'll need to be tweaking for this.

**Comment by hjoliver** [comment]
@arjclark - before working on this can we consider https://github.com/cylc/cylc/issues/1587#issuecomment-135874677 ?  I'm a bit concerned that we'll just be adding a series of elaborate  workarounds to compensate for problems created by of pre-initial ignoring.  I'd rather deprecate the feature and explain clearly (a) how to do start-up properly with the new graph syntax; and (b) that the problem mentioned on this issue is a potential consequence of using the deprecated feature.

**Comment by arjclark** [comment]
@hjoliver - part way commenting on that :wink: 

Having had a think and a dig through the code I've been wondering if this might be slightly different.

As far as #1544 goes, I disagree and wouldn't want to go down that route until such times as pre-iso8601 cycling is fully removed from cylc. 

#1540 is definitely closely related and were we to adopt the "insert held task" approach where the operator has to decide what state those tasks should be in (though I can see that getting a bit horrendous where there are potential links between two pre-warm start cycle tasks that could have an affect on their relative states - e.g. if foo succeeds then bar should fail and vice versa, or possibly that if foo succeeds then bar would be suicided out).

I've been asked to create a "master" ticket grouping all these dependencies related issues for discussion/addressing so I'll go do that before proceeding any further.

**Comment by hjoliver** [comment]
> As far as #1544 goes, I disagree and wouldn't want to go down that route until such times as pre-iso8601 cycling is fully removed from cylc. 

@arjclark - note that in #1544 (if you read it to the bottom) I'm only advocating *deprecation* of pre-initial ignore (and perhaps requiring deliberate use of it), and using that as an excuse not to add more complicate workarounds.  We could still use it with old-style syntax for as long as we retain that.

Moving to the new umbrella issue now #1603

**Comment by hjoliver** [comment]
[meeting] - agreed this should be easily solved once we record warm state point in the db.

**Comment by arjclark** [comment]
Attempts so far have shown really easy to record but using it proving difficult...
