### ISSUE TITLE
Triggering off short-lived task states.

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc#1600]
Currently, in the following suite task `bar` triggers when `foo` finally enters the failed state after 3 retries, rather than immediately after `foo` first triggers:
```
 [scheduling]
    [[dependencies]]
       graph = foo:start => bar

[runtime]
    [[foo]]
        script = exit 1
        retry delays = 3*PT10S
```

It works correctly if a short sleep is added to the task scripting before `exit 1`.

**Comment by matthewrmshin** [comment]
I think this is because we have the statement `self.outputs.set_all_incomplete()` under `TaskProxy.job_execution_failed` when there is a retry lined up. Is this statement necessary? Can we simply remove the statement?

**Comment by hjoliver** [comment]
> Is this statement necessary?

I guess the logic was that a retrying task has been reset to a pre-run state, during which it should not record any outputs as completed because it has not started running yet (albeit, running again).  I can  imagine a restart of `foo` in `foo:start => bar` in which we want to reset `bar` to waiting so that it triggers again when `foo` runs again. That wouldn't work if we do as you suggest.

**Comment by matthewrmshin** [comment]
> I can imagine a restart of `foo` in `foo:start => bar` in which we want to reset bar to waiting so that it triggers again when `foo` runs again.

But surely, this will contradict with any fix to this issue? Should `foo:start` be the 1st time `foo` has achieved the `running` (i.e. `start`) state?

I can also imagined that you can have triggers such as:

```
foo:output1 => bar
```

In which case, it is likely that `foo` has generated a file for `output1`, so it should be safe to trigger off `bar` regardless of what comes after `foo:output1` (unless a 2nd `foo:start` will wipe out the result of `foo:output1`).

This leads me to think about a scenario where an unlucky 2nd submission can lead to:

```
foo.1 job 01 started
foo.1 job 01 failed
foo.1 retry
foo.1 job 01 submit failed
```

Currently, this will lead to a final state of `submit failed`, but should it actually be `failed`, given that `failed` was logically the *furthest* state reached by the task?
