### ISSUE TITLE
cylc dependencies issues

### ISSUE THREAD

**Issue by arjclark** [cylc/cylc#1603]
We now have a number of issues open which relate to our underlying handling of cylc dependencies and how they have had unforeseen consequences:

#1544 - wants to look at removing the need for pre-initial cycling filtering now that the ISO8601 syntax has been implemented. The "ideal" solution would be to have users re-write their suites so this filtering isn't necessary, but there is a worry that this could massively complicate some suites. It also discusses the possibility of adding in pre-initial tasks in a held state so the operator can set appropriate states for triggering purposes.

#1540 - covers the problem of pre-initial dependencies in warm starts. It covers the situation in which our pre-initial triggering is wiping out dependencies on cycles prior to the warm-start cycle which can cause further problems. Again, the possibility of inserting tasks on which these dependencies exist in a held state for the operator to set according is suggested.

#1587 - is looking to address the problem of a restart being carried out following a warm start. In this case, the pre-initial cycling has removed tasks and dependencies from the warm started suite. Following this a subsequent restart before all tasks have had a chance to cycle has caused the suite to stall as it has no knowledge of the warm starting and that it should be ignoring dependencies. This has caused problems with several of our operational suites.

~~#1585 and #1286 relate to suites stalling as a result of never being able to fulfil a particular dependency and the desire to be able to identify the offending dependencies either so they can be flagged to the operator or so task events can be triggered.~~ **Struck through due to addition of "Stalled handler" addressing primary motivations behind this.**

~~#1570 - contains a refactor of the prerequisites class to bear in mind when looking at the above.~~ **Merged**

@cylc/core - can we please now take a look at these issues and discuss here. Is it time for some refactoring of the underlying way in which pre-requisites are being handled? Do we really want to add further complexity to the cylc code to be handling these situations? Is re-writing suites to address some of these issues appropriate or will it add massive amounts of extra complexity and harm readability?

**Comment by arjclark** [comment]
@hjoliver - please clarify any of the above issues that you raised where my summary isn't quite right

**Comment by hjoliver** [comment]
A few comments:

> #1570 - contains a refactor of the prerequisites class to bear in mind when looking at the above.

This only matters as a source of conflicts (i.e. wait for the merge).  It unifies the old "plain" and "conditional" prerequisite types, but does not change the essence of what "prerequisite" means in cylc (certainly not in any way that affects this issue).

**Comment by hjoliver** [comment]
In my analysis the issues above *all* result from our cylc-5 pre-initial handling wiping out dependencies that it should not wipe out.  The only partial exception to this is that un-meetable prerequisites #1585  can also result from other ways of wiping out tasks - namely user error as commented in https://github.com/cylc/cylc/issues/1585#issuecomment-140234708.

**Comment by hjoliver** [comment]
To mitigate the work required by users to adapt, we can retain the current level of pre-initial handling as an option (preferably non-default, but not necessarily) but explain that the reason to change is to avoid the aforementioned issues with the old method.  That's my opinion anyway :grimacing:

**Comment by arjclark** [comment]
> [and a restart after changing the graph and not inserting new tasks?]

Correct, yes.

**Comment by hjoliver** [comment]
[meeting] - closing this as other @cylc/core members have convinced me that we can properly manage the issues above by refining the current pre-start ignore code bit.
