### ISSUE TITLE
cylc gui: view prequisites and outputs fails

### ISSUE THREAD

**Issue by benfitzpatrick** [cylc/cylc#1616]
At current master, the cylc gui `View -> prereq's and outputs` menu item doesn't work.
It pops up a dialog saying:
```
'Prerequisite' object has no attribute 'message'
```

**Comment by matthewrmshin** [comment]
It works for me. Please provide a better recipe to repeat.

**Comment by kaday** [comment]
Fails for me on master, I get a two part error, the first as Ben's and then this one in a new window 
```
gcylc has a problem.

Traceback (most recent call last):
  File "/net/home/h02/kerryday/cylc.git/lib/cylc/gui/app_gcylc.py", line 1571, in popup_requisites
    [pre, out, extra_info] = result[task_id]
TypeError: 'NoneType' object is unsubscriptable
```

**Comment by matthewrmshin** [comment]
Again, please provide a better recipe to repeat.

**Comment by kaday** [comment]
Simply run a suite and in the cylc GUI right click on a waiting task and select `View -> prereq's and outputs` then it complains for me. Does that help?

**Comment by matthewrmshin** [comment]
Yes, I have tried that, and it works for me.

**Comment by hjoliver** [comment]
I can reproduce reliably on master with `examples/task-states/` and task `foo`, but not `cfoo`.

**Comment by hjoliver** [comment]
The root cause of this a typo in my recent prerequisite refactor that affects retrieval of prerequisites for viewing, from task with conditional trigger expressions only (hence the above trouble in reproducing the error, I suspect):
```
cylc show states foo.20120811T0000+12 --debug
/home/oliverh/SUITES/task-states/passphrase (oliverh@niwa-34403.niwa.local)
title: (not given)
description: (not given)
Traceback (most recent call last):
  ...
AttributeError: 'Prerequisite' object has no attribute 'message'
```
