### ISSUE TITLE
cylc gcylc: filter option in gcylc.rc

### ISSUE THREAD

**Issue by kaday** [cylc/cylc#1619]
User request for a `filter on` option in gcylc.rc so that when the gcylc GUI opens it filters the tasks, for example not showing the `succeeded` tasks.

**Comment by oliver-sanders** [comment]
Closed by #1701?

**Comment by matthewrmshin** [comment]
Closed by #1833.

**Comment by matthewrmshin** [comment]
#1701 is in fact a duplicate of this.
