### ISSUE TITLE
cylc scan: reduce scanned suite log verbosity

### ISSUE THREAD

**Issue by benfitzpatrick** [cylc/cylc#1623]
At the moment, for new suites and new cylc scan, a `cylc scan` by anybody on a host will result in a log entry under `INFO` for all new cylc suites on that host:
```
2015-10-02T14:03:25Z INFO - [client-command] identify gruffalo@deepdarkwood.com gruffalo
```

This would be a problem when it scales up (e.g. in the extreme, for 200 users all running `cylc gscan`, you would get ~200 logged messages per minute). We should reduce it to DEBUG.

[EDIT: only one message per client uuid... but it is probably still worth doing if you have lots of users]

**Comment by benfitzpatrick** [comment]
7f65dd6 is a possible fix for this, but I haven't run it through the test battery

**Comment by hjoliver** [comment]
The fix looks right (although I haven't tested it either).  Perhaps we should log a count of scan connections though, e.g. per minute, just to get an indication of what's going on in case of really heavy scan usage?
