### ISSUE TITLE
complete missing gscan functionality

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc#1625]
See https://github.com/cylc/cylc/pull/1586#issuecomment-136676930

Missing options:
- [ ] --all
- [x] --name
- [ ] --owner

**Comment by matthewrmshin** [comment]
See also #1302.

**Comment by matthewrmshin** [comment]
Looks like `--owner` can actually be done via `--user` in `cylc gscan`, although we should make it clearer that listing is for a given user ID.

We need to agree the behaviour of the `--all` option, as `cylc gscan` currently uses `cylc cat-state` for stopped suites as well. It is probably not a good idea to scan for stopped suites for *all* users. Can we agree that if `--all` is specified, we simply do a scan for running suites?

**Comment by hjoliver** [comment]
Agreed.
