### ISSUE TITLE
cylc validate: family OR logic problem

### ISSUE THREAD

**Issue by matthewrmshin** [cylc/cylc#1626]
A user reports this error while trying to validate a rather complex looking suite.
```
object of type 'NoneType' has no len()
'ERROR, failed to instantiate task c'
```
The problematic expression looks a bit like this `A[-PT24H]:fail-any | B[-PT12H]:fail-any => c`. Replacing `|` with `&` allows validation to pass, but obvious this does not do what the user want.

The failure comes from [cylc.conditional_simplifier.ConditionalSimplifier.clean_expr](https://github.com/cylc/cylc/blob/master/lib/cylc/conditional_simplifier.py#L113).

I was trying to reduce the suite some what. I end up with something like this.

```
[cylc]
    UTC mode = True
[scheduling]
    initial cycle point = 2000
    final cycle point = 2020
    [[dependencies]]
        [[[T00]]]
            graph = """
                A
                B
                A[-PT24H]:fail-any | B[-PT12H]:fail-any => c
"""
        [[[T12]]]
            graph = B
[runtime]
    [[A]]
    [[B]]
    [[a1]]
        inherit = A
    [[b1123456789, b2123456789, b3123456789, b4123456789]]
        inherit = B
    [[c]]
```

Unfortunately, the error appears to have moved to [cylc.conditional_simplifier.ConditionalSimplifier.flatten_nested_expr](https://github.com/cylc/cylc/blob/master/lib/cylc/conditional_simplifier.py#L147), which looks like this:

```
sequence item 2: expected string, NoneType found
'ERROR, failed to instantiate task c'
```

Strangely, if I remove the UTC mode, or have fewer characters for the `b*` tasks, validation would succeed.

**Comment by hjoliver** [comment]
Bug active at cylc-6.4.1 - i.e. prior to #1570 (prerequisite refactor) - just checking.

**Comment by hjoliver** [comment]
Here's a cut-down version of your example that still exposes the bug:
```
[scheduling]
    initial cycle point = 2000
    [[dependencies]]
        [[[T00]]]
            graph = """
                A
                B
                A[-PT24H]:fail-any | B[-PT12H]:fail-any => c"""
[runtime]
    [[A]]
    [[B]]
    [[a1]]
        inherit = A
    [[b1a, b2a, b3a]]
        inherit = B
    [[c]]
```
