### ISSUE TITLE
Error in code that updates CYLC_DIR for remote host

### ISSUE THREAD

**Issue by MartinDix** [cylc/cylc#1628]
In our environment cylc is installed in different locations on the suite host and the supercomputer.

_job_submit_prepare_remote in batch_sys_manager.py fixes the job file by changing the line in the prelude
```python
prelude() {
    export CYLC_DIR='/usr/local/cylc/cylc-6.7.0'
```

6.6.1 had
```python
LINE_PREFIX_CYLC_DIR = "export CYLC_DIR="
...
if line.strip().startswith(self.LINE_PREFIX_CYLC_DIR):
  ... modify line 
```

In 6.7.0 the strip is gone, 
https://github.com/cylc/cylc/blob/master/lib/cylc/batch_sys_manager.py#L760
```python
if cur_line.startswith(self.LINE_PREFIX_CYLC_DIR):
```
and the match fails. With the strip() added back we get
```python
prelude() {
# N.B. CYLC_DIR has been updated on the remote host
    export CYLC_DIR='/projects/access/apps/cylc/6.7.0'
```
as expected.

**Comment by hjoliver** [comment]
Thanks @MartinDix.

@matthewrmshin - can you take this, and check for other "stripping" issues in the new batch sys manager (there's quite a bit of `cur_line.startswith()`...)?
