### ISSUE TITLE
cylc gui: prog bar error

### ISSUE THREAD

**Issue by arjclark** [cylc/cylc#1631]
User reported this error on pressing the stop button in their suite:

![adam_crash](https://cloud.githubusercontent.com/assets/2562650/10364786/4a5073c8-6db6-11e5-87fa-1b9054508e5f.png)

**Comment by hjoliver** [comment]
Wow, your users sure know how to give the graph view a work out! :grimacing:

**Comment by arjclark** [comment]
> Wow, your users sure know how to give the graph view a work out! :grimacing:

Yeah, that would be the same user who reported the memory leak :wink:
