### ISSUE TITLE
gcylc: not connecting properly

### ISSUE THREAD

**Issue by arjclark** [cylc/cylc#1640]
User reported error, no recipe for reproducing but seen several times now (admittedly by same user).

On starting up suite the bottom left [connected/stopped] box flashes between its two settings and views aren't populated. This stays the case. Opening a new gui is fine.

**Comment by hjoliver** [comment]
I saw this myself two days ago, but wasn't able to investigate at the time, and now I can't reproduce it :grimacing:.

**Comment by hjoliver** [comment]
@arjclark - I think this was probably caused by #1725 (fixed)  - close if you agree.

**Comment by arjclark** [comment]
Haven't seen this reported in ages, believe its been fixed.

**Comment by matthewrmshin** [comment]
(Reassign milestone to match #1725.)
