### ISSUE TITLE
test battery: misbehaving tests on VMs

### ISSUE THREAD

**Issue by matthewrmshin** [cylc/cylc#1656]
Follow on from #1648:

`tests/retries/02-submission-retry.t` test 2 is failing on Ubuntu 15.04.

The following fails on Ubuntu 14.04:

```
./tests/events/01-task.t                                        (Wstat: 0 Tests: 2 Failed: 1)
  Failed test:  2
./tests/events/07-task-iso.t                                    (Wstat: 0 Tests: 2 Failed: 1)
  Failed test:  2
```

These 2 are the same tests. One of the tasks fails to record an event for some reason.

**Comment by hjoliver** [comment]
`tests/authentication/07-back-compat.t` may be fixed by https://github.com/cylc/cylc/pull/1658#issuecomment-152369740 ?

**Comment by matthewrmshin** [comment]
> `tests/authentication/07-back-compat.t` may be fixed by [#1658 (comment)](https://github.com/cylc/cylc/pull/1658#issuecomment-152369740)?

Wonderful.

**Comment by matthewrmshin** [comment]
Updated issue description, now that `tests/authentication/07-back-compat.t` is fixed by #1658.

**Comment by hjoliver** [comment]
These tests are also misbehaving on one of my systems.  The consistently pass if run alone, but regularly fail if run together.

**Comment by matthewrmshin** [comment]
The tests are consistently passing on my Ubuntu 15.10 environment, so I think I'll close down this issue. Please open a new issue if tests are failing again.
