### ISSUE TITLE
gcylc job file tailing broken on AIX.

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc#1659]
(this is something I should have tested properly before recent changes went in, now that NIWA is pretty much alone in using Loadleveler)

**Comment by matthewrmshin** [comment]
@hjoliver (Let me know what the problem is, if you need any help. Are you using the default `tail -F` command? Perhaps the syntax is not compatible for the `tail` command on AIX? Is it possible to add a configuration in `global.rc` to use an alternate `tail` command, e.g. a GNU one?)

**Comment by hjoliver** [comment]
I've confirmed this is an AIX problem, not Loadleveler.

**Comment by hjoliver** [comment]
In `lib/cylc/gui/tailer.py`:
```python
R_CMD_TMPL = "tail --pid=`ps h -o ppid $$` -n +1 -F %(filename)s"
```
AIX is :hankey:
 * `tail` has no `--pid` option
 * `ps` has no `h` option to exclude the header line
 * `ps` does not take a command line argument (`$$`) if `-` options are used
 * `ps -o ppid='' -p $$` works on Linux and AIX, but AIX prepends a space to the output!

This works at the command line:
```python
R_CMD_TMPL = "/opt/gnu/bin/tail --pid=$(ps -o ppid='' -p $$ | tr -d ' ') -n +1 -F %(filename)s"
```

But it still doesn't work in gcylc...

**Comment by hjoliver** [comment]
> But it still doesn't work in gcylc...

That was the space in `tr -d ' '` getting lost in `shlex.split()`.  So this works on AIX:
```python
R_CMD_TMPL = "/opt/gnu/bin/tail --pid=$(ps -o ppid= -p $$ | sed -e 's/[[:space:]]//') -n +1 -F %(filename)s"
```

**Comment by hjoliver** [comment]
I'll make this configurable next...

**Comment by matthewrmshin** [comment]
Should be possible to do:

```cfg
[hosts]
    [[my-aix-host]]
        [[[batch systems]]]
            [[[[loadleveler]]]]
                out tailer = "/opt/gnu/bin/tail --pid=$(ps -o ppid= -p $$ | sed -e 's/[[:space:]]//') -n +1 -F %(filename)s"
                err tailer = "/opt/gnu/bin/tail --pid=$(ps -o ppid= -p $$ | sed -e 's/[[:space:]]//') -n +1 -F %(filename)s"
```

(May be easier to put the whole command in a wrapper?)

```cfg
[hosts]
    [[my-aix-host]]
        [[[batch systems]]]
            [[[[loadleveler]]]]
                out tailer = /path/to/tailer %(filename)s
                err tailer = /path/to/tailer %(filename)s
```

**Comment by hjoliver** [comment]
Note this is platform specific, not batch-system specific.

**Comment by matthewrmshin** [comment]
(Acknowledged that my suggestion above is a quick workaround.)

**Comment by hjoliver** [comment]
> (Acknowledged that my suggestion above is a quick workaround.)

It also doesn't work, because the tailer config items get substituted with `job_id` not `filename` :grin:
