### ISSUE TITLE
atq on AIX is useless to us

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc#1661]
The joys of AIX :grimacing:.   In addition to https://github.com/cylc/cylc/issues/1659#issuecomment-153193433, `atq` on AIX does not list running jobs, only queued jobs yet to start running are reported. Cylc job poll for `at` jobs on AIX therefore reports job failed even if the job is running.  It's not particularly likely that anyone is submitting jobs to `at` on AIX, but for completeness we should probably have some way of telling cylc that such jobs cannot be polled.

**Comment by matthewrmshin** [comment]
@hjoliver I cannot think of an easy way to fix this right now - if the batch system cannot even be trusted!

(`at` is becoming less relevant on most platforms these days, as most sites expect users to submit stuffs under a proper load balancing system. We have come across sites which deliberately leave `at` broken in some horrible forms to discourage users from using it.)

**Comment by hjoliver** [comment]
I agree, this would not be easy to fix, and is probably not worth fixing.  But so long as we support 'at' jobs, maybe we should at least emit a warning that job poll (and maybe kill too) will be disabled for 'at' jobs on AIX if a user tries to do that.

I've always thought of 'at' jobs in cylc as essentially just 'background' jobs with a genuine detaching job submit (we have to sort of fake that for background jobs).

**Comment by matthewrmshin** [comment]
@hjoliver We think we may be seeing this on a Linux box as well for some long running jobs, but I am not yet able to repeat this - `atq` appears to show running jobs in my environment. I have opened PR #1717. Do you think you can test it in an AIX box to see if this fixes the reported problem or not?

**Comment by hjoliver** [comment]
Comments on the PR.
