### ISSUE TITLE
gcylc - better command output display?

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc#1671]
The old `gcapture` text windows (used to capture output from subprocess commands executed by gcylc) (a) are usually overkill - there's often little or no output; and (b) look really clunky.

@matthewrmshin - do you think it'd be worthwhile replacing with the `rose suite-run` dialog or something similar (I'm not sure how easy it would be to plug in the current rose code )?

**Comment by matthewrmshin** [comment]
@hjoliver Did you mean something like the dialog in `rose config-edit` when you press the button to run a suite?

**Comment by hjoliver** [comment]
Sorry, yes that's what I meant - the `rose config-edit` dialog for `rose suite-run` output.

**Comment by hjoliver** [comment]
[meeting]
  * 'later' - irritating but not so important
