### ISSUE TITLE
The 'Add A Prerequisite' option has been removed

### ISSUE THREAD

**Issue by malcolmbrooks** [cylc/cylc#1704]
Using cylc 6.4.1 I can right-click on a task and have the option to 'Add A Prerequisite'.

This option is very useful for debugging failed tasks in a suite as it allows you to insert fcm_make_um, fcm_make2_um tasks (for example) and set up dependencies so that the first taks can be triggered, followed by fcm_make2_um and a forecast run happen automatically. 

This is very as you can continue with other work while the compile and forecast tasks run. Without  it, each task in the chain needs to be triggered manually which makes debugging issues much slower.

pull request #1570 seems to be a likely cause of this loss of functionality.

**Comment by hjoliver** [comment]
@malcolmbrooks - you're right, sorry for the inconvenience :grimacing:

This was deliberate, we didn't realise anyone used the feature, and I also thought that the same thing could be more straightforwardly achieved with a quick suite shutdown and restart (now that this can be done even if tasks are running at the time, there should be no need to wait around for tasks to finish).   Before we consider restoring the functionality, can you consider whether or not a restart would do the trick for your use case?   Specifically: shut down "now", write "fcm_make => fcm_make2 => forecast" into the graph (presumably this is not already in the graph or you wouldn't need to use "add a prerequisite"??), restart (possibly in the held state), insert new task instances if necessary, then trigger the first one.

**Comment by hjoliver** [comment]
@malcolmbrooks - you can also change dependencies with a suite reload, if you don't want to do a full restart.  If you're using the gcylc graph view, it will update once the new tasks are inserted, or before that if you restart the view (by switching briefly to another view).

**Comment by hjoliver** [comment]
Another difference: you'll probably want to reverse the change to the graph again afterward.  @cylc/core - any opinions on restoring this feature, using reload or restart as I've suggested, or some other way of achieving the same result?

**Comment by matthewrmshin** [comment]
> @cylc/core - any opinions on restoring this feature

We have no strong feeling with this one.

**Comment by arjclark** [comment]
Personally I don't mind either way. I can see that a button is more convenient than shutting down and restarting to add in and subsequently remove though.

**Comment by hjoliver** [comment]
@arjclark, "add a prerequisite" was more than just a button click - presumably @malcolmbrooks would have had to insert several new tasks then use it several times (with the right arguments) to make them depend on one another in the right order.   With more than one or two tasks I think a quick suite edit + reload or restart would probably be easier.  But I'll await word from Malcolm, to see if he agrees or not...

**Comment by arjclark** [comment]
I'll leave it to @malcolmbrooks to clarify how he was using this but going back and having a quick play with 6.4.0 it's still much more trivial for me to add a one-off dependency to a running suite via the click menu item and type a task.cyclepoint entry in a box. As I say, I don't mind either way (tbh I'm only commenting on this issue as @matthewrmshin encouraged me to have a think about it so you got feedback from several of @cylc/core) but one is definitely simpler to work with than the other for one-off dependency additions.

**Comment by hjoliver** [comment]
@arjclark - I certainly agree that for a single task the old option was easier.   But I still think that it sounds "advanced" and would likely be little used.  Also, what it achieves is effectively a change to the suite structure (albeit a temporary change), which requires a reload or a restart in any other context.  I can still restore it if that's the consensus, I just think it's worth considering the options first.

Maybe a better way of achieving the sort of use-case that Malcom describes would be something like this: "insert a temporary sub-graph", type in "fcm_make => fcm_make2 => um_forecast" and the cycle point.  The first task(s) in the subgraph could either trigger immediately, or initially go to the 'held' state, or be made to trigger off an existing task instance.

**Comment by malcolmbrooks** [comment]
Sorry for the delay, I haven't been using github much, but it sends me too many emails to check through. I need to prune them down a bit.

The next time I need to do detailed UM debugging I will try adding the dependencies before adding a task. This wasn't a common usage, but it was very useful when it was needed.

**Comment by benfitzpatrick** [comment]
See also #986.

**Comment by hjoliver** [comment]
[meeting]
  * @arjclark  to address "later"

**Comment by malcolmbrooks** [comment]
Having worked through a UM debug process, adding a prerequisite in the graph is a usable alternative to GUI version. The 'Add a prerequisite' option was definitely easier and nicer to work with, so if it becomes possible to add it without too much work that would be appreciated.

Until then, I won't object to this issue being closed.

**Comment by matthewrmshin** [comment]
Hopefully, sub-graph insertion will be addressed when we look at #1314.
