### ISSUE TITLE
cylc gui: dot view redraw resetting selection

### ISSUE THREAD

**Issue by arjclark** [cylc/cylc#1707]
Somewhat frustratingly for users with large suites using the dot view of cylc gui, it seems that whenever a redraw happens the view gets reset so you are no longer focused on the area of interest.

@benfitzpatrick - I seem to remember we had a similar problem with treeview, can you advise?

**Comment by benfitzpatrick** [comment]
The tree view is nearly always incrementally updated rather than cleared and rebuilt - I think the dot view needs the same approach.
