### ISSUE TITLE
Explicit Sub-suite (suite within a task) support 

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc#171]
For a sufficiently large suite (somewhere above 1000 tasks, depending)  the suite definition may take a significant amount time to parse; and at runtime a pass through the dependency negotiation algorithm may take a significant amount of time. 

The most likely reason for a very big suite is ensembles.  These are an good candidate for a sub-suite approach because ensemble members don't really need to participate individually in the scheduling pool - they naturally trigger all at once anyway.  

E.g. in "foo => ensemble => bar": instead of "ensemble" being a large family within the main suite it could be a task that runs a single cycle of another suite that contains just the ensemble member tasks.

This is already easy enough to do: just put "cylc run SUB-SUITE $CYLC_SUITE_CYCLE_TIME --until=$CYLC_SUITE_CYCLE_TIME" in the command scripting of the task that represents the ensemble in the top level suite. Be it might be good to provide explicit support for the following (and more?) features:

 1. a special sub-suite task type (or some kind of indicator) that knows how to invoke the sub-suite with the run command.

 2. support opening up a sub-suite gcontrol instance via right-click in the top level suite.

 3. support other ways of getting sub-suite information by interrogating the top-level task? 

 4. have validation recurse into sub-suites?

 5. consider transfer of information such as output directory paths from the top suite to the sub-suite: write a suite-rc include-file to be picked up by the sub-suite? use cylc's Jinja2 extension for reading in environment variables? ...

**Comment by benfitzpatrick** [comment]
Maybe we should be looking at syntax improvements or internal efficiency improvements (e.g. #107) to handle this in a better way.

**Comment by hjoliver** [comment]
To elaborate on the reasons for closing this issue:
  * sub-suites create a major housekeeping problem (every *instance* of the sub-suite needs a new suite name (e.g. sub-suite-name.cycle-point, to avoid overwriting logs) and run directory
  * job logs are not visible from the main suite
  * efficiency (parsing and runtime) is vastly improved since this issue was posted.

The remaining use-case for sub-suites is dynamic family sizing, for which a top-level solution would be best - #1636
