### ISSUE TITLE
Generate wall time directive from execution timeout, etc

### ISSUE THREAD

**Issue by arjclark** [cylc/cylc#1718]
It would potentially be quite useful/handy/convenient to automatically generate default values for execution timeouts in tasks where directives already contain things such as wallclock times.

For example:
```cfg
[runtime]
    [[foo]]
        script = something
        ...
        [[[job submission]]]
            method = pbs
        [[[directives]]]
            -q = myqueue
            -l select=1:ncpus=6:mem=5GB:arch=linux:vntype=cray_serial
            -l walltime = 00:30:00
```
would give you a default execution timeout value of the order of PT30M should you decide to add an execution timeout handler to that task.

If you wanted to increase/decrease the value you could just define it in the task as well.

**Comment by matthewrmshin** [comment]
I think it is easier if we do it the other way round, i.e. if an execution time out is specified, cylc can add the correct directive to the job file according to the job submission method.

**Comment by arjclark** [comment]
That'd be trickier for batch systems like Loadleveler where you set soft and hard limits - presumably you'd pass it through as the hard limit and then subtract something to get you the soft limit. What that something would be though could be difficult to set something sensible automatically. If you work the other way round you would take the hard limit and use that as the execution timeout value.

**Comment by matthewrmshin** [comment]
The problem is that we'll find ourselves having a lot of trouble writing time syntax parsers for the different queueing systems. It is a lot easier to format a string than to parse one.

**Comment by benfitzpatrick** [comment]
This is a bit of a can of worms, isn't it? There are features like suspend/resume that can alter this behaviour in the schedulers.

**Comment by arjclark** [comment]
> This is a bit of a can of worms, isn't it? There are features like suspend/resume that can alter this behaviour in the schedulers.

I actually don't think that's such an issue (or at least a new one). All that's being suggested is automatic generation of one of these values from the other as a sensible default. In our current system we'd still have problems with this as we'd set execution timeout to X anyway which may be "invalid", for lack of a better word, if a job that starts is subsequently suspended/resumed.

**Comment by matthewrmshin** [comment]
Following [meeting], we agreed to consider:
* Add a new runtime task setting or re-purpose the current `execution timeout` setting to specify the maximum execution wall clock time.
* For relevant batch system, generate the wall clock directive from the time out setting.
  * E.g. for `execution timeout=PT10M`, the system will insert `#PBS -l walltime=00:10:00` to a PBS job header.
* Poll intervals following execution time out?
* Redesign (with automatic upgrade) of `[job submission]` sections in `suite.rc`?

Other things to consider:
* Use the new setting to implement kill on submission/execution time out for `background` and `at` jobs. #992.

Currently, we have settings like these that I think are related to this issue:

```cfg
[runtime]
    [[TASK]]
        submission polling intervals = DURATION-LIST
        execution polling intervals = DURATION-LIST
        retry delays = DURATION-LIST
        [[[job submission]]]
            method = NAME
            command template = TEMPLATE
            shell = COMMAND
            retry delays = DURATION-LIST
        [[[events]]]
            submission timeout = DURATION
            execution timeout = DURATION
        [[[event hooks]]]
            submission timeout = DURATION
            execution timeout = DURATION
```

We can have something like this instead?

```cfg
[runtime]
    [[TASK]]
        [[[job]]]
            batch system = NAME
            batch system submit command template = TEMPLATE
            # Do we really need this?
            shell = PATH
            # Normal poll intervals while submitted/running
            submission polling intervals = DURATION-LIST
            execution polling intervals = DURATION-LIST
            # Time out settings, and poll intervals after timeout
            submission timeout = DURATION
            submission timeout polling intervals = DURATION-LIST
            execution timeout = DURATION
            execution timeout polling intervals = DURATION-LIST
            # Should these be "... retry intervals"?
            submission retry delays = DURATION-LIST
            execution retry delays = DURATION-LIST
```

**Comment by hjoliver** [comment]
[meeting] - @dpmatthews and @matthewrmshin to capture results of discussion on Monday!

**Comment by matthewrmshin** [comment]
After discussion, I think we want something like this:

```cfg
[runtime]
    [[TASK]]
        [[[job]]]
            batch system = NAME
            batch system submit command template = TEMPLATE
            # Do we really need this?
            shell = PATH

            # Normal poll intervals while submitted/running.
            # We can have `global.rc` settings for these as well even
            # when we have normal task communication,
            # to health check submitted and running jobs.
            submission polling intervals = DURATION-LIST
            execution polling intervals = DURATION-LIST

            # Execution wall time
            execution wall time = DURATION
            # Polling interval after execution wall time in `global.rc`?
            # execution wall time polling intervals = DURATION-LIST

            # Should these be "... retry intervals"?
            submission retry delays = DURATION-LIST
            execution retry delays = DURATION-LIST
```

The new `execution wall time` setting will be used to generate the wall time limit directive for a batch scheduler that supports wall time limit. The suite should kill `background` and `at` task jobs if they exceed their `execution wall time` settings.

On exceeding `execution wall time`, the suite should start poll the job after some delays (to allow the batch scheduler time to signal the job, and for `cylc message` to do its stuffs.) The polling intervals after exceeding the wall time should be `global.rc` configurable per host + batch system. (It is probably not essential for it to be suite configurable.) The task should only issue an execution timeout event if wall time is exceeded and polling is exhausted (i.e. job still in batch system for some reason).

`submission timeout` should remain an event. `execution timeout` should be automatic as described above.
