### ISSUE TITLE
job scripts: ability to have timings diagnostics

### ISSUE THREAD

**Issue by arjclark** [cylc/cylc#1719]
Context: We've seen some surprisingly long times for job scripts to fire off things like task messages in their trap routines but we're not sure where the time is being spent.

It would be useful to be able to turn on time stamps (or something to that effect) that would allow us to know how long it takes for various parts of the script to run.

**Comment by matthewrmshin** [comment]
The main problem is `cylc task message`. We are currently not passing debug mode and verbose mode to `cylc task message` in job files. We should do that, and add relevant diagnostics for these modes to `cylc.task_message`.

**Comment by matthewrmshin** [comment]
Perhaps we can switch on `set -x` with a `PS4` with time stamp information when we are in verbose+debug mode. E.g.:

```sh
PS4='[\D{%Y%m%dT%H%M%S%z}]\u@\h+ '
set -x
```
