### ISSUE TITLE
cylc gui: clickable menu options inverted

### ISSUE THREAD

**Issue by kaday** [cylc/cylc#1724]
A user noticed:
"
It seems as though the events in the right-click context sub-menus in the cylc GUI don't quite follow "conventional" rules for clickable menu items.  Specifically they appear to be bound to a "onMouseDown" type action rather than the more traditional "onMouseUp"... 

To see what I mean - grab any old suite you have running, right click on any task and go to one of the sub-menu options (these are either "View" or "Reset state" menus, for arguments sake go to the "View" menu and pick one of the log files or something) but click the option and keep the button held down.  You'll see that the pop-up spawned happens as soon as you click.  Now try the same thing with one of the top-level items in the context menu when you right click a task (e.g. the "Browse task URL" option) - clicking and holding does nothing; the pop-up only gets spawned when you release the button (and actually if you move the cursor away before you release it won't appear at all) - that is the correct expected behaviour.  
"

This should be a simple GTK issue.

**Comment by kaday** [comment]
@hjoliver Any thoughts on this? Before I look into it?

**Comment by hjoliver** [comment]
@kaday - agreed, we should change this - please go ahead and take a look at
it.
