### ISSUE TITLE
Explicit restart checkpointing?

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc#1735]
~~At the moment cylc dumps suite state at every change, and keeps a rolling archive of the most recent states.  However, it's not very easy for users to determine which state file to restart from, if not the default (most recent), and you can't go far back either because the archive length is short (by default anyway).~~

[UPDATE: as of 6.11.0, the run DB has replaced the old state dump files, including for restarts.  As of 6.11.2, the DB automatically stores checkpoints representing the most recent suite state (continually updated) plus  before and after a reload, and at restart.  We can list available checkpoints with `cylc ls-checkpoints` and restart from any stored checkpoint.]

It might be useful to allow special checkpoint "tasks" in the graph to regularly ~~dump state~~ [write state checkpoints] at special points in the workflow that the user knows they might want to return to:

```
graph = foo => bar => :checkpoint: => baz => qux
```

This could be used to backtrack to an earlier point at the behest of some kind of diagnosis task, as an extreme form of automatic error recovery.

**Comment by arjclark** [comment]
Presumably you'd need to limit the number of checkpointed dumps?

I guess this'd need to come with appropriate warnings re. rolling back and re-running previously ran tasks. I could see it potentially being useful for start/end of cycle/model checkpointing though.

**Comment by hjoliver** [comment]
[meeting]
  * agreed just CLI and GUI manual named? checkpoint 
  * no need to complicate the graph syntax - just have a task run the checkpoint command.
