### ISSUE TITLE
Colour-blind option in '> cylc monitor [ID]'

### ISSUE THREAD

**Issue by jonnyhtw** [cylc/cylc#1739]
Hi there

This issue is minor but worth pointing out I think.

I occasionally use the '> cylc monitor [ID]' facility to examine a running suite in a terminal. However this does not pick up my color-blind setting which is defined in my ~/.cylc/gcylc.rc file. This is not surprising I guess given that this is not GCylc itself but rather a command line clone thereof.

The guidance in the Cylc [http://cylc.github.io/cylc/html/single/cug-html.html#C.1.3](url) states that the chosen default colour scheme is 'common to all views' but I guess this refers to GCylc views?

Is there a way of achieving this without taking up too much time? Like I said, this shouldn't be considered urgent but would it interesting to know!

Cheers

Jonny

**Comment by hjoliver** [comment]
@jonnyhtw - thanks for the issue report.  The in-terminal monitor actually predates the GUI by a long way, and is vastly less sophisticated.  I would like to redo it - see #1685 - but not currently a high priority.  For your specific problem it would indeed be good to have the monitor automatically use the same colours as the GUI, but I'm not sure to what extent that's even possible.  Terminals typically (always?) have a discrete pallet of colours  and the ASCII terminal control colour codes are not very extensive or easy to use (I don't think there's any way of directly translating from full RGB codes): http://misc.flogisoft.com/bash/tip_colors_and_formatting

For the moment you could probably get by with a special terminal "profile" that you just use with the cylc monitor, with the colour palette adjusted as you like.

I'll close this page and add the issue as an addendum to #1685...

**Comment by jonnyhtw** [comment]
Thanks for the information @hjoliver, that's very useful to know! Let me know if you need someone to test this functionality going forward. I'd also be interested in the development of this tool if I can be of assistance.

Cheers

Jonny
