### ISSUE TITLE
gcylc graph-view "focus range" should move with the suite

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc#174]
I mostly use "focus on cycle time" to show all tasks with the same cycle time.  A cycle time range option is also provided, but it has hard limits at each end, so eventually the suite all tasks will move out of the range window leaving nothing to display. Mike Naughton has suggested it might be better to have a moving range window, probably set with respect to the greatest cycle time in the suite.

**Comment by benfitzpatrick** [comment]
Group by cycle point has helped with this. There hasn't been any further demand, and it's not totally easy to figure out the best way to implement it.

Closing for the moment - reopen if necessary.
