### ISSUE TITLE
Tasks stuck in ready state after remote submission failure

### ISSUE THREAD

**Issue by aosprey** [cylc/cylc#1741]
Occasionally we are seeing tasks getting stuck in the "ready" state. Examination of the log/suite/err file shows that the remote submission command has failed, however the failure has not resulted in a "job submission failure" being returned (see below). 

It looks like the ssh command has failed between our server and the remote HPC system, and manually re-triggering the task usually works. Ideally this would be flagged as a submission failure, so that submission retries could be used. In other cases, where for example the remote batch scheduler has returned an error, this is returned as a job submission failure. 

```
2016-02-19T13:48:21Z ERROR - 2016-02-19T13:48:20Z [jobs-submit cmd] cat /home/annette/cylc-run/u-ab712_site/log/job/20120927T2100Z/fcm_make2/01/job | cylc jobs-submit --host=login5.archer.ac.uk --remote-mode -- '$HOME/cylc-run/u-ab712_site/log/job' 20120927T2100Z/fcm_make2/01
2016-02-19T13:48:20Z [jobs-submit ret_code] 1
2016-02-19T13:48:20Z [jobs-submit err]

--------------------------------------------------------------------------------
This is a private computing facility. Access to this service is limited to those
who have been granted access by the operating service provider on behalf of the
contracting authority and use is restricted to the purposes for which access was
granted. All access and usage are governed by the terms and conditions of access
agreed to by all registered users and are thus subject to the provisions of the
Computer Misuse Act, 1990 under which unauthorised use is a criminal offence.

If you are not authorised to use this service you must disconnect immediately.
--------------------------------------------------------------------------------

ERROR: remote command failed 255
```

**Comment by matthewrmshin** [comment]
@aosprey Could you tell us...
* What version of cylc are you running? (It looks recent enough, but is worth checking.)
* Does cylc master solve this for you?
* Does #1737 solve this for you?

The reason I am asking is that I have been doing quite a lot of work in this area, and I am quite sure that I have done something already to solve this. Prove me wrong!

**Comment by aosprey** [comment]
I am running with 6.8.1 currently. I will test with master and #1737 and get back to you - hopefully you have already fixed it!

**Comment by aosprey** [comment]
@matthewrmshin Running with cylc master solves this - thanks! 

Also found that cylc master crashes when polling fails, but this is OK in your branch #1737 (so presume has been fixed).

**Comment by matthewrmshin** [comment]
@aosprey Thanks for testing. #1737 will hopefully be merged when @hjoliver is available again to review the change.

**Comment by hjoliver** [comment]
> #1737 <https://github.com/cylc/cylc/pull/1737> will hopefully be merged
when @hjoliver <https://github.com/hjoliver> is available again to review
the change.

I'm back today!
