### ISSUE TITLE
occasional blanked gcylc window

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc#1750]
In recent versions, the main gcylc window occasionally - but not infrequently - pops up entirely blank and unresponsive.  The process has to be killed to get rid of it.

@matthewrmshin - have you seen this at MO?

**Comment by matthewrmshin** [comment]
I have heard of one case recently, but I don't think the problem is widely reported.

**Comment by kaday** [comment]
Over on Windows machines we have seen it quite frequently.
I have made it occur twice in a day with about seven reloads and a about the same for suite-gcontrol. So I guess may be ~ 1 in 7 times for me.
We have only noticed it recently, for example in the last few weeks and at least four of us using Windows have experienced it. It is usually on big suites. It has been observed using reload, suite-gcontrol and opening the suite via gscan.

**Comment by kaday** [comment]
More details:
The GUI opens but blank as Hilary has said, also the task bar only says the suite name and not the suite name -hostname as it usually does.

**Comment by kaday** [comment]
![gcylc_issue](https://cloud.githubusercontent.com/assets/3693326/13496507/6f678be6-e148-11e5-9058-d51cb653e35f.PNG)

**Comment by hjoliver** [comment]
Agree with Kerry's description, and it seems not to be platform specific, so marking this as a high priority bug...

**Comment by hjoliver** [comment]
Nice if it was more reproducible, for `git bisect` :grimacing: ...

**Comment by hjoliver** [comment]
I wonder if we've added some GTK function call recently that should have been done via `idle_add()`...
