### ISSUE TITLE
remote tasks load wrong passphrase if suite name is registered remotely too

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc#1763]
If I run a suite called SUITE on SUITE_HOST that submits a task to TASK_HOST, the remote task can load the wrong passphrase if TASK_HOST also has a suite registered as SUITE (with a passphrase in its suite definition directory).

**Comment by matthewrmshin** [comment]
I guess we need to change the logic to favour the passphrase file installed under `~/cylc-run/SUITE/` before everything else.
