### ISSUE TITLE
unnecessary logging of job-logs-register failed messages

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc#1765]
```
2016-03-15T01:08:43Z ERROR - [run_topnet_CAM5_26_09015793.1] -('job-logs-register', 1) failed
```

These error messages are logged when automatic job log retrieval is turned off in site config (we don't need it on NIWA's HPCF servers thanks to a shared filesystem) AND one or both of the job.out and job.err logs are missing after a job completes.  Noticed here because loadleveler jobs get no job.err log (as opposed to an empty but existing one) if the job doesn't write anything to stderr.

**Comment by hjoliver** [comment]
@matthewrmshin - I had trouble following the relevant code in the limited time available today, but this might be an easy one for you?

**Comment by matthewrmshin** [comment]
I don't understand how this happens because we have something like this in the logic:

```python
if "job.out" in filenames or "job.err" in filenames:
```

(following the recent change in #1747.)

**Comment by hjoliver** [comment]
Hmm, I thought there must have been a distinction between retrieval and register that allowed this.  Maybe my mistake though - I'd better check tomorrow that I tested this on master, not on 6.8.1 (latest installed at NIWA).  (apologies!)

**Comment by hjoliver** [comment]
You're right, fixed by 1747!
