### ISSUE TITLE
Spurious 'job submit failed' error

### ISSUE THREAD

**Issue by dacreman** [cylc/cylc#1767]
I'm seeing a spurious error which shows that submitting a job to a batch queue has failed, when the job has actually been queued correctly. The job initially goes into the submitted state but then goes into the submit failed state. 

```
2016-03-17T11:54:35Z INFO - [atmos_uoe_zen_n48_noomp_4x4.1] -(current:submitted)> atmos_uoe_zen_n48_noomp_4x4.1 submission failed
2016-03-17T11:54:35Z ERROR - [atmos_uoe_zen_n48_noomp_4x4.1] -submission failed
2016-03-17T11:54:35Z DEBUG - [atmos_uoe_zen_n48_noomp_4x4.1] -(setting:submit-failed)
2016-03-17T11:54:35Z DEBUG - [atmos_uoe_zen_n48_noomp_4x4.1] -Queueing submission failed handler: rose suite-hook --mail 'submission failed' 'vn10.4_trunk' 'atmos_uoe_zen_n48_noomp_4x4.1' 'job submission failed'
```

We are using polling and the batch scheduler is torque. Job submission was working fine with cylc-6.3.1 and rose-2015.02.0 but not with cylc-6.8.1and rose-2016.02.1. I've attached the job-activity.log file. 

[job-activity.log.txt](https://github.com/cylc/cylc/files/177855/job-activity.log.txt)

**Comment by matthewrmshin** [comment]
@dacreman If you type `qstat`, do you get something like `97346.service0.ice.astro.ex.ac.uk` in column 1? If not, what sort of output do you get? (I don't have access to torque, so it is quite hard to replicate your problem, but polling does work on pbs.)

**Comment by dacreman** [comment]
@matthewrmshin The qstat output shows `97346.service0` in column 1 i.e. it is missing the `.ice.astro.ex.ac.uk` part.

**Comment by matthewrmshin** [comment]
This explains the problem. The old logic in cylc calls the command `qstat JOB-ID` for each `JOB-ID` it is trying to poll, and inspect the return code to see if `JOB-ID` is still in the queue or not. This is not efficient if we need to poll many job IDs. The new logic calls `qstat` once, and look to see if the relevant job IDs is in column 1 or not. Those that are missing from column 1 are assumed to be not longer managed by the queueing system.

Is there an option for `qstat` to force it to display the full job ID?
* If so, you can modify [cylc.batch_sys_handlers.pbs](https://github.com/cylc/cylc/blob/master/lib/cylc/batch_sys_handlers/pbs.py#L31) to use the option in your local install of cylc.
* If not, we'll need to think of different ways to fix this.

**Comment by dacreman** [comment]
There are two flags which expand column 1 of the qstat output. 

`qstat -l` specifies that the long name of the job is displayed and shows `97346.service0.ice.astro` in column 1 (i.e. still missing the `.ex.ac.uk`)

`qstat -a` lists the jobs in an alternative format and shows the first 16 characters of the job identifier in column 1 (i.e. `97346.service0.i`).

Adding either `-l` or `-a` to the qstat command fixes the polling problem, even though neither of these options display the full job identifier.

**Comment by matthewrmshin** [comment]
This is a bit puzzling as the logic uses simple string comparison. What are the job IDs stored as in your `job.status` files?

**Comment by dacreman** [comment]
The job.status file shows 

`CYLC_BATCH_SYS_JOB_ID=97362.service0.ice.astro.ex.ac.uk` 

and `qstat -l` shows

`97362.service0.ice.astro   atmos_uoe_zen_n  acreman                0 Q all`

so it is indeed puzzling that this is working. The job-activity.log file shows that the job is being polled and the return code is 0 each time.

**Comment by matthewrmshin** [comment]
I wonder what happens if you redirect output of `qstat -l` to a file? Does it give you different output than when it is connected to a TTY?

**Comment by dacreman** [comment]
I get the same output when redirecting qstat to a file. I can't see anything obvious which would be modifying the behaviour of qstat in addition to the -l or -a flags. Can I get cycl to report the exact qstat command it is using, and perhaps dump the output? It would be interesting to see what's going on.

**Comment by matthewrmshin** [comment]
> Can I get cylc to report the exact qstat command it is using, and perhaps dump the output?

At the moment, not easily via configuration or verbosity, but feel free to hack this bit of logic https://github.com/cylc/cylc/blob/master/lib/cylc/batch_sys_manager.py#L624 to get it to print the command and its output. I'll modify the logic in the future to do this automatically in verbose or debug mode.

**Comment by dacreman** [comment]
I've added some diagnostics as follows: 

```
        for batch_sys, exp_ids, bad_ids in items:
            if hasattr(batch_sys, "get_poll_many_cmd"):
                # Some poll commands may not be as simple                                                                                                                                            
                cmd = batch_sys.get_poll_many_cmd(exp_ids)
            else:  # if hasattr(batch_sys, "POLL_CMD"):                                                                                                                                              
                # Simple poll command that takes a list of job IDs                                                                                                                                   
                cmd = [batch_sys.POLL_CMD] + exp_ids
            try:
# Start of debug section                                                                                                                                                                             
# Redirect stdout and stderr to log files for testing                                                                                                                                                
                tempstdout = sys.stdout
                tempstderr = sys.stderr
                sys.stdout = open('log_cylc_stdout.txt','w')
                sys.stderr = open('log_cylc_stderr.txt','w')
# Record the poll command and its output                                                                                                                                                             
                sys.stdout.write('Poll command: ' + str(cmd) + "\n")
                sys.stdout.write('Output from poll command:')
                proc = Popen(cmd)
                out, err = proc.communicate()
                sys.stdout.write(out)
                sys.stderr.write(err)
# Return stdout and stderr to their previous locations                                                                                                                                               
                sys.stdout.close()
                sys.stderr.close()
                sys.stdout = tempstdout
                sys.stderr = tempstderr
# End of debug section                                                                                                                                                                               
                proc = Popen(cmd, stderr=PIPE, stdout=PIPE)
            except OSError as exc:
                # subprocess.Popen has a bad habit of not setting the                                                                                                                                
                # filename of the executable when it raises an OSError.                                                                                                                              
                if not exc.filename:
                    exc.filename = cmd[0]
                sys.stderr.write(str(exc) + "\n")
                return
```

With `POLL_CMD = "qstat -l"` in batch_sys_handlers/pbs.py I get the following in log_cylc_stdout.txt
```
Poll command: ['qstat -l', '97381.service0.ice.astro.ex.ac.uk']
Output from poll command:[TASK JOB SUMMARY]2016-03-18T11:50:47Z|1/atmos_uoe_zen_n48_noomp_4x4/01|pbs|97381.service0.ice.astro.ex.ac.uk||||2016-03-18T11:47:45Z||
```

and in log_cylc_stderr.txt I get
```
[Errno 2] No such file or directory: 'qstat -l'
```
which suggests that the qstat is not actually running when the flag is added. To check this I put  `POLL_CMD = "wibble"` in batch_sys_handlers/pbs.py and the behaviour is the same as with `POLL_CMD = "qstat -l"` and I see
```
Poll command: ['wibble', '97388.service0.ice.astro.ex.ac.uk']
Output from poll command:[TASK JOB SUMMARY]2016-03-18T12:45:44Z|1/atmos_uoe_zen_n48_noomp_4x4/01|pbs|97388.service0.ice.astro.ex.ac.uk||||2016-03-18T12:40:41Z|2016-03-18T12:44:56Z|
```
and
```
[Errno 2] No such file or directory: 'wibble'
```
from stdout and stderr respectively. 

When the job polling command is not working (as described above) the job remains in the submitted state until it completes. The job I ran completed successfully and the job registered success the next time it was polled. It looks like breaking the command for polling the batch queue stops the job going into the submit-failed state producing behaviour that almost works - I hadn't noticed that the job never makes it into the running state.

**Comment by matthewrmshin** [comment]
OK. Can I suggest that you make a change like this?

```diff
diff --git a/lib/cylc/batch_sys_manager.py b/lib/cylc/batch_sys_manager.py
index 70c3892..919683c 100644
--- a/lib/cylc/batch_sys_manager.py
+++ b/lib/cylc/batch_sys_manager.py
@@ -619,7 +619,8 @@ class BatchSysManager(object):
                 cmd = batch_sys.get_poll_many_cmd(exp_ids)
             else:  # if hasattr(batch_sys, "POLL_CMD"):
                 # Simple poll command that takes a list of job IDs
-                cmd = [batch_sys.POLL_CMD] + exp_ids
+                cmd = [shlex.split(batch_sys.POLL_CMD)] + exp_ids
+            sys.stderr.write(str(cmd) + "\n")
             try:
                 proc = Popen(cmd, stderr=PIPE, stdout=PIPE)
             except OSError as exc:
@@ -631,6 +632,7 @@ class BatchSysManager(object):
                 return
             proc.wait()
             out, err = proc.communicate()
+            sys.stderr.write(out)
             sys.stderr.write(err)
             if hasattr(batch_sys, "filter_poll_many_output"):
                 # Allow custom filter
```

Run the suite on debug mode, and you should see the command and its STDOUT being written to the suite log.

**Comment by matthewrmshin** [comment]
(Sorry updated the diff.)

**Comment by dacreman** [comment]
Thanks, that works better. I'm now seeing submit-failed when the poll command is `qstat -l`. The suite log file shows:
```
2016-03-18T14:56:20Z INFO - [atmos_uoe_zen_n48_noomp_4x4.1] -setting submission poll timer for 60 seconds
2016-03-18T14:56:21Z DEBUG - 2016-03-18T14:56:21Z [jobs-poll cmd] cylc jobs-poll --debug --host=zen.astro.ex.ac.uk -- '$HOME/cylc-run/vn10.4_trunk/log/job' 1/atmos_uoe_zen_n48_noomp_4x4/01
2016-03-18T14:56:21Z [jobs-poll ret_code] 0
2016-03-18T14:56:21Z [jobs-poll out] [TASK JOB SUMMARY]2016-03-18T14:56:20Z|1/atmos_uoe_zen_n48_noomp_4x4/01|pbs|97395.service0.ice.astro.ex.ac.uk|1|||2016-03-18T14:55:18Z||
2016-03-18T14:56:21Z [jobs-poll err]

['qstat', '-l', '97395.service0.ice.astro.ex.ac.uk']
Job id                    Name             User            Time Use S Queue
------------------------- ---------------- --------------- -------- - -----
97395.service0.ice.astro   atmos_uoe_zen_n  acreman                0 Q all


2016-03-18T14:56:21Z INFO - [atmos_uoe_zen_n48_noomp_4x4.1] -(current:submitted)> atmos_uoe_zen_n48_noomp_4x4.1 submission failed
2016-03-18T14:56:21Z ERROR - [atmos_uoe_zen_n48_noomp_4x4.1] -submission failed
2016-03-18T14:56:21Z DEBUG - [atmos_uoe_zen_n48_noomp_4x4.1] -(setting:submit-failed)
2016-03-18T14:56:21Z DEBUG - [atmos_uoe_zen_n48_noomp_4x4.1] -Queueing submission failed handler: rose suite-hook --mail 'submission failed' 'vn10.4_trunk' 'atmos_uoe_zen_n48_noomp_4x4.1' 'job submission failed'
2016-03-18T14:56:21Z DEBUG - BEGIN TASK PROCESSING
2016-03-18T14:56:21Z DEBUG - 0 task(s) de-queued
2016-03-18T14:56:21Z DEBUG - END TASK PROCESSING (took 0.000350952148438 sec)
2016-03-18T14:56:21Z INFO - [atmos_uoe_zen_n48_noomp_4x4.1] -(('event-handler-00', 'submission failed'), 1) will run after P0Y (after 2016-03-18T14:56:21Z)
2016-03-18T14:56:22Z DEBUG - [atmos_uoe_zen_n48_noomp_4x4.1] -2016-03-18T14:56:21Z [(('event-handler-00', 'submission failed'), 1) cmd] rose suite-hook --mail 'submission failed' 'vn10.4_trunk' 'atmos_uoe_zen_n48_noomp_4x4.1' 'job submission failed'
2016-03-18T14:56:21Z [(('event-handler-00', 'submission failed'), 1) ret_code] 0
```

**Comment by matthewrmshin** [comment]
@dacreman Sorry for not getting back sooner. I am not sure how to fix this properly, giving that Torque is returning different string subsets at job submission and listing. I can suggest hacks or even implement logic to allow you to configure hacks more effectively, but neither solution is satisfactory.

**Comment by dacreman** [comment]
Thanks for looking into this. Changing the poll command to 'qstat -l' produces a string which matches the qsub output on some systems but not others. We'll just have work around this on systems where qstat -l doesn't work.

**Comment by matthewrmshin** [comment]
Hi @dacreman, I really cannot think of a satisfactory solution here, so I am closing this down as a won't fix for now. Please feel free to reopen if you think this is not satisfactory. Obviously, if I can think of a satisfactory solution, I'll reopen the issue.

**Comment by hjoliver** [comment]
@matthewrmshin and @dacreman - I'm not a torque user at the moment, so I haven't followed this in great detail.  Is this going to be a problem for all torque users, or is it version-specific, or some quirk of local implementation?   If not the latter, do we need to warn about it and suggest a workaround for those affected?

**Comment by dacreman** [comment]
@hjoliver I've seen a second Torque installation where the job ID returned by qsub is different to the job ID returned by qstat. However in this second case simply changing the poll command from 'qsub' to 'qsub -l' fixes the problem. There seems to be a version or implementation specific problem with our local set up (the first case mentioned in this thread) which means that 'qstat -l' isn't working correctly. To answer the original question I would expect other Torque users affected by this but they probably just need to change qstat to 'qstat -l'.
