### ISSUE TITLE
cylc gui: immortal R1 tasks: can hang obtaining graph edges

### ISSUE THREAD

**Issue by benfitzpatrick** [cylc/cylc#1773]
Suites with long-lasting R1 tasks (e.g. having "foo_cold[^] => foo" in each cycle point)
can generate a lot of spurious cycle points in the graphing.

Although we filter out useless cycles in the graph view (#1185, #1155), the daemon still
figures them out in the `get_graph_raw` call. For a large enough suite, with a large enough
number of cycles, this daemon computation time can be very significant.

**Comment by hjoliver** [comment]
[meeting]
   * document as a performance issue!
   * can we do anything to jump over the intermediate graph nodes / cycle points?

**Comment by matthewrmshin** [comment]
#2088 should have fixed the hanging bit, and documented the performance issue. The immortal/performance bit is really the same issue as #1392.
