### ISSUE TITLE
cylc gui: tree-view tasks not right-click-able after state change and filter

### ISSUE THREAD

**Issue by oliver-sanders** [cylc/cylc#1781]
If a user changes a task's state then enables a filter, all tasks belonging to the filter are un-right-clickable in tree-view providing that the view has not been updated.

Bug can be replicated by:
1. Holding a task
2. Waiting for the suite to come to a halt
3. Releasing the task
4. Enabling a filter
5. Right clicking on a task belonging to the filter which has just been enabled

If changing the state of the task results in any further changes to the view (e.g. task starts running) then the bug will not occur.

**Comment by hjoliver** [comment]
A simpler recipe to reveal this bug, for `graph = foo => bar => baz`
 * start gcylc on a stopped suite
 * set task filter for 'waiting' (i.e. to hide 'waiting' tasks)
 * start the suite running and immediately enable display of waiting tasks again: right-click menu will not pop up on the revealed waiting tasks until the running task finishes and changes state.
