### ISSUE TITLE
job scripts trap pipe problem

### ISSUE THREAD

**Issue by matthewrmshin** [cylc/cylc#1783]
Consider a task with a `script`:

```sh
echo "$GARBAGE" | tee 'whatever.txt'
```

The task will attempt to report both failure and succeeded. The 1st part of the pipe will fail with an unbound variable, which triggers the exit trap to send a failure message back to the suite. The 2nd part of the pipe will succeed and the script will some how continue to run before sending a succeeded message back to the suite.

This is a well known problem in bash, but we should probably document the problem in the cylc user guide?

**Comment by hjoliver** [comment]
This is an interesting one!   Did you actually see a case that triggered this?

**Comment by matthewrmshin** [comment]
Yes, it was reported by a user, and was very easy to repeat. (In the real case, `$GARBAGE` was a better-named variable, which the user has forgotten to define.)

(We have now asked the user to use the syntax `tee 'whatever.txt <<<"$GARBAGE"'` to avoid the problem, but it is not going to stop other users from doing something similar.)

**Comment by hjoliver** [comment]
(the pipe opens a subshell, inherits the traps; one subshell succeeds, one fails?!)
[meeting]
 * cannot trap errors in a pipe" - avoid using pipes in job scripts
 * Document and close
 * @hjoliver - document in FAQ

**Comment by matthewrmshin** [comment]
I have done some more digging. Apparently, we can do `set -o pipefail` (bash only) to force the whole command to return an error. Unfortunately, we'll still be calling the trap twice.

I think we should have `set -o pipefail` in a bash job script any way, and document it.
