### ISSUE TITLE
High CPU usage with queued tasks

### ISSUE THREAD

**Issue by MartinDix** [cylc/cylc#1787]
We still see high CPU usage in large suites when there are queued tasks, though the problem isn't as bad since the fix for #1744.

The 1744 fix stopped the state files being written every second, but in scheduler.py
```
                self.pool.match_dependencies()
```
is still getting called every second (if there are queued tasks) rather than just whenever the state changes. With a lot of waiting tasks this can be expensive.

Example cylc scan output from a large NWP ensemble suite (u-aa670)

```
Task state totals:
      queued:30 runahead:109 running:1 submitted:9 succeeded:479 waiting:249
      20150626T1800Z succeeded:9
      20150627T0000Z queued:30 running:1 submitted:7 succeeded:235 waiting:51
      20150627T0600Z succeeded:140 waiting:147
      20150627T1200Z submitted:2 succeeded:95 waiting:51
      20150627T1800Z runahead:105
      20150628T0000Z runahead:1
      20150628T0600Z runahead:3
```

When there are queued tasks CPU usage is about 30%, otherwise it's about 2%. Running a profiler shows that most of this is from ```prerequisite.satisfy_me``` which is called an enormous number of times.

**Comment by hjoliver** [comment]
Reproduced.  This is caused by the test for tasks that have become ready to run for external reasons - clock triggers or external triggers - even when there is no task activity in the suite (queued tasks are ready to run, by definition).

**Comment by MartinDix** [comment]
Thanks Hilary.

Testing suite in simulation mode shows the number of calls to match_dependencies has significantly decreased. The time spent has decreased dramatically compared to 6.9.1, perhaps due to #1769 as well.
