### ISSUE TITLE
Drop support for "detaching" tasks?

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc#1798]
Consider a model with a native front-end script that generates a secondary job script on the fly and submits that to a batch scheduler before immediately exiting.   As a normal cylc task, the model run will erroneously appear to finish immediately after the internal job is submitted.

So, if *[runtime][TASK]manual completion = True* we disable the automatic job completion scripting, write the entire suite-task messaging environment to a variable in the job file, which has to be inserted by the user, along with cylc task messaging calls, in the internal detached job. 

This dates back to my original attempts at handling pre-Rose UM job scripts, but I've long since concluded that it's always easier to modify the external script to foreground its internal detaching job submission than it is to successfully add the manual cylc task completion messaging.

If @cylc/core does not object, I'd like to remove this feature (some code, one config item, two example suites, and a User Guide section) and just insist that external jobs executed by cylc tasks must be non-detaching.

**Comment by matthewrmshin** [comment]
I agree. I cannot think of any use cases here that would require detaching tasks.
