### ISSUE TITLE
Extend the argument list supplied to task event handlers

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc#181]
Met Office uses get-config to extract task owner and host from the suite within a task event handler script. This can be problematic for large suites due to high memory usage by get-config (which has to parse the entire suite definition before reporting this information) - see Issue #170.  

Task event handlers should really be supplied with any information they might need to handle a task event, so the best solution to this problem might be just to add task owner and host to argument list passed to event handlers.

Before doing that, can we anticipate any other task-related information that might be useful to task event handlers?  Or perhaps a way of passing said information that won't break existing event handlers in the future if we add more items to the command line used to invoke them.  Currently a general message is the last thing on the command line, because it may contain spaces and therefore result in an indefinite number of arguments ... but I think we could just ensure that all arguments are quoted, and event handlers should not test for a specific number of arguments and should ignore additional arguments that they don't need.

**Comment by matthewrmshin** [comment]
Once #992 is done, the requirement for this will diminish at our site.
