### ISSUE TITLE
Can active tasks be "reloaded" immediately?

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc#1818]
It can be confusing to users when a reload takes a long time due to presence of active tasks in the suite, which aren't reloaded until they finish.

Offhand, I don't recall the reason for this - what settings could be changed in a reload that would somehow be incompatible with an already-submitted task?   We should see if it's possible to handle such edge cases, if any, and reload all task definitions immediately.

**Comment by benfitzpatrick** [comment]
I thought that it was just a way of indicating to users that their active tasks were still running with old settings. I always click the progress bar off myself - I agree it gets a bit annoying in this case.

**Comment by arjclark** [comment]
> a way of indicating to users that their active tasks were still running with old settings

Likewise. There's been a few queries about it but the explanation for why the progress bar's still there seems to make sense to people.

**Comment by hjoliver** [comment]
@arjclark and @benfitzpatrick - your explanation makes good sense, but it's a bit more than that: the runtime of an active task is actually not reloaded until the task finishes.   As I recall, when I originally implemented suite reload I was concerned that a reloaded task proxy could potentially be incompatible with the already-running task.  Wracking my brains for why exactly, I can think of two scenarios:
 1. a detaching tasks could become non-detaching (or vice versa) - no longer relevant due to #1807 
 2. task message outputs could be changed to be different than the running task expects

**Comment by hjoliver** [comment]
PR #1835 handles changed outputs too, without delayed reload.
