### ISSUE TITLE
cylc gscan: configurable default settings

### ISSUE THREAD

**Issue by kaday** [cylc/cylc#1830]
It would be great to have a way to set the defaults for gscan` like we do for `gcylc`.

Would this be best as a file like `gcylc.rc`? @hjoliver what do you think?

@oliver-sanders are you interested in this issue?

**Comment by hjoliver** [comment]
Yes, this would be useful.   For historical reasons it should be a `gscan.rc` file (although in future we might want to consider moving all non suite-specific site/user configuration into a single configuration file!)

**Comment by benfitzpatrick** [comment]
Also see #1834 for an example of a user-requested configuration.
