### ISSUE TITLE
scan hangs during suite start-up (rebuilding the suitedb)

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc#1842]
We rebuild the public suite DB at suite restart, from the private DB.  During the DB rebuild, `cylc scan` hangs until it times out.  In a suite with quite a large DB (84MB) one our servers this can take many minutes.

We can presumably avoid this problem by doing the DB rebuild before connecting the suite to the network (and before daemonization, so it is clear what's happening - see also #1721).

**Comment by hjoliver** [comment]
See also https://github.com/cylc/cylc/issues/1159#issuecomment-2187176630 (DB housekeeping)

**Comment by matthewrmshin** [comment]
Is it `vacuum` of the private database that is taking its time? The private to public re-sync is a simple file copy, and should not take minutes for only 84MB of data.

**Comment by hjoliver** [comment]
It probably was `vacuum` of the private DB.

**Comment by hjoliver** [comment]
I'm not sure if there was a load issue on the machine at the time.  Does minutes sound excessive for vacuuming a ~100MB db?

**Comment by matthewrmshin** [comment]
I would imagine that it should take seconds. I have just done a few tests here on a few 100+MB database files. They all take <10s on local or NFS mounted file systems.

**Comment by hjoliver** [comment]
Hmmm.  In that case I suspect a GPFS problem, or perhaps just massive I/O overload, slowing down our systems at the time (our Linux servers see the same filesystem as the supercomputer).  It's been known to happen.  I'll do some tests myself tomorrow though...

**Comment by matthewrmshin** [comment]
(However, I think it is still worth moving the vacuum logic + copy logic to an earlier part of the restart process, as suggested, but it may be as chicken-and-egg as the problem of #1721, which I am still trying to find a solution.)

**Comment by hjoliver** [comment]
I tested DB vacuuming on the same suite server today.  It doesn't take as long as I thought yesterday, but is certainly too long to be acceptable in terms of its current effect on "cylc scan" (for all users):

```
$ ls -lh
total 165M -rw-r--r-- 1 oliverh unix-users 165M May 17 01:07 cylc-suite.db

$ time sqlite3 cylc-suite.db "VACUUM;"

real  1m38.464s
user   0m3.168s
sys    0m9.590s
```

**Comment by matthewrmshin** [comment]
I'll have a look at what's possible here, (perhaps in combination of a localised re-factor I am aiming to do for `bin/cylc-run`, `bin/cylc-restart`, `lib/cylc/run.py` and `lib/cylc/scheduler.py`). I think it should be relatively easy to move the logic higher up in the restart process.

**Comment by hjoliver** [comment]
OK, thanks - assigning to you

**Comment by matthewrmshin** [comment]
(Do we also need some time out for scan? E.g. If a port does not respond, move on?)
