### ISSUE TITLE
cylc commands in task environments can't target other suites

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc#1843]
If a task in suite X tries to execute `cylc stop Y` (for example) the stop client will load the passphrase for its parent suite `X`, not the target suite `Y`.

**Comment by hjoliver** [comment]
And/or (I need to check) at the point that the suite environment file for `X` is loaded by the task, it will complain that the suite names `X` and `Y` don't match.  The final result is the `stop` command is denied access by the target suite.

**Comment by matthewrmshin** [comment]
This should be relatively straightforward. We can probably check that `CYLC_SUITE_NAME` is the same as the requested suite name to determine whether we can load the passphrase file from locations such `CYLC_SUITE_RUN_DIR` or not.
