### ISSUE TITLE
cylc run --hold: prereqs caching breaks pre-initial dependencies

### ISSUE THREAD

**Issue by benfitzpatrick** [cylc/cylc#1857]
When this suite is run with `--hold`, then released, `foo` will be stuck in the waiting state:
```ini
[scheduling]
    initial cycle point = 2016-01-01
    final cycle point = 2016-01-02
    [[dependencies]]
        [[[PT6H]]]
            graph = "foo[-PT6H] => foo"
```

**Comment by arjclark** [comment]
Bit odd as the pre-initial dependencies part of the code should only be removing irrelevant pre-reqs so shouldn't be of relevance once they've been generated on task proxy creation.

**Comment by benfitzpatrick** [comment]
Looks like the change in behaviour came with the new handling of `release_suite` (reset to waiting) in 78166a2/#1775.

**Comment by benfitzpatrick** [comment]
And on further investigation, it's any 'reset to waiting'/'set prereqs unsatisfied' for pre-initial dep tasks, so it's actually my own prereq caching.

This fixes it, although to be honest I'd be tempted to just delete the `all_satisfied' attribute instead - that would fix it just as well.

```diff
diff --git a/lib/cylc/prerequisite.py b/lib/cylc/prerequisite.py
index e0eec8c..0732e42 100755
--- a/lib/cylc/prerequisite.py
+++ b/lib/cylc/prerequisite.py
@@ -211,7 +211,9 @@ class Prerequisite(object):
     def set_not_satisfied(self):
         for label in self.messages:
             self.satisfied[label] = False
-        if self.conditional_expression is None:
+        if not self.satisfied:
+            self.all_satisfied = True
+        elif self.conditional_expression is None:
             self.all_satisfied = False
         else:
             self.all_satisfied = self._conditional_is_satisfied()
```

**Comment by matthewrmshin** [comment]
(Note: I have come up with a different fix, as I cannot see why we need to reset anything other than the status string when a task is released.)

**Comment by hjoliver** [comment]
BTW, yesterday a user here showed me a waiting task that was not submitting even though all its prerequisites (a non-zero number of them) were reported as satisfied.  This suggests it is possible for the caching to incorrectly report `all_satisfied` as `False`  in other circumstances too.  Unfortunately it was a large complex suite and it was being actively messed about with - including restarts and reloads - at the time, and I wasn't able to reproduce the problem.   But we should have a good look at the code...

**Comment by hjoliver** [comment]
(I can't see how this can happen though!)

**Comment by hjoliver** [comment]
Reproduced:
```
[scheduling]
    initial cycle point = 2015
    final cycle point = 2015
    [[dependencies]]
        [[[P1D]]]
            graph = """foo => bar
                bar[-P1D] => bar"""
[runtime]
    [[root]]
        script = sleep 5
  ```
Hold the suite while the first `foo` is running, then release it (while `foo` is still running, or after it succeeds) and `bar` will be stuck `waiting` with its one prerequisite satisfied.

Which I guess makes this another symptom of the same problem.  Matt's PR does fix it.

Interestingly, it doesn't happen for `graph = foo & bar[-P1D] => bar`, which should be equivalent.

**Comment by hjoliver** [comment]
> Interestingly, it doesn't happen for graph = foo & bar[-P1D] => bar, which should be equivalent.

I guess this form is treated differently because it's a conditional prerequisite.

**Comment by hjoliver** [comment]
(this is arguably another unfortunate side effect of technically unnecessary pre-initial filtering #1544)

**Comment by arjclark** [comment]
> (this is arguably another unfortunate side effect of technically unnecessary pre-initial filtering #1544)

@hjoliver - I thought you might say that :grin:

I'll take a look later and see if there's anything that can be done to get a pre-req filtered task to be equivalent to a non pre-req filtered task i.e. the prereqs for:
```
graph = foo
```
shoud be equivalent to those produced by:
```
graph = foo[-P1D] => foo
```
the only difference I could see yesterday digging around was that in the first case it had no prerequisites leftover whereas in the second it has prereqs of [None] (which are handled in the code but I think in this case flagged up the problem introduced above and which you saw with your user)

I suspect the difference between:

```
            graph = """foo => bar
                bar[-P1D] => bar"""
```
and 
```
graph = foo & bar[-P1D] => bar
```
is down to how they're read in by cylc and subsequently filtered.

I *think* for the former you end up with it evaluating ```foo => bar``` and ```bar[-P1D] => bar``` as separate dependencies so end up with prereqs of:
```
[foo, None]
```
whereas in the second case it comes in as a single conditional statement so you get:
```
[foo]
```
as the ```bar[-P1D]``` element is filtered out and doesn't result in a null prerequisite.

**Comment by hjoliver** [comment]
> @hjoliver - I thought you might say that :grin:

Who, me? :innocent:
