### ISSUE TITLE
Default global.rc file gives validation error

### ISSUE THREAD

**Issue by trwhitcomb** [cylc/cylc#1865]
I got a new workstation, so I'm setting it up with the latest cylc version (6.10.1-37-g2c9bb), and I'm now getting validation errors with the global.rc file.  I cleared out the old and ran:

`cylc get-site-config > $HOME/.cylc/global.rc`

to generate the new configuration file.  Then, I tried validating a suite and got:

```
[whitcomb@whitcomb-dev ~]$ cylc validate -v /ftp/receive/whitcomb/suite.rc
Loading site/user config files
Reading file /users/whitcomb/.cylc/global.rc
WARNING: ignoring bad site config /users/whitcomb/.cylc/global.rc:
Illegal ISO 8601 interval value: [task events][execution timeout]
```
it's also not suite-specific:
```
[whitcomb@whitcomb-dev ~]$ cylc version
WARNING: ignoring bad site config /users/whitcomb/.cylc/global.rc:
Illegal ISO 8601 interval value: [task events][execution timeout]
6.10.1-37-g2c9bb
```

If I look at the file, it shows that execution timeout entry as blank.  I haven't changed anything, but it appears that the validation code is looking for something that's not present in the internal configuration.

Expected result is to not get a bad site config by using the software's method to dump the current configuration from scratch - the actual result is a validation error with a pristine `global.rc` file.

**Comment by hjoliver** [comment]
Reproduced. Thanks for the report.

**Comment by hjoliver** [comment]
This goes back to the 6.6.0 release.  Most users just set the site config items they need, rather than start from a file full of default values.  However, that certainly should be possible; we'd better add a test for it.
