### ISSUE TITLE
Document batch system command requirements.

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc#1879]
With reference to #1767 - we should mention in the "Task Job Submission" section (which also documents job poll and kill) that the batch system job queue interrogation command must return the same job ID string as the job submit command, what the consequences are if it doesn't, and what to do about it, e.g. you may need to use `qstat -l` with torque.

**Comment by matthewrmshin** [comment]
I think we are better off solving #1413.

**Comment by hjoliver** [comment]
That issue was raised a whole year ago.  We can still document the limitations/requirements of the current system, pending the full solution.

**Comment by matthewrmshin** [comment]
Hear hear. I have taken a quick look at the logic just now, and I think it is quite easy to implement a good solution for #1413. I'll get on with it as one of my next things to do.
