### ISSUE TITLE
queues: priority for some members

### ISSUE THREAD

**Issue by benfitzpatrick** [cylc/cylc#1882]
It might be nice to have extra syntax to allow prioritisation of some families or tasks within a queue.

Something like:
```ini
[scheduling]
    [[queues]]
        limit = 5
        members = FOO, BARBAZ
        priorities = BARBAZ, FOO
```

You can arguably achieve a similar thing with multiple queues, but it isn't quite as flexible. It should just be a slight sorting change in task_pool.

One more step on the road to making cylc a scheduler!

**Comment by matthewrmshin** [comment]
This appears to be a duplicate of #1196.

**Comment by benfitzpatrick** [comment]
Hah, great.
