### ISSUE TITLE
Suite timer should start after stall, not lack of activity.

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc#1897]
This is feasible now that we have automatic stall detection.  The current behaviour can kill suites that simply have jobs stuck in the batch scheduler queue for a long time.

While doing this, check that holding a suite doesn't disable the timer.

**Comment by arjclark** [comment]
I have this pretty much done (trivial change to existing code). However, it occurs to me that relying on stalled detection will mean that if a task gets stuck in a running state then the suite timeout handler will never get started as at that point the suite is considered running. @hjoliver - thoughts on how you think that should be handled?

**Comment by hjoliver** [comment]
(This discussion continued on the pull request #1897)

**Comment by arjclark** [comment]
Closed by #1945
