### ISSUE TITLE
cylc 5 syntax deprecation

### ISSUE THREAD

**Issue by benfitzpatrick** [cylc/cylc#1907]
We should deprecate cylc 5 cycling syntax, and produce warnings for it on cylc validate. We should do the same for some of the other syntax that has changed since cylc 6.0 where we think it's appropriate.

(Eventually we should fail validation in strict mode, then remove support entirely.)

**Comment by matthewrmshin** [comment]
I would be tempted to remove support for all pre-cylc-6 stuffs (and/or maybe pre-cylc-6.4 stuffs) in the `global.rc` and `suite.rc`. See:
* [cylc.cfgspec.globalcfg.upg](https://github.com/cylc/cylc/blob/master/lib/cylc/cfgspec/globalcfg.py#L290)
* [cylc.cfgspec.suite.upg](https://github.com/cylc/cylc/blob/master/lib/cylc/cfgspec/suite.py#L430)

We should probably remove CLI compatibility usage at some point, e.g. old syntax for multi-task usage.

**Comment by benfitzpatrick** [comment]
Closed by #1964.
