### ISSUE TITLE
Cylc/SLURM

### ISSUE THREAD

**Issue by miiorga** [cylc/cylc#1926]
Sorry for duplicate question..I am still confused reading tickets that is related to my problem. Would anyone mind throwing some light? 
I want to use cylc to run a model developed by UK met office. Have installed cylc but we don't have pygtk on the cluster. Is pygtk essential for the functioning of Cylc? because the IT officer said we don't have either on the cluster the graphical libraries that is required by pygtk. 
Another question is that we have SLURM as a job scheduler on the cluster, will it be compatible with Cylc?
Thanks!

**Comment by matthewrmshin** [comment]
In general, please use [cylc Google Group](https://groups.google.com/forum/?fromgroups#!forum/cylc) for usage question.

To answer your question:
* You only need pygtk if you can and want to use the GUIs.
* Cylc has built-in support for submitting jobs to SLURM.

**Comment by matthewrmshin** [comment]
See also [cylc support](https://cylc.github.io/cylc/support.html).

**Comment by hjoliver** [comment]
@miiorga - note a typical mode of operation is: run cylc on a Linux server (with GUI support) and have your suites submit jobs to the compute cluster (which may not have GUI support).

**Comment by miiorga** [comment]
Thanks guys!
