### ISSUE TITLE
Proposal for built-in (non-Jinja2) parameterized tasks.

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc#1937]
Consider a simple workflow like this:
```
prep => init => sim => post => done
```

Now consider that we want replicate this for two different model "members" (using ensemble forecasting terminology), combine their results in some way, and then replicate the whole two-model experiment for two distinct "runs" (which differ in some other way, e.g. start date), like this:
![auto1](https://cloud.githubusercontent.com/assets/2362137/16859265/1d66781e-4a1d-11e6-8ed8-24f28caf1c9e.png)

Currently we can generate this by parameterizing the task names with Jinja2 loop indices.  I will also put all post tasks in a POST family (as they'll likely share a lot of configuration), all sim tasks in a SIM family, and so on.  This works perfectly well, but it is hard to discern the suite structure by inspection!
```
#!Jinja2
{% set N_RUNS = 2 %}
{% set N_MEMS = 2 %}

[scheduling]
    [[dependencies]]
        graph = """
{% for R in range(0, N_RUNS) %}
        prep => r{{R}}_init
    {% for M in range(0, N_MEMS) %}
        r{{R}}_init => r{{R}}_m{{M}}_sim => r{{R}}_m{{M}}_post
        r{{R}}_m{{M}}_post => r{{R}}_comb
    {% endfor %}
        r{{R}}_comb => done
{% endfor %}
            """
[runtime]
    [[prep]]
    [[done]]
    [[INIT]]
    [[SIM]]
    [[POST]]
    [[COMB]]
{% for R in range(0, N_RUNS) %}
    [[r{{R}}_init]]
        inherit = INIT
    [[r{{R}}_comb]]
        inherit = COMB
    {% for M in range(0, N_MEMS) %}
    [[r{{R}}_m{{M}}_sim]]
        inherit = SIM
    [[r{{R}}_m{{M}}_post]]
        inherit = POST
    {% endfor %}
{% endfor %}
```

The collapsed family graph is simple and clear, but we can't write the graph like this in the suite definition because we don't have member-to-member family triggering semantics:
![auto2](https://cloud.githubusercontent.com/assets/2362137/16859460/8f735124-4a1e-11e6-895e-5c010e1d3429.png)

## step 1: family member-to-member triggering semantics

By merely extending our graph parsing to substitute (non "-all" or "-any") family triggers with member-to-member triggers, we could write the suite like this:
```
#!Jinja2
{% set N_RUNS = 2 %}
{% set N_MEMS = 2 %}

[scheduling]
    [[dependencies]]
        graph = prep => INIT => SIM => POST => COMB => done

[runtime]
    [[prep]]
    [[done]]
    [[INIT]]
    [[SIM]]
    [[POST]]
    [[COMB]]
{% for R in range(0, N_RUNS) %}
    [[r{{R}}_init]]
        inherit = INIT
    [[r{{R}}_comb]]
        inherit = COMB
    {% for M in range(0, N_MEMS) %}
    [[r{{R}}_m{{M}}_sim]]
        inherit = SIM
    [[r{{R}}_m{{M}}_post]]
        inherit = POST
    {% endfor %}
{% endfor %}
```
Member-to-member semantics is uniquely determined so long as the members have common indices.  So `FOO => BAR` means:
 ```
foo_m1 => bar_m1
foo_m2 => bar_m2
```
or for different member numbers:
```
foo_m1 => bar_m1_a1 & bar_m1_a2  # (m1-to-m1)
foo_m2 => bar_m2_a1 & bar_m2_a2  # (m2-to-m2)
```

## step 2: built-in generation of the task definitions

Step 1 restores clarity of suite structure, but we can also get rid of the Jinja2 loops under [runtime] and have cylc internals (at parse time) do the expansion, something like this:
```
[scheduling]
    [[dependencies]]
        graph = prep => INIT => SIM => POST => COMB => done
[runtime]
    R = 2
    M = 2
    [[prep]]
    [[done]]
    [[INIT<R>]]
    [[SIM<R,M>]]
    [[POST<R,M>]]
    [[COMB<R>]]
```

__Note that this allows chunking__ (c.f. two other known "job submission tools!) __aka statically defined date-time-labelled tasks in a non-cycling suite__ (or in each cycle of a cycling suite): to break the model and post-processing tasks up into shorter runs ("chunks") just add another index:
```
[runtime]
   C = 5
   [[SIM<R,M,C>]]
   [[POST<R,M,C>]]
```
(We can also do this already with Jinja2 loops, of course, but it makes the graph definition even messier).  The generated tasks will be passed their indices, and multiplying the chunk index by a designated chunk interval will give the chunk start date. (Or we could optionally treat the chunk index differently, and use it define a dynamic date-time cycling suite).

**Comment by hjoliver** [comment]
(just to note we'd also need a minor syntax extension to define inter-chunk dependence akin to inter-cycle dependence in a cycling suite, e.g. `SIM<C-1> => SIM`)

**Comment by matthewrmshin** [comment]
Very nice proposal.

**Comment by benfitzpatrick** [comment]
Yep, nice. We could do with the various indices being made available as environment variables for users to use - e.g. input parameters and output paths for the individual members.

**Comment by hjoliver** [comment]
@cylc/core  - I took a look at implementing this and decided the current graph string parsing code has become unwieldy and difficult to extend, so I rethought it from scratch and coded a new class to parse  each graph string in turn as straightforwardly as possible, expanding families and (the new) parameters, and extracting and storing all the dependency information for each task in each graph section.  As well as existing functionality it handles the new parameterization (including "inter-chunk dependence") plus another new feature: member-to-member semantics for non-parameterized same-size same-sorting families (e.g.  `OBS_GET => OBS_PROC` for  `obs_get_aircraft => obs_proc_aircraft` and `obs_get_sonde => obs_proc_sonde` etc).   However, I have yet to actually interface this to `config.py` (standalone tested so far).  Hopefully that won't be difficult and I'll raise a pull request soon (note I expect to be tied up with admin work for the next few days though).
