### ISSUE TITLE
newly flaky test: pre-initial/10-warm-insert.t

### ISSUE THREAD

**Issue by matthewrmshin** [cylc/cylc#1938]
Test fails when system is loaded. Symptom is that the inserted 12Z tasks are stuck apparently waiting for the 06Z tasks before the suite times out.

**Comment by hjoliver** [comment]
Agreed, this is flaky.  It's the only one failed on Travis CI after the lastest PR merge.

**Comment by hjoliver** [comment]
>  inserted 12Z tasks are stuck apparently waiting for the 06Z tasks before the suite times out.

Odd. The stalled handler is supposed to reset the first of the 12Z tasks to get them going.

**Comment by hjoliver** [comment]
I'm also getting some cases where `pre-initial/11-warm-start-stall.t` hangs for ever.  This one uses `abort on stalled` to shut down.  `pre-initial/10-warm-start.t` uses a `stalled handler` to reset task states.   

This suggests there is some circumstance in which our suite stalled detection isn't working.  Any ideas @arjclark?

**Comment by arjclark** [comment]
No ideas I'm afraid. I've only recently seen this happen, a number of merges after the original pull request went in...

**Comment by hjoliver** [comment]
Yeah, we might have broken it with subsequent changes, I'll investigate further...

**Comment by arjclark** [comment]
N.B. I can't account for what others have seen as @matthewrmshin had said he'd been seeing it for a while, whereas I only started to see it reviewing one of his recent changes.

**Comment by hjoliver** [comment]
This gets weirder.  Yesterday (while the network was down) `11-warm-insert-stall.t` failed every time I ran it.  Today, it passes every time.

**Comment by arjclark** [comment]
@matthewrmshin seemed to indicate that it was dependent on machine load at time of running the test (again not really experiencing the problem so can't comment) but maybe that played a factor here?

**Comment by matthewrmshin** [comment]
`pre-initial/10-warm-insert.t` is no longer flaky for me. @hjoliver Is it still flaky at yours?
`pre-initial/11-warm-insert-stall.t` is being fixed by #1969.

**Comment by hjoliver** [comment]
Bad news, the latest Travis CI build (after merging #1969) was killed with `pre-initial/10-warm-insert.t` stalled indefinitely https://travis-ci.org/cylc/cylc/builds/154564973#L829

**Comment by matthewrmshin** [comment]
(The symptom is that the task was inserted in too late or something, so it hangs waiting for its dependency on an already removed task to be satisfied.)

**Comment by arjclark** [comment]
If the latest pull request still doesn't fix things I have two remaining ideas...
