### ISSUE TITLE
Stalled warning when a task is in 'retrying' state.

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc#1941]
This suite reports a stalled warning every time foo goes into the 'retrying' state.
```
[scheduling]
    [[dependencies]]
        graph = foo => bar
[runtime]
    [[foo]]
        script = sleep 10; /bin/false
        retry delays = 2*PT10S
```
@arjclark - with reference to the issue description in PR #1848, should we add `retrying` to the list of states that indicate a suite is not stalled?

**Comment by arjclark** [comment]
Agreed, pull request raised.
