### ISSUE TITLE
Unhelpful "self-suicide" warnings

### ISSUE THREAD

**Issue by arjclark** [cylc/cylc#1946]
We've noticed that since cylc 6.5.0 (#1482) we're getting lots of self suicide warnings out of validation even when a task isn't solely suicide triggered by itself. For example:
```
    [[dependencies]]
        graph = """
                    foo => bar => baz
                    foo:fail => qux => baz
                    foo:fail & baz => !foo
                """
```
will throw out:
```
WARNING: self-suicide is not recommended: foo:fail => !foo.
```
As the warning is unhelpful and (potentially) prolific in larger suites it's probably just easiest to remove it.

**Comment by hjoliver** [comment]
Yeah, that's fine with me.
