### ISSUE TITLE
GUI right-click menu item selection

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc#1956]
Currently we activate right-click menu with mouse button three, and select an item with button one.  If you try to select with button three, the menu will disappear and nothing will happen.  This still confuses some users.  Playing around with other GUI applications it seems to me that standard behaviour is to allow selection with either one or three, or else do nothing (but menu stays activated) on button three.

**Comment by matthewrmshin** [comment]
Hi @hjoliver I hope you don't mind me taking this one from you.

**Comment by hjoliver** [comment]
@matthewrmshin - thanks, I don't mind at all!
