### ISSUE TITLE
Advanced exclusion graphing syntax

### ISSUE THREAD

**Issue by oliver-sanders** [cylc/cylc#1960]
Follow on from #1928, possible improvements to existing exclusion syntax:
- Recursion exclusion `[[[ P3D!P9D ]]]`
- Multiple point exclusion `[[[ T00 ! (20000101T00, 20100101T00, ...) ]]]`

**Comment by oliver-sanders** [comment]
The syntax for excluding datetimes using the `!` symbol was introduced to solve the `T00` after the ICP problem #1353 (`[[[ T00!^ ]]]`). It could be expanded to become more powerful. My thoughts thus far:

- Potentially useful
- Could reduce the need for suicide triggers?
- Can simplify some graph section headings
  - e.g. `[[[ T-00 ! PT6H ]]]`
- Could result in overly complex / hard to read graph section headings
  - e.g. `[[[ R/^/P1H ! (R/$-P2D/P2H, R4/^/P6H, 20120101T00) ]]]`

#### 1) Datetime exclusion _(implemented)_:
- `[[[ R/^/PT1H ! 20120101T00 ]]]`

#### 2) Multiple datetime exclusion _(trivial)_:
- `[[[ T00 ! (20000101T00, 20100101T00, ...) ]]]`

#### 3) Partial datetime (datetime recurrence) exclusion:
- `[[[ PT1H ! T12 ]]]` _Run hourly but not at 12:00 (from the ICP)_
- `[[[ T-00 ! (T00, T06, T12, T18) ]]]` _Run hourly but not at 00:00, 06:00, 12:00, 18:00_
- `[[[ PT5M ! T-15 ]]]` _Run 5 minutely but not at 15 minutes past the hour (from the ICP)_
- `[[[ T00 ! W-1T00 ]]]` _Run daily at 00:00 except on Mondays_

#### 4) Sequences exclusion:
- `[[[ PT1H ! PT6H ]]]` _Run hourly (from the ICP) but not 6 hourly (from the ICP)_
- `[[[ T-00 ! PT6H ]]]` _Run hourly on the hour but not 6 hourly on the hour_
  - Same as `[[[ T-00 ! T-00/PT6H ]]]` _(the `T-00` context is implied for the excluded sequence)_
  - Same as `[[[ T-00 ! (T00, T06, T12, T18) ]]]`
  - Same as `[[[ PT1H ! (T00, T06, T12, T18) ]]]` _(ICP Dependent)_
- `[[[ T12 ! T12/P15D ]]]` _Run daily at 12:00 except every 15th day_
- The exclusion(s) could be any valid recurrence _(would we want to do this?)_
  - e.g. `[[[ R/^/P1H ! R5/20000101T00/P1D ]]]`

@cylc/core Any thoughts?

**Comment by arjclark** [comment]
As discussed, I have a usecase basically ready and waiting for something like this:  
`[[[ T-00 ! (T00, T06, T12, T18) ]]]` Run hourly but not at 00:00, 06:00, 12:00, 18:00

**Comment by hjoliver** [comment]
Closed by #2258 (@dvalters - reopen if I'm wrong)

**Comment by dvalters** [comment]
@hjoliver yep - sorry, forgot to close this!
