### ISSUE TITLE
New command to find suite PIDs

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc#1967]
Currently we print suite PID and a command for finding it, at start-up, e.g.:

```
ssh niwa-34403.niwa.local "pgrep -a -P 1 -fu $USER 'cylc-r.* \bfoo\b'"
```

Users are unlikely to remember this when they need it; we should wrap it in a simple command (`cylc get-suite-pid`?).

**Comment by matthewrmshin** [comment]
With #2067, the suite PID will be printed in the 1st line of the suite log. It will also appear in the suite contact file while the suite is running. (Do we just need a command to display the content of the contact file? Or is that even necessary?)

**Comment by hjoliver** [comment]
The intention here was just to make it easy for users to find the suite PID in rare occasions when they need to kill processes manually.  IMO many users have little awareness of the suite log, and none of the contact file.  However, printing the content of the contact file would be sufficient, I guess.
