### ISSUE TITLE
Don't abort on port file missing if --port is used.

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc#1968]
The `--port` option can be used to target suites (found with `cylc scan`) if the port file is wrong (e.g. multiple instances of the same suite started accidentally).  At the moment it doesn't work if the port file is actually missing, because commands check for that and abort.

**Comment by hjoliver** [comment]
Works as intended if both `--host` and `--port` are used.

**Comment by hjoliver** [comment]
I guess the logic should be:
 * if --port and --host are used, we don't need to look for the port file
 * if only --port is used,
   * if a port file exists, get host from it
   * if no port file exists, assume localhost <------- this bit is missing
 * if only --host is used,
   * the port file must exist on the host, to get the port number.

**Comment by matthewrmshin** [comment]
Dumping brain:
* Should we support a `--host=HOST[:PORT]` syntax?
* Should the running suite check for its port file regularly - re-creating if it has been deleted accidentally?

**Comment by matthewrmshin** [comment]
Alternatively, should a running suite shuts itself down if it finds its port file missing or contains the wrong information?
