### ISSUE TITLE
'running to stop at [cycle point]' not updating 

### ISSUE THREAD

**Issue by jonnyhtw** [cylc/cylc#1997]
Hi

A very minor issue here so feel free to kick into the long grass :) ...

I've noticed a few times that the _running to stop at [cycle point]_ info at the bottom left corner of my GCylc window doesn't update when using `rose suite-run --reload`.

In the attached pic, you can see that the currently running task is significantly later than the _running to stop at ..._ point.

Like I said, this is not a pressing issue but I thought it worth mentioning.

Cheers

Jonny

![snap](https://cloud.githubusercontent.com/assets/12940715/18502093/14b4a486-7aa9-11e6-9b99-b1c896332ba9.png)

**Comment by matthewrmshin** [comment]
@jonnyhtw I suppose you are modifying the *final cycle point* in your reload? Is this a problem specific to `rose suite-run --reload` (I can't see why) or do you see the problem using `cylc reload`?

Note: I am unable to repeat your problem in a simple case I have set up, using either cylc 6.10.2 or HEAD of master. Could you please provide more detail on how to repeat?

**Comment by jonnyhtw** [comment]
Thanks @matthewrmshin 

The problem is related to `rose suite-run --reload` not `cylc reload` since I have never used the latter directly.

The only thing that I modified in this example was the `RUNLEN` variable in the rose-suite.conf file in my suite.

I'll try and put together an example for you.

Thanks

Jonny

**Comment by jonnyhtw** [comment]
Hi there

I have (informally) tested this in several different configurations of Rose/Cylc and this issue seems to have gone away. I am closing this issue but will reopen it if it reappears.

Thanks

Jonny
