### ISSUE TITLE
cylc 5 syntax obsoletion

### ISSUE THREAD

**Issue by benfitzpatrick** [cylc/cylc#2001]
Following on from #1907, we should obsolete cylc 5 syntax at cylc 7.

**Comment by benfitzpatrick** [comment]
I'm going to put something up for this tomorrow. There are a couple of decisions I'd like to discuss with @cylc/core where obsoletion is not black and white - e.g. `initial cycle time`, `cylc broadcast -t`.

**Comment by arjclark** [comment]
Taking over this issue.
