### ISSUE TITLE
Handling of "can't start new thread" errors.

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc#2009]
A NIWA user running many large suites at once (including many tasks running on the suite host) got occasional hung suites that had to be hard-killed and restarted.  By hung, I mean non-responsive to user commands (but still showing state summary to the GUI) **and** causing `cylc scan` (and therefore the `gcylc` Switch Suite dialog to lock up until the Pyro timeout (which is too long by default).

With `cylc scan --pyro-timeout=5`:

```
suite? owner?@localhost:7771 - connection timed out (connection timeout receiving)
```

Then identify the hung suite by finding 7771 in users port files.  Suite err log shows:

```
$ cat ~andrewsp/cylc-run/NZLAM_GA6_vg36/log/suite/err
WARNING: message trigger offsets are deprecated
  command scripting started at []
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib64/python2.6/threading.py", line 532, in __bootstrap_inner
    self.run()
  File "/gpfs_oper/filesets/oper/admin/um_fcm/cylc/cylc-6.10.2/lib/cylc/scheduler.py", line
    self.pyro.handle_requests(timeout=1)
  File "/gpfs_oper/filesets/oper/admin/um_fcm/cylc/cylc-6.10.2/lib/cylc/network/pyro_daemon
    self.daemon.handleRequests(timeout)
  File "/gpfs_oper/filesets/oper/admin/um_fcm/cylc/cylc-6.10.2/lib/Pyro/protocol.py", line
    self._handleRequest_Threaded(timeout,others,callback)
  File "/gpfs_oper/filesets/oper/admin/um_fcm/cylc/cylc-6.10.2/lib/Pyro/protocol.py", line
    thread.start()
  File "/usr/lib64/python2.6/threading.py", line 474, in start
    _start_new_thread(self.__bootstrap, ())
error: can't start new thread  # <---------------- !!!!!!!
```

**Comment by hjoliver** [comment]
Note the new thread was requested by the Pyro comms library, which has been replaced by HTTPS on current master.  So, I need to attempt to reproduce this problem (can I set the thread limit low? or start a program that creates a large number of threads...) under current cylc, to see what happens...

**Comment by matthewrmshin** [comment]
Port scan should no longer hang since #2060. If the suite dies gracefully on this sort of error, we should be fine.

**Comment by matthewrmshin** [comment]
Still an issue?

**Comment by hjoliver** [comment]
Closing - no longer an issue as far as I can tell.

**Comment by hjoliver** [comment]
(for the record, a hung port - back at cylc-6.11 at least - can evidently be caused by a user forcibly starting two instances of the same suite so that both daemons try to write to the same directory)
