### ISSUE TITLE
occasional error from gcylc log view of running task

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc#2012]
I've seen this several times, but unable to reproduce consistently (and I'm short on time right now...):

Right-click running task, "view stdout", then:
```
Traceback (most recent call last):
  File "/gpfs_oper/filesets/oper/admin/um_fcm/cylc/cylc-6.11.1/lib/cylc/gui/app_gcylc.py", line 1214, in view_task_info
    self._popup_logview(task_id, task_state_summary, choice)
  File "/gpfs_oper/filesets/oper/admin/um_fcm/cylc/cylc-6.11.1/lib/cylc/gui/app_gcylc.py", line 2233, in _popup_logview
    if '@' in job_user_at_host:
TypeError: argument of type 'NoneType' is not iterable
```

**Comment by oliver-sanders** [comment]
To replicate run and stop a suite, then restart it in the cylc gui. Tasks which complete post-restart will have this issue.

**Comment by matthewrmshin** [comment]
OK. Repeatable on tasks that are in the waiting state on restart. On viewing their outputs when they have started up, we'll get the traceback.

**Comment by matthewrmshin** [comment]
@oliver-sanders #2015 and #2016 should now fix the case reported by you.

**Comment by oliver-sanders** [comment]
@matthewrmshin Can confirm #2015, #2016 do fix this for me.
