### ISSUE TITLE
"view prerequisites" fails for tasks in the runahead pool

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc#2045]
(the method is presumably assuming all tasks are in the main pool - easy to fix).

![foo](https://cloud.githubusercontent.com/assets/2362137/19336372/42d786d8-9167-11e6-8f21-a4acfc8d2373.png)

**Comment by matthewrmshin** [comment]
(I am looking at a simple fix for 6.11.x, but a slightly better fix for master, which should make `cylc show` a more powerful command.)
