### ISSUE TITLE
Task messaging outputs in dummy mode are propagated improperly to other tasks

### ISSUE THREAD

**Issue by trwhitcomb** [cylc/cylc#2064]
Thanks to #1420, dummy mode now includes the ability to detect and generate cylc messaging commands to allow message-based triggering within suites running in dummy mode.

However, more tasks than expected are actually generating output, resulting in confusing log entries, longer-than-normal runtimes (Because additional sleep commands are added for every output).

The problem arises in `lib/cylc/config.py` where the task messaging outputs are generated.  The dummy mode information is stored in 

    self.taskdefs[name].rtconfig['dummy mode']['script']

(see https://github.com/cylc/cylc/blob/master/lib/cylc/config.py#L1480)

By inspecting the output, everything goes fine until we hit the first task with outputs.  For that task, and then for *every task after that*, the outputs are added even if the tasks do not normally output data.

After some tests, the issue appears to be that the runtime dummy mode configuration information

    self.taskdefs[name].rtconfig['dummy mode']

has the same ID for all tasks - since Python dictionaries are mutable data structures, accessing the `'script'` key within this dictionary has the effect of updating all the tasks that share that dictionary.

The solution will probably be making sure that this dictionary isn't shared, or at least that a copy is created when it's modified.

**Comment by hjoliver** [comment]
Bug reproduced.

**Comment by hjoliver** [comment]
@matthewrmshin - I wonder if this results from changes we made to share as much of the runtime dict as possible, to reduce the memory footprint, and then my change for the dummy mode custom outputs was made after the sharing (/lack of replication) had occurred.  Simplest fix is presumably to replicate that bit of the dict for the dummy custom outputs, but I guess we should check for other errors of the same kind too (and how to know what's shared and what isn't now...?)

**Comment by trwhitcomb** [comment]
@hjoliver I think that's exactly what's going on here.  See

https://github.com/cylc/cylc/blob/master/lib/parsec/OrderedDict.py#L58

I bet that

    self.taskdefs[name].rtconfig['dummy mode']['script'] = 'xxx'

is returning the mutable dictionary of defaults for `rtconfig['dummy mode']`.

This appears to potentially be a larger issue then I first suspected - sorry!

**Comment by hjoliver** [comment]
@trwhitcomb - I think don't think any other config items are affected as that would cause major problems. This case is unusual because we are modifying the dummy mode task scripting on the fly for tasks with custom outputs, after the file parsing and handling of defaults is already done.

**Comment by trwhitcomb** [comment]
That's good.  I tend to get very nervous when I see shared state issues like this!
