### ISSUE TITLE
More delay and grouping of email notifications

### ISSUE THREAD

**Issue by matthewrmshin** [cylc/cylc#2099]
If a large set of task events occur within a short period of time (let's say within a few minutes), users can get many email notifications. (However, if the period of time is very short, like a few seconds, the emails will actually be grouped together.)

It would be desirable to wait a short period of time (e.g. a minute or a few minutes?) before sending a notification email, which can then report the events together in a single email.

**Comment by hjoliver** [comment]
Good idea.
