### ISSUE TITLE
broadcast: settings in file

### ISSUE THREAD

**Issue by matthewrmshin** [cylc/cylc#2108]
While the `--set=[SEC]ITEM=VALUE` option to broadcast is good enough for most cases, it can be quite difficult for:
* multi-line values
* values with lots of shell meta characters.
* many values

It should be possible to support broadcast options from a file that looks like a `suite.rc` fragment (with 2 section levels removed?)

Either:

```cfg
[runtime]
    [[__BROADCAST__]]
        script = printenv FOOBAR
        [[[environment]]]
            FOOBAR=foobar
```

Or:

```cfg
# Broadcast
script = printenv FOOBAR
[environment]
    FOOBAR=foobar
```

We'll then do `cylc broadcast SUITE --file=FILE`?

**Comment by hjoliver** [comment]
Good idea.
