### ISSUE TITLE
Hold (pause) by job host.

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc#2144]
Suggestion from BoM: it would be useful to be able to hold all tasks on a particular host.

This already works via the CLI if (as is typically the case) all tasks on the host inherit from a host-specific family HOST1 (say): `cylc hold SUITE HOST1`

However, host-specific settings (including host-name and batch-system) are usually inherited as secondary families that do not appear in the first-parent hierarchy visible in the GUI - i.e. there is usually no HOST1 family to right-click on.

We could either:
 * allow host-specific hold from the GUI, which would affect all tasks that run on the target host regardless of the family hierarchy, or 
 * allow actions such as hold to target non first-parent families, e.g. right-click could allow optional selection of all parent families as the target of the operation rather than the task itself.

**Comment by matthewrmshin** [comment]
Just to complicate matters... The actual host a task job runs on is only determined at job submit time. Before that, a task only has a host string (which can be a command) from the `suite.rc` and/or a broadcast. So, although bullet point 1 is seemingly more correct, bullet point 2 is the only possible option in reality.

**Comment by hjoliver** [comment]
Sorry, I meant to say - we'd have to distinguish between static and dynamic host determination (most of us outside the MO don't have enough hosts to bother with the latter :-).  Presumably in the GUI you'd get a list of "host names" in which the dynamic host selection command would be pretty obvious.

**Comment by matthewrmshin** [comment]
Somewhat related to #2199, which should allow us to select tasks by host group.

**Comment by matthewrmshin** [comment]
(Can this one be superseded by #2199?)

**Comment by hjoliver** [comment]
(yes)

Superseded by #2199
