### ISSUE TITLE
PBS duplicate directives

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc#2146]
A user from a PBS site recently asked me how to specify multiple `-l=blah` directives in Cylc, like this:

```
-l=select=28:ncpus=36:mpiprocs=18:ompthreads=2
-l=walltime=12:00:00
```
As written above, the second directive overrides the first (i.e. the 'select' one gets ignored) because Cylc sees the directive name as simply `-l`, and everything after the first `=` is the value.

Looking back at an older version Cylc user guide, the first '=' isn't necessary, so we can write this as:
```
-l select=28:ncpus=36:mpiprocs=18:ompthreads=2
-l walltime=12:00:00
```
which works because Cylc now sees different directive names: `-l select` and `-l walltime`

@matthewrmshin - can you comment on whether the first form is legit, and if so can we (re)document that the solution is to use the second form?  (I don't have access to PBS at the moment).

**Comment by matthewrmshin** [comment]
The first form is legit, but everything will need to be in a single line. We normally recommend the second form only.

**Comment by matthewrmshin** [comment]
I'll add something under *Directives Section Quirks*.
