### ISSUE TITLE
gui: graph view - 2nd level r-click task menu items not working on l-click

### ISSUE THREAD

**Issue by oliver-sanders** [cylc/cylc#2154]
Resetting a tasks state via the right click menu in graph view would appear to be broken.

**Comment by arjclark** [comment]
This appears to be down to #2125 

r-click and pressing enter over a highlighted item are fine but the l-click button is no longer working...

**Comment by arjclark** [comment]
N.B. this also applies to the `view => log` menu too (title updated accordingly)
