### ISSUE TITLE
cylc 7.1.0: host name problem due to removed domain name part

### ISSUE THREAD

**Issue by m214089** [cylc/cylc#2167]
Hi everybody,

I do run into a problem with the new communication layer (https). Defined is:

`cylc-run/hello_world/.service/contact:CYLC_SUITE_HOST=cylc7.dkrz.de`

but the message to be sent is shortend to the hostname without the domain part and you can see the error message.

`cylc-run/hello_world/log/job/1/hello/01/job.err:Send message: try 1 of 7 failed: Cannot connect: https://cylc7:43013/message/put?priority=NORMAL&message=started+at+2017-02-17T14%3A00%3A46%2B01&task_id=hello.1: ('Connection aborted.', gaierror(-2, 'Name or service not known'))`

I verified that the hostname without the domain part does not resolve.

Cheerio,
Luis

**Comment by matthewrmshin** [comment]
Hi @m214089,

The offending logic is here:
https://github.com/cylc/cylc/blob/master/lib/cylc/network/https/base_client.py#L83

Does it work if you comment out the if-block?

In the mean time, I'll have a look to see why we have this if-block in the first place.

**Comment by m214089** [comment]
Hi Matt,

commenting the two line you mentioned solved the problem. Now everything is running smoothly.

From my point of view this lines are not needed, even may create problems as in our case. 

Cheerio,
Luis

**Comment by matthewrmshin** [comment]
Hi Luis @m214089,

Thanks for the info. It is good to know (and may even be related to one of the problems raised in https://groups.google.com/forum/?fromgroups#!topic/cylc/Eahss_mXgqM).

I'll raise a pull request on this soon. (These lines should not be necessary. However, there is something incorrect going on when we have a farm of hosts for running suites and if a suite is registered on a host different from the actual run host. I'll need to sort that logic out as well before I raise the PR.)
