### ISSUE TITLE
gcylc: Blank (broken) graph view with runahead filtering

### ISSUE THREAD

**Issue by arjclark** [cylc/cylc#2176]
Problem reproducible as follows:

 - Start simple suite (foo[-P1D] => foo type thing) without any custom filtering
 - Click filtering and check the "runahead" box
 - Swap to graph view
 - Should see an empty graph despite what's actually running

Message dumped to CLI is:

> Cannot connect: https://host:port/info/get_graph_raw?stop_point_string=None&ungroup_recursive=False&start_point_string=20170225T0000Z&group_nodes=None&ungroup_nodes=None&ungroup_all=False&group_all=True: HTTP Error 500: Internal Server Error

Other views are unaffected, so yet another special behaviour for the graph view.

**Comment by arjclark** [comment]
Additional piece of info passed to me is that applying a time range focus undoes the problem when you put in a STOP point and things are displayed again.

**Comment by matthewrmshin** [comment]
Looks a bit like #2159 - the same function is still broken?
