### ISSUE TITLE
cylc ls: no longer invocable

### ISSUE THREAD

**Issue by arjclark** [cylc/cylc#2179]
Due to the existence of `cylc ls-checkpoints` you can no longer use `cylc ls`:
```
$ cylc ls -t SUITEID
'CATEGORY not found: ls'
'COMMAND "ls" not unique: list|ls ls-checkpoints'
```

**Comment by matthewrmshin** [comment]
Can still do `cylc list`? If so, we should either modify the docs for `cylc list` or change the name of `cylc ls-checkpoint`.
