### ISSUE TITLE
Jinja2: custom "assert" filter

### ISSUE THREAD

**Issue by oliver-sanders** [cylc/cylc#2184]
**The Problem**

Some users are writing Jinja2 tests in their suites to prevent them from running in the event of an in-compatible config (Jinja2). A recent example I have seen is:
```
#!Jinja2

{% if not VARIABLE is defined %}
[ERROR: VARIABLE must be defined]
{% endif %}

[cylc]
    UTC mode = True
...
```

This will raise a cylc syntax error quoting the offending line. Sometimes these tests protect Jinja2 logic further into these suites where they can raise more cryptic errors e.g:

```
#!Jinja2

{% if not VARIABLE is defined %}
    {% "ERROR: Variable must be defined." / 0 %}
{% endif %}
...
```

This will raise a Jinja2 exception causing the error to surface before vulnerable logic is attempted.

Rose metadata enables users to write similar checks but it is not compulsory to run these prior to running the suite (https://github.com/metomi/rose/issues/1908).

**Proposed Solution**

It might be a good idea to provide a more elegant way of raising exceptions using a custom Jinja2 filter something like:

```
{% assert( logical ) %}
# Raises an exception (which causes an instant fail) if logical == False

{% assert(VARIABLE is defined, 'VARIABLE must be defined' %}
# The second argument or a kwarg could serve as the error message.
# I.E. >>> Jinja2 Error: VARIABLE must be defined

{% assert( (FOO != BAR) and not BAZ is defined, 'BAZ must be set if FOO and BAR are equal') %}

**Comment by hjoliver** [comment]
Good idea.  @arjclark @dpmatthews - note there's an example of the first kind in one of the suite fragments in the Suite Design Guide you've been reviewing.  @oliver-sanders - if this is a quick one, we could adapt said guide before releasing it...
