### ISSUE TITLE
dummy mode: use execution time limit for sleep time

### ISSUE THREAD

**Issue by oliver-sanders** [cylc/cylc#2185]
For dummy mode it may be useful to have tasks sleep for a percentage of their `execution time limit` to achieve more realistic simulation. This would probably be an optional configuration.

**Comment by hjoliver** [comment]
Very early versions of Cylc actually had proportional dummy run length.  Dropped it because users had to configure timings that had no other use at the time.  But now `execution time limit` is useful...
