### ISSUE TITLE
gscan: missing checker-board status icons

### ISSUE THREAD

**Issue by oliver-sanders** [cylc/cylc#2190]
The checker-board "suite stopped" status icons have disappeared.

**6.11.4**
![screenshot-cylc gscan-old](https://cloud.githubusercontent.com/assets/16705946/23649375/29ecb28a-0316-11e7-8f2c-58b30e54b524.png)
**master**
![screenshot-cylc gscan-new](https://cloud.githubusercontent.com/assets/16705946/23649376/2a432be2-0316-11e7-9913-4d3764db03c5.png)

**Comment by hjoliver** [comment]
`git bisect` identifies 005ddeaf1251256e2cb8fb46c74e85f51d7bf2ae  from #2105 (_t: embed ls-checkpoints tests_) which touches `bin/cylc-cat-state` and `lib/cylc/rundb.py` (likely candidate locations for the problem?)

**Comment by matthewrmshin** [comment]
(Sorry, my bad.)
