### ISSUE TITLE
Apparently null task names are legal?

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc#2200]
Ref https://groups.google.com/forum/#!topic/cylc/fV9qQaJ7nZc

**Comment by matthewrmshin** [comment]
It appears to only affect the graph display when we have `graph = t1 => & t2` or `graph = t1 => t2 &` (i.e. RHS only). The logic does not create a task definition with a null name.

**Comment by matthewrmshin** [comment]
Just to be clear... Empty node on LHS (e.g. `graph = t1 & => t2` and `graph = & t1 => t2`) also validates but does not have the same effect as empty node on RHS.

We can EITHER:
1. Fix display issue if there are empty nodes on the RHS, OR
2. Fail on empty nodes on either side of the expression.

Preference? (2 is more correct, but may break existing suites.)
