### ISSUE TITLE
Improve "cylc check-software"?

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc#2203]
This tool currently does a rather trivial check for a small number software dependencies:
```
$ cylc check-software
Checking for Python >= 2.6 ... found 2.7.5 ... ok
Checking for non-Python packages:
 + Graphviz ... ok
Checking for Python packages:
 + pygraphviz ... ok
 + pygtk ... ok
```

@dpmatthews suggests we could make it a more useful diagnostic tool that users could run and give its output with bug reports:
> ~~Currently it reports the version of Python but nothing else.~~
We could get it to report the versions of all the libraries as well.
~~It could also check for optional dependencies such as pyGTK, graphviz, etc.~~
We could also get it to report the site config, OS details, etc (in verbose mode).

**Comment by matthewrmshin** [comment]
(Check for availability and version of the *requests* library (minimum version 2.4.2) as well.)
