### ISSUE TITLE
Remove auto-fallback to HTTP comms.

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc#2204]
From @dpmatthews:

> Python OpenSSL is required to use HTTPS. Otherwise cylc falls back to HTTP and issues lots of warnings (so it's not really very usable).  I think we should:
> * Allow [communication] method = http (only option at the moment is https) (assuming we want to support this).
>  * Add tests to make sure it works.
> * Modify cylc check-software to test for OpenSSL (unless HTTP option configured).
> * Get rid of the fall-back - i.e. fail if you've configured https method but can't use it.

Also:
 * document the OpenSSL dependency

**Comment by hjoliver** [comment]
Current fallback is imperfect too.  Without HTTPS/SSL support job submission to a remote host fails with `SuiteServiceFileError: Couldn't get ssl.cert`.

**Comment by chanwilson** [comment]
There's also a typo in the CUG in section 12.4; [communications] vs [communication]

**Comment by hjoliver** [comment]
> There's also a typo in the CUG in section 12.4; [communications] vs [communication]

Fixed: 2e2ddd0baf3259c39a05a0c10450caa85efc6de9
