### ISSUE TITLE
Family Workspaces

### ISSUE THREAD

**Issue by oliver-sanders** [cylc/cylc#2210]
Resurrected from a long dead email thread.

We create "work" directories for tasks, some users would find it helpful to have the same functionality for families as well enabling a more encapsulated way to share files between groups of tasks and potentially enabling users to make better use of `rose prune`.

**Comment by hjoliver** [comment]
@oliver-sanders - we can already make a family share the same work directory, but @dpmatthews and @arjclark don't like this (hence warnings in the new suite design guide). But do you mean something different from this:
```
[runtime]
    [[FAMILY]]
          work sub-directory = $CYLC_TASK_CYCLE_POINT/beer
    [[m1, m2, m3, m4, m5]]
          inherit = FAMILY
```

Here `m1, ..., m5` all get a work directory `work/<cyclepoint>/beer` instead of `work/<cyclepoint>/m1` etc.

**Comment by oliver-sanders** [comment]
@hjoliver 

> But do you mean something different from this

Yes. The tasks work directory should be left as is but another separate work directory for the family should also be created.

**Comment by hjoliver** [comment]
In that case, I think you mean a special share directory?  We use "work directory" to mean the directory that the job runs in.

**Comment by matthewrmshin** [comment]
Hi @benfitzpatrick We were under the impression that you think this was a good idea, when it was discussed with the user. Do you mind commenting on this just to remind us whether you still think this is a good idea (or if you don't care about this any more)?

**Comment by MatthewHambley** [comment]
Speaking as a user who has requested this maybe I can clarify why we want it.

It simply comes down to the fact that in our test suite we often have a group of tasks which work together to produce some results. They need to share information between themselves which is achieved by putting files in the "share" directory.

This works but these files do not have long term value, they are purely a communication channel which we would like to be automatically tidied up in the same way work directories are. From this came the idea of associating work directories with "family" tasks. They already have the lifespan we are interested in, ending as they do when the last task hey contain ends. If they had an associated work directory we could dump our communication files in there sure in the knowledge that they would be cleaned up and not pollute "share".

One possible implementation would be to provide something like CYLC_FAMILY_\<NAME\>_WORK_DIR in addition to CYLC_TASK_WORK_DIR. Obviously a task can be a member of multiple families so there needs to be a way of coping with that.

If "work directory" has a meaning within the project which is incompatible with this functionality feel free to call it something else. Equally it doesn't have to be in the "work" directory. The requirements are:

* Shared space available to all  members of a family
* Removed upon successful completion of the family

**Comment by dpmatthews** [comment]
Spoke to @MatthewHambley about this. The key requirement is auto-removal which we don't even have for work directories (other than empty ones). Hard to see how this would work, especially once you start considering multiple platforms (with or without shared filesystems). Using the `share` directory and explicitly housekeeping the data is the best approach (at least for the moment).

Closing (unless anyone from @cylc/core disagrees?).
