### ISSUE TITLE
paramaterized tasks - environment variable order

### ISSUE THREAD

**Issue by oliver-sanders** [cylc/cylc#2225]
Inheritance can affect the order in which environment variable declarations are written in the job file. This can cause problems with parametrized tasks.

The following runtime ...
```
[runtime]
    [[root]]
        script = sleep 1
        [[[environment]]]
            PARAM = 'something'
    [[task<task>]]
        [[[environment]]]
            PARAM = $CYLC_TASK_PARAM_task
```
... will result in this job file:
```bash
cylc__job__inst__user_env() {
    # TASK RUNTIME ENVIRONMENT:
    PARAM="$CYLC_TASK_PARAM_task"
    CYLC_TASK_PARAM_task="1"
    export PARAM CYLC_TASK_PARAM_task
}
```
Note the `PARAM` variable is declared before `CYLC_TASK_PARAM` and thus, will cause an error.

By contrast when the `[root][environment]PARAM` setting is removed the job file is written correctly:

```bash
cylc__job__inst__user_env() {
    # TASK RUNTIME ENVIRONMENT:
    CYLC_TASK_PARAM_task="1"
    PARAM="$CYLC_TASK_PARAM_task"
    export CYLC_TASK_PARAM_task PARAM
}
```

_Note: This bug was reported with 6.11.4_

**Comment by hjoliver** [comment]
Suite parameters should really be in the suite environment, not the user environment as if defined in a suite.rc `environment` section.  I probably intended to come back and fix this, when implementing suite parameters.

**Comment by hjoliver** [comment]
Xiao has reported runing into this at BoM.
