### ISSUE TITLE
gscan - stop or hold suites?

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc#2227]
It would be useful to be able to stop or hold suites (or groups of them) by right-clicking on them in gscan.

**Comment by matthewrmshin** [comment]
Agree that it would useful. Should be relatively easy to do as well.

**Comment by hjoliver** [comment]
Further, it would be good to be able to start or restart stopped suites like this.  Depends on #1302

**Comment by matthewrmshin** [comment]
> start or restart stopped suites

See also #1885. For our site, it would be useful to add the logic to (re)start suite on a pool server before doing this.
