### ISSUE TITLE
suite log server warning

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc#2228]
Class `SuiteLogServer` in `lib/cylc/network/https/suite_log_server.py` (only used by gcylc to retrieve suite logs?) contains two calls to methods that don't seem to exist: `self.log.warn()` and `self.log.warning()`.

**Comment by matthewrmshin** [comment]
(The issue has hit me while coding #2157, I have modified the statements to use `cylc.suite_logging.LOG` in that branch. However, I am happy for this issue to be fixed separately.)

**Comment by hjoliver** [comment]
@matthewrmshin - fine to leave it for your new PR IMO.
