### ISSUE TITLE
Re-think on queues

### ISSUE THREAD

**Issue by arjclark** [cylc/cylc#2251]
Capturing the talking points from: https://github.com/cylc/cylc/pull/2246#issuecomment-296326025 onwards

Points for discussion:
 * We have a default set of settings for tasks under the `root` family and a default queue called `default`. It seems odd that the naming conventions here vary
 * Simply renaming the queue to "root" could suggest to some users that queue names are synonymous with Family
 * It may be more useful to re-design how we define a queue so it is of the form in https://github.com/cylc/cylc/pull/2246#issuecomment-296326558 :
```
[queue limits]
     root = 20
     FAM1 = 5
     FAM2 = 5
```

**Comment by arjclark** [comment]
@cylc/core - thoughts?

I think @hjoliver's suggestion of queue limits based on Families makes a lot of sense - again its ultimately a shared config item.

As a possible extension, why not integrate queue limits into general runtime settings anyway?

**Comment by hjoliver** [comment]
@arjclark - good point, if queues are entirely family based then I guess they might as well be defined under run time. One undesirable aspect of this though: queue limits would be inherited right down to single task level, which doesn't make much sense.

**Comment by dpmatthews** [comment]
Using queue limits based on families is less flexible. Sometimes I've used queues on a temporary basis involving multiple families or tasks - it would have been more work to add in a new family to achieve this.

So far, at least, I'm not convinced it is worth changing the current syntax (which doesn't seem that bad to me).

**Comment by matthewrmshin** [comment]
Are the queue names used in any way at the moment? Is there any way to assign a task to a given queue temporary during run time at the moment? Is there a way to change the limit of a queue at run time? If so, then any change to the syntax will have to cater for these functionalities.

**Comment by hjoliver** [comment]
@cylc/core -on reflection I think I agree with @dpmatthews comment above, so we should stick with the status quo and close this issue if others agree?

(@matthewrmshin - the only way to change queue config at run time is via a reload - I think that'll work)

**Comment by matthewrmshin** [comment]
Close agreed.
