### ISSUE TITLE
gscan/gui: intelligent update frequency

### ISSUE THREAD

**Issue by oliver-sanders** [cylc/cylc#2262]
Currently gscan performs a `scan_all` every time it updates. This is a slow process and so gscan is infrequently updated. This process is, however, only required to pick up new suites. Once gscan is aware of a suite it can query it directly which is much faster and thus can be performed more frequently.

**Comment by matthewrmshin** [comment]
This was discussed off-line.

Large number of users running `gscan` may result in all suites running on the scan hosts being swamped.

Consider the main usage for `gscan` - which is for each user to monitor his/her running suites (and/or not-running ones, see #1302). In this usage, we don't really need a scan to locate the relevant suites. Looking under a user's `~/cylc-run/` directory should be sufficient.

We should either modify `gscan` to allow it to work in this way (intelligently based on options and settings) or write a new command (with a similar presentation front end as `gscan`) to work in this way.

**Comment by matthewrmshin** [comment]
More thoughts on update frequency adjustment:
* Configurable via `global.rc`?
  * Frequency of `host:port` scan or `~/cylc-run/` scan.
  * Frequency of API calls per suite.
* For `cylc gui`, we should be able to intelligently adjust the API call frequency according to suite activity. E.g.:
  * Use latest main loop times to estimate next update time - useful if main loop takes >1s to run. It is pointless to keep asking for updates before the main loop completes a run.
  * Reduce update frequency for suites in a quiet period. E.g. It is pointless to keep asking for updates for a suite waiting for a task with a long execution time or for a suite waiting for a clock trigger that is not due for a while.
