### ISSUE TITLE
automatic suite-state tasks broken at cylc-7.3.0 

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc#2268]
Oops, my fault via 200e18c5f2f881e289 (sim and dummy mode enhancement).  Now generating empty `script` string instead of `cylc suite-state ...`.   Evidently the relevant tests in `tests/suite-state/` are passing even if their tasks succeed immediately (rather than triggering off the tasks in the upstream suite).  This is quite a serious bug, the feature is used a lot in NIWA's operational suites (but ah, fortunately, we're still stuck at 6.11.4 awaiting central intallation changes). @matthewrmshin - hopefully at MO you're still using roll-your-own suite-state scripting, or not up to 7.3.0 yet?

**Comment by matthewrmshin** [comment]
I believe users are mainly on *roll-your-own suite-state scripting*, as we don't have users reporting this problem on 7.3.0.
