### ISSUE TITLE
job.sh not found on remote host

### ISSUE THREAD

**Issue by mjwoods** [cylc/cylc#2273]
In 68d0c4787566ccd256872ff6bbb8d91f91311793, @matthewrmshin has neatly separated the static part of a job script into an external file, which is included at run-time with the following command:

```shell
. "${CYLC_DIR}/lib/cylc/job.sh"
```

Variable CYLC_DIR is defined as the cylc location on the suite host. This causes jobs to fail if cylc is installed in a different location on execution hosts, which is unfortunately the case at our site.

Is there a recommended workaround for this situation? If not, is there a need to provide a site configuration option that defines CYLC_DIR on remote hosts? Or could it be derived from the existing `cylc executable` option?

**Comment by hjoliver** [comment]
@mjwoods - running distributed systems - with potentially multiple cylc versions installed and many ways users could provide access to Cylc on jobs - is complicated.  That said, I thought we had this working: I think CYLC_DIR is supposed to be adjusted on the fly to point to the `lib/cylc/` in the Cylc version being invoked.  Unfortunately I've run out of time to test and investigate tonight, but maybe our UK colleagues will chime in overnight...

**Comment by matthewrmshin** [comment]
On job submission, `cylc jobs-submit` would modify `CYLC_DIR` in the job script on the fly. This is how it works on our site.

However, if you have a batch system where you are able to submit your job on the suite host, but the job actually executes in a host with a totally different environment, then this will not work. What you can do is use `global init-script` to modify your environment. E.g.:

```cfg
[hosts]
    [[HOST]]
        global init-script = """
export CYLC_DIR=/path/to/cylc-dir
"""
```

https://cylc.github.io/cylc/html/multi/cug-htmlse15.html#x16-420000B.9

**Comment by matthewrmshin** [comment]
(Close as invalid - the reported statement is not true - and I believe the actual problem can be worked around via a configuration. Please feel free to reopen if this does not solve your problem.)

**Comment by hjoliver** [comment]
@mjwoods - it would still be good to know why this (evidently) failed for you.  Was this under your "hybrid mode" setup (i.e. local submit to PBS on suite host)?

**Comment by mjwoods** [comment]
Hi @matthewrmshin,

We are not doing any fancy "hybrid" communications with this pair of hosts - just bi-directional ssh.

Remote jobs are working for me now. It turned out that I had a python module problem on the remote host. The remote cylc was not starting properly and job files were therefore not being generated on the remote side. When I looked at the job files on the suite host, they showed the CYLC_DIR for the suite host, and I assumed that the incorrect path was being used to invoke cylc on the remote host. This automatic path translation is an easy trap for beginners like me.

For the record, I do not think your suggested solution would have worked. It looks as though the global init script is embedded in function `cylc__job__inst__global_init_script`, which is invoked by `cylc__job__main`, which is defined in `${CYLC_DIR}/lib/cylc/job.sh`. So `CYLC_DIR` would need to be defined correctly in order to redefine `CYLC_DIR`! My head hurts now ...

**Comment by matthewrmshin** [comment]
OK. You are right, the `init-script` solution will not work - as there is previously a requirement that `init-script` must run after the job script's prelude section.

However, I hope we never have to support different `CYLC_DIR` between the hosts for job submission and job execution. If we have to support something like this, it will need to be a setting specific to both the job submission host and the batch system. E.g.:

```cfg
[hosts]
    [[my-hpc-submission-host]]
        [[[batch systems]]]
            [[[[pbs]]]]
                # Suggested setting, not yet implemented!
                job execution cylc dir=/path/to/cylc
```
