### ISSUE TITLE
cylc reg "[\n]\0 \/\/ `exit`"

### ISSUE THREAD

**Issue by oliver-sanders** [cylc/cylc#2281]
Currently cylc will let you register suites with unsafe characters. My favourites are:
- Empty string
- Backquotes
- New lines, tab, null characters

**Comment by dvalters** [comment]
Python string methods: `isalpha(), isdigit(), isalnum()` will test a character is alpha/number/alphanumeric. This also works on unicode strings, and (it would appear) on non-latin alphabets characters. 

```python

chinese_string = u'中文。'
for char in chinese_string: print char, char.isalpha()
    
# > 中 True
# > 文 True
# > 。 False

# German
german_string = u'„Hallo! Grüß dich 666!“'
for char in german_string: print char, char.isalnum()

# true for all the letters, including non-English ones, false for all others.
# etc...
```
Example here:

https://github.com/dvalters/Notebooks/blob/master/is_it_a_letter.ipynb

**Comment by matthewrmshin** [comment]
In theory, we should be able to get `re.compile(ur'\w', re.U)` to match Unicode word characters. This didn't work in my environment the last time I looked (when I was working to white list the allowed characters for task names). I have just taken a look in my environment, and it seems to be working now! I'll see if I can repeat this success in a different environment, so we can modify the logic for matching  task names as well.

**Comment by dvalters** [comment]
> In theory, we should be able to get re.compile(ur'\w', re.U) to match Unicode word characters.

There is a flag (`flags=re.UNICODE`) for unicode that might have to be passed to `re.compile(ur'\w', re.U)` for the regex module to do this with unicode strings:

https://docs.python.org/2.7/library/re.html#re.UNICODE

**Comment by dvalters** [comment]
...I couldn't get that regex to work either

**Comment by matthewrmshin** [comment]
I think we should revisit this one when we port cylc to Python 3 - #1874, when we can be sure that all strings are automatically Unicode.

**Comment by matthewrmshin** [comment]
See also #51.

**Comment by oliver-sanders** [comment]
We may want to roll this one into #2979

**Comment by matthewrmshin** [comment]
Please close. (The originator of this issue can do the honour.)

**Comment by oliver-sanders** [comment]
Superseded by the more generic #2979
