### ISSUE TITLE
gscan misc view improvements

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc#2284]
Follow one #2259 

https://github.com/cylc/cylc/pull/2259#issuecomment-301525073

- [ ] Columns menu via right-click on table heading.
- [ ] Menubar/Toolbar startup size issue, see below.
- [x] If using "Groups", stopped suites lose their group identity and end up under "None".

~@oliver-sanders - can you elaborate on the "strange behaviour with the separator between the menubar and the toolbar" - I haven't noticed anything.~

**Comment by oliver-sanders** [comment]
> can you elaborate on the "strange behaviour with the separator

There is a bit of a graphical oddity with the menu-bar appearing with a different background to the toolbar, though this may not be curable. My main issue is that the toolbar does not resize to fill available space, see screenshots.

![shrunk](https://cloud.githubusercontent.com/assets/16705946/26102111/867b42ae-3a2b-11e7-9644-77ef0d5a2e20.png)
![expanded](https://cloud.githubusercontent.com/assets/16705946/26102112/86a2c680-3a2b-11e7-915b-481e0ec95ae7.png)

**Comment by hjoliver** [comment]
Ah yes, I did see those, which I took as pretty minor annoyances that are probably built into GTK - if you want to put a menubar and toolbar in the same hbox (which is a bit unusual?).  But a fix may be worth a try...

**Comment by matthewrmshin** [comment]
Title edited to make it easy for my brain (sorry if it does not work for you). Description edited to have tick boxes. I am going to gave a quick look at point 3 to see if there is an easy fix or not.

**Comment by kinow** [comment]
We are now working [on the new Web GUI](https://github.com/cylc/cylc/issues/1873), which will replace the previous Desktop PyGTK GUI in our next major release of Cylc 8.

This issue is being closed for not being applicable to this new Web GUI.
