### ISSUE TITLE
cylc version self-identification problem

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc#2285]
Currently:
 * in an unpacked release tarball, 'make' creates a VERSION file containing the version number that is henceforth used for self-identification
 * in a Cylc git repository, code in `lib/cylc/version.py` uses `git describe` to create a "version number" (string) that reflects the change history since last version tag

If '.git/' directory is detected, the latter is assumed.

It has just come to my attention that **users may want to turn an unpacked Cylc release into a new git repo** as a quick way to track local changes during installation or whatever.  This seems a reasonable thing to do, but it breaks the above mechanisms!   Need a better way...

**Comment by matthewrmshin** [comment]
Hi @hjoliver I am not entirely sure about the use case here. There are 2 very simple solutions for the users at the moment:

1. Create a normal git clone of the cylc project.
2. If they must turn a release tar ball into a git repository, all they need to do is run the `git tag` command to tag the initial commit to the same name as the release.

Or am I missing the point?

**Comment by hjoliver** [comment]
@matthewrmshin - the use case is as above: user installs a Cylc release from tarball and decides to mess with the code a bit for whatever reasons (perhaps local installation problems), and naturally enough decides to use git to keep track of his own changes to the release code. 

As I said, this doesn't strike me as an unreasonable thing to do - in fact I've done the same myself a number of times with other software packages.   But unfortunately if you merely do `git init` inside a release our version self-identification goes awry because the code assumes (based solely on presence of `.git/`) that it must be a Cylc repository clone, which it isn't. 

IMO for this use case, the "version" should stay locked at the release version.  The just wants to know "this is cylc version X" and (from git) "these are the changes I made to cylc version X after installation".

**Comment by hjoliver** [comment]
Maybe we just need to look at the git history a bit to see if it really is a proper Cylc clone, and if not look for the VERSION file. 

Or reverse the precedence - if VERSION file exists use that, if it doesn't exist check for .git.  (this would be faster too, with downside that it would affect developer clones if we run `make` in them...)

**Comment by hjoliver** [comment]
To your specific points - I don't think either 1. or 2. are obvious in the use case I've described (e.g. a system admin installing Cylc for the first time).  We could document this of course, but if there's a simple solution that just works...

**Comment by hjoliver** [comment]
Proposed solution:

 1. if VERSION file exists, use it to identify the cylc version, else look at .git (and perhaps abort if not a proper cylc clone).
 2. and `make` should only create the VERSION file if we are not inside a clone (to avoid messing with developer clone version).

**Comment by matthewrmshin** [comment]
That sounds OK.

(For information, Rose has a similar mechanism to the way cylc currently does it, i.e. use `git describe` version where possible, use version file otherwise. The difference is that the version file is updated as part of the release process, so it is always there with the string containing the current release number.)

**Comment by hjoliver** [comment]
@matthewrmshin - in Rose, have you automated version file creation (as part of some release-generating script) or is it created manually - I'd rather avoid the latter in case of human error.

**Comment by matthewrmshin** [comment]
@hjoliver It is manual, unfortunately. (I think I can just about trust myself with a version string!)

**Comment by hjoliver** [comment]
Suggested this should be done with planned `bin/cylc` refactor by @dvalters

**Comment by dvalters** [comment]
Just for clarity in implementing #2305 (@matthewrmshin), what should the version be if there is no VERSION file, nor .git, nor is it not a proper cylc clone; version-less, or something else? A warning to user that they need to run `make` before their cylc has a version?

**Comment by matthewrmshin** [comment]
There is no right answer. 3 options are available here:
* Current cylc behaviour, die and tell user to run `make version`.
* Current Rose behaviour, use value in version file, which is most likely set to the name of the latest release.
* Set the version to the value `unknown` (or similar).

**Comment by dvalters** [comment]
If no-one has a preference I will just pick my favourite and implement :) (I'm leaning towards `die and tell user to run make`...)
