### ISSUE TITLE
Event handler argument quoting

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc#2335]
A user reports:

```
 [[[events]]]
       failed handler=error.pl %(event)s %(suite)s %(point)s %(name)s %(message)s
```

> Unexpectedly, my wrapping of `%(message)s` in quotes results in the message being seen as multiple arguments to my handler.

I guess we need to checkout for existing quoting before adding our own...

**Comment by dvalters** [comment]
☆ZVEzzZm

**Comment by dvalters** [comment]
Xd 4Gė   r  2xx 1  hx5  gzb3 x    zD the d  . '+t# 44  exz

**Comment by dvalters** [comment]
(Sorry, ignore my bizarre comments - I think I must have lent on my phone in my pocket or something..)

**Comment by matthewrmshin** [comment]
They are done here, using `pipes.quote`.

https://github.com/cylc/cylc/blob/7.4.0/lib/cylc/task_events_mgr.py#L822

**Comment by matthewrmshin** [comment]
Can we just document that strings will be quoted automatically if required?

**Comment by hjoliver** [comment]
>... "if required"?

The user's report suggests that quoting is applied even if not required (i.e. if supplied already by the user), which effectively cancels the correct quoting. 

If so, we should document that event handler arguments should not be quoted in the string template.  However, I have not actually tested this yet.

**Comment by matthewrmshin** [comment]
That's surprising, as I thought the `quote` function only quotes a string if necessary. I'll do a quick test tomorrow.

**Comment by matthewrmshin** [comment]
The `quote` function in my environment behaves as expected.

Note: It is never safe for users to quote the arguments themselves, because argument strings may contain the quote characters. The document should say this, and tell users that template arguments that require quoting will be quoted automatically, so they should never quote the template arguments.

**Comment by hjoliver** [comment]
OK, let's just document this and close the issue.
