### ISSUE TITLE
parallel scheduling

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc#2348]
Something to consider longer term: Cylc's internal scheduling algorithm should be very amenable to parallelization: just split the task pool into sub-pools on different processors.  They only need to interact through the "dependency broker" that records all completed task outputs, and incoming task messages and commands would have to be targeted to the right pool (could be achieved by some kind of central queue that all pools look at, perhaps).

**Comment by hjoliver** [comment]
Might not be needed after https://github.com/cylc/cylc/issues/2329#issuecomment-313623017 ?

**Comment by matthewrmshin** [comment]
I hope so, until #2329 becomes unable to handle whatever users will throw at their suites!

**Comment by hjoliver** [comment]
I'll close this as (I hope) unlikely to be necessary in the foreseeable future.  It's still on the record if we need to reconsider...

**Comment by matthewrmshin** [comment]
(Marking as superseded, which is sort of right.)
