### ISSUE TITLE
Restart sends unreported outputs for succeeded tasks

### ISSUE THREAD

**Issue by GlennCreighton** [cylc/cylc#2361]
Not sure if this is a bug, but I have noticed an undesirable effect when running cylc-2017.02.0.  In it I have a task that either ouputs a "data" or "nodata" message.  This message triggers one of two branches in the suite graph.  The task always succeeds with unreported outputs (which annoyingly triggers a warning; I wish there was a way to specify optional outputs, but I digress), however the real problem is when I stop and restart the suite.  At that point, the unreported output messages get marked as sent and both branches of my suite get activated (in my case suiciding jobs which should not be suicided).  I thought that Cylc kept a record of messages and treated these custom messages as any other message, so I am surprised to see this behavior.  Is this a known issue?

**Comment by matthewrmshin** [comment]
Yes, the behaviour of the normal succeeded message handling logic is not consistent with the restart succeeded state handling logic.

(*cylc-2017.02.0* is likely *cylc-7.3.0*? This inconsistent behaviour is not specific to this version, however. It has been around for a long time, and is still present on master, with TODO statements near the problematic logic.)

**Comment by GlennCreighton** [comment]
Yes, sorry I meant cylc-7.3.1.  Thanks for looking into fixing this!
