### ISSUE TITLE
recent bug: gcylc launches wrong cylc version

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc#2377]
Just noticed on current master, starting a suite from  `gcylc` when `CYLC_HOME=/home/USER/cylc.git` (e.g.) launches default installed version  `/opt/cylc` instead of the repository version.
```
~/cylc.git$ git bisect bad
b61189dd313026eb01c1706308af7f769525ae26 is the first bad commit
commit b61189dd313026eb01c1706308af7f769525ae26
...
    Improve remote host/owner logic
```

**Comment by hjoliver** [comment]
(i.e. the PR just merged today)

**Comment by matthewrmshin** [comment]
@hjoliver It seems to work for me. Can you provide a more detailed recipe to reproduce?

**Comment by hjoliver** [comment]
This is strange!  I'm testing on my metomi VM.  `CYLC_HOME` is not propagated to the cylc wrapper, when `cylc run` is launched from the GUI.  Will investigate further...

**Comment by matthewrmshin** [comment]
OK. That gives me a slightly better handle to the problem. I'll do a bit more tests tomorrow, as the problem can potentially causes issues with how we deploy cylc on site.

**Comment by hjoliver** [comment]
`gcylc` is invoking `cylc run` with the `--user=$USER` option, and that option appears to be nuking `$CYLC_HOME` (since your PR went in).

**Comment by hjoliver** [comment]
Looks like `--user` is now causing `cylc run` to do an ssh "remote run" as if targeting another host (and hence disconnecting from the suite daemon environment).
