### ISSUE TITLE
profile battery - local experiments

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc#2402]
A quick test the other day suggested experiments under `.profiling/` don't work as advertised - probably just a simple dir creation issue, I think.

**Comment by oliver-sanders** [comment]
The profile battery will pick up experiments in the `.profiling/experiments/` directory.

**Comment by hjoliver** [comment]
Probably my mistake - I'll check again and close the issue...

**Comment by hjoliver** [comment]
```
vagrant@vagrant:~/cylc.git$ find .profile
find: ‘.profile’: No such file or directory
vagrant@vagrant:~/cylc.git$ find .profiling/
.profiling/
.profiling/experiments
.profiling/experiments/test.json

vagrant@vagrant:~/cylc.git$ cylc profile-battery -e test -v master 7.4.0 7.3.0
Traceback (most recent call last):
  File "/home/vagrant/cylc.git/bin/cylc-profile-battery", line 953, in <module>
    main()
  File "/home/vagrant/cylc.git/bin/cylc-profile-battery", line 936, in main
    schedule, exps_to_run = get_schedule(versions, experiments, test=opts.test)
  File "/home/vagrant/cylc.git/bin/cylc-profile-battery", line 212, in get_schedule
    result_keys = get_result_keys()
  File "/home/vagrant/cylc.git/bin/cylc-profile-battery", line 191, in get_result_keys
    profile_results = get_results()
  File "/home/vagrant/cylc.git/bin/cylc-profile-battery", line 173, in get_results
    create_profile_directory()
  File "/home/vagrant/cylc.git/bin/cylc-profile-battery", line 91, in create_profile_directory
    os.mkdir(profile_dir)
OSError: [Errno 17] File exists: '/home/vagrant/cylc.git/.profiling'
```

**Comment by oliver-sanders** [comment]
Looks like you don't have a results file (but do have a .profiling directory) which causes it to fall over (this is something I've fixed in a branch I'm currently working on).

Try `echo '{}' > .profiling/results.json`

**Comment by hjoliver** [comment]
Yep, that worked.

**Comment by hjoliver** [comment]
Is you new branch going up soon, or should we fix this bug for the next release?

**Comment by oliver-sanders** [comment]
My branch should be ready in the next couple of weeks...

**Comment by hjoliver** [comment]
@oliver-sanders -so in that case would you mind back-porting the fix for this from your new branch, so we can put it in next-release and close this issue (only if it's a very small job... which I'm guessing it is)
