### ISSUE TITLE
__MANY__ config keys with multiple internal spaces

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc#2417]
Config item keys (as per "key = value") that are destined for external interpretation (such as by batch systems) are (naturally enough) taken literally by Cylc.  The result is, using PBS directives for example, we do not recognize that `-l select` (one space) is the same as `-l  select` (two spaces):

```
[scheduling]
    [[dependencies]]
         graph = task1
[runtime]
     [[HPC]]
        [[[job]]]
           batch system = pbs
        [[[directives]]]
           -l select=1:ncpus=1:mem=5GB
     [[task1]]
        inherit = HPC
        [[[directives]]]
            -l  select=1:ncpus=24:mem=20GB
```

In this suite, the task-specific select directive should override the inherited one, but they both end up in the job file:

```
$ cylc jobscript foo task1.1 | grep select
#PBS -l select=1:ncpus=1:mem=5GB
#PBS -l  select=1:ncpus=24:mem=20GB
```

This is an easy error to make and hard to detect.  Cylc should not be expected to understand PBS directives, and in principle a batch system could have directive names that contain multiple consecutive internal spaces, but that seems highly unlikely in practice... so perhaps we should:
 * generically fail all such cases during validation, or
 * get batch sys handlers to do that, where it is known for sure that consecutive spaces aren't ever needed  

(I think the first will do)

**Comment by matthewrmshin** [comment]
1st bullet point should be nice and easy to implement. (Until we have a use case for the 2nd bullet point, we should stick with 1st bullet point solution.)
