### ISSUE TITLE
gscan/gcylc: launching gcylc via gscan incorrectly shows suite as stopped

### ISSUE THREAD

**Issue by dvalters** [cylc/cylc#2422]
Reported by user launching launching gcylc by double clicking on a suite in gscan.

(Since 7.5)

Reproducible using same steps:
1. Start a test suite running
2. Launch gscan
3. Launch gcylc by double-clicking the suite in gscan
4. In gcylc, the suite shows as "Stopped", even when the suite is still running.

Launching gcylc from the command line does not produce the issue (only via gscan)

Note that the domain name is omitted when launched via gscan (top image), but not when launched via the command line (bottom image). 

![launch-differ](https://user-images.githubusercontent.com/10996571/30216423-df39ca8a-94aa-11e7-86cb-67303bfedfeb.png)

**Comment by dvalters** [comment]
git bisect shows: (but just double-checking this)

```
94ae017c69b6fbdc961a8a6244c72da639a6a870 is the first bad commit
commit 94ae017c69b6fbdc961a8a6244c72da639a6a870
Author: Matt Shin <matthew.shin@metoffice.gov.uk>
Date:   Tue Aug 1 11:17:04 2017 +0100

    Improve host management
    
    Remove `DNS:*` from SSL certificate.
    Improve client `localhost` logic.

```

**Comment by trwhitcomb** [comment]
Rather ironic, because the reported issue is exactly the same as what I ran into with pre-7.5.0 versions of Cylc: everything works fine from the command line, but opening gcylc through gscan shows exactly this behavior.

Those changes found in the bisect are what actually fixed it for me - I just tried this yesterday, and things are working as expected in the new version.

**Comment by dvalters** [comment]
Intriguing! I will re-check next week, the bisect tests were slightly flaky when I did them (hence my uncertainty above) 😕

**Comment by hjoliver** [comment]
Works fine for me, on all platforms that I currently have access to.

**Comment by dvalters** [comment]
Looking like this is some site-specific conflict...

**Comment by dvalters** [comment]
OK, it looks like we can fix this with our own site config. For reference, we need to specify the full host plus domain name in site config. E.g. `example06.domain.com` rather than just `example06`, which had previously worked.

**Comment by hjoliver** [comment]
@dvalters - I think it would still be worth understanding why the unqualified host name had that effect, so we can either deal with it or warn against it (unless the problem was caused by a misconfigured DNS or something?)

**Comment by dvalters** [comment]
@hjoliver Yes, true - we can re-open for now until we understand it better?

**Comment by hjoliver** [comment]
Yes, will do!

**Comment by matthewrmshin** [comment]
(I have now got a good handle of this problem. Basically, a supplied host name without a domain name causes the client to fail as it is unable to verify with the SSL certificate (in which the suite host name is recorded with the domain name).

**Comment by trwhitcomb** [comment]
@matthewrmshin That's consistent with what I saw before.
