### ISSUE TITLE
GUI issues on current master (OK at 7.5.0)

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc#2428]
* half of the graph view right-click task menu is missing
 * suite log viewer (via main Suite menu) broken.

**Comment by matthewrmshin** [comment]
Most likely victim of #2373.

**Comment by matthewrmshin** [comment]
Log viewer issue identified as victim of #2375.

**Comment by matthewrmshin** [comment]
Actually both are victims of #2375 and not #2373. I'll raise a fix.
