### ISSUE TITLE
cylc trigger --edit behaviour improvement

### ISSUE THREAD

**Issue by matthewrmshin** [cylc/cylc#2460]
This behaviour of `cylc trigger --edit` is not ideal:
1. Invoke `cylc trigger --edit`.
2. Make a change to the job file, and save.
3. When prompted to run the task, answer *no*.
4. Trigger the task normally, and it will run with the *modified* job file.

Most users would assume that a *no* answer would discard the modification to the job file. We should either document the current behaviour carefully, or modify the behaviour.

Reported by @stevewardle in a private conversation.

**Comment by matthewrmshin** [comment]
It is also worth imagining a work flow like https://github.com/cylc/cylc/pull/2449#issuecomment-337191224 in the future- but in this case:
1. Client asks the suite to put the task on hold
2. Client asks the suite to generate the job file.
3. Client downloads the job file.
4. Client launches an editor:
  a. *On change+confirm*: Client uploads the content of the job file to the suite.
  b. Client asks the suite to un-hold the task.
  c. *On change+confirm*: Suite runs the task-job with the uploaded job file.

**Comment by arjclark** [comment]
This has definitely caught me out recently - good to now understand what's going on!

**Comment by hjoliver** [comment]
Oops, apologies - definitely not intentional.  For a quick fix under the current edit run mechanism, it should be sufficient to delete the modified job file if the user chooses "no" - OK?

**Comment by matthewrmshin** [comment]
Yes, fixing the behaviour in the current mechanism should be trivial.

**Comment by hjoliver** [comment]
Not entirely trivial - I think I was saving the aborted job log directory rather than deleting it because it was easier under the two-step process (1. generate job file *plus record its path and increment submit number*; 2. submit it (or not, if aborted). PR coming though.

**Comment by matthewrmshin** [comment]
Close by #2461. Futuristic part moved to #2466.
