### ISSUE TITLE
GUI should access suite items only via the API

### ISSUE THREAD

**Issue by matthewrmshin** [cylc/cylc#2466]
In the future, we should modify the GUI so that all relevant commands are accessed though the API of the running suite (with the exception for suites running on `$USER@localhost`?) so we don't have to rely on non-interactive SSH to remote suite/task hosts.

See also these comments:
https://github.com/cylc/cylc/pull/2449#issuecomment-337185393
https://github.com/cylc/cylc/pull/2449#issuecomment-337191224
https://github.com/cylc/cylc/issues/2460#issuecomment-339001335

**Comment by oliver-sanders** [comment]
This should be superseded by #1873

**Comment by hjoliver** [comment]
Definitely superseded!

**Comment by kinow** [comment]
>hjoliver added the superseded label 41 seconds ago

Good label! Will use it tomorrow for other issues I may find!

**Comment by hjoliver** [comment]
(That's me done for the night :sleeping_bed: )
