### ISSUE TITLE
Terminology unification: suite server program

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc#2471]
Ref https://github.com/cylc/cylc/pull/2469#issuecomment-341659520 and preceding discussion.

Throughout the documentation a running suite server program is variously referred to as "cylc", "the suite", "the suite daemon",  "the suite server", and "the suite server process" (and maybe more). 

These are all more or less inaccurate or ambiguous terms. They should all be replaced with "**the suite server program**" (which is both accurate and unambiguous, if slightly unwieldy).

**Comment by matthewrmshin** [comment]
@dpmatthews just mentioned *suite controller* as well, which is also not a bad phrase (borrowed from the MVC design pattern).

**Comment by hjoliver** [comment]
Hmmm, maybe, but I think most users think of the GUI as "the controller".

**Comment by matthewrmshin** [comment]
@hjoliver I hope you don't mind me grabbing this one off of you. I am trying to get the docs issues (this one), #2499 and #2500 sorted in one go.

**Comment by hjoliver** [comment]
All good, thanks
