### ISSUE TITLE
make-tarball script no longer works

### ISSUE THREAD

**Issue by jontyq** [cylc/cylc#2482]
/admin/make-tarball has succumbed to bit-rot due to no longer being used.

We now have a requirement for rolling our own tarballs in-house.

The script is failing like this:

```
$ ./admin/make-tarball 
./admin/make-tarball: line 38: cylc: command not found
ERROR
```

**Comment by hjoliver** [comment]
(agreed - for the purpose of this script there's no need to insist on the host cylc clone's bin dir being in PATH already).
