### ISSUE TITLE
Parameters broken inside family names.

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc#2484]
Bug reported by @ColemanTom:  Parameters seem to work fine *inside* task names `foo<param>bar` but not inside family names.  From a quick a look, it appears that the post-parameter bit is being dropped from processing of `inherit = FAM<param>bar`.  Probably an easy fix.

**Comment by matthewrmshin** [comment]
For example:

```
[cylc]
    [[parameters]]
        s = mercury, venus, earth, mars
[scheduling]
    [[dependencies]]
        graph = X<s>Y
[runtime]
    [[X<s>Y]]
        script = true
    [[x<s>y]]
        inherit = X<s>Y
```

On `cylc validate` of the above suite, you will get:

```
'ERROR, undefined parent for x_mercuryy: X_mercury'
```

**Comment by matthewrmshin** [comment]
(@sadielbartholomew This bug requires a simple fix that is probably a good introduction to the guts of cylc. I'll walk you through the location of the problem and how to create a test for the fix, etc.)

**Comment by sadielbartholomew** [comment]
Thanks for your assistance with this Matt.
