### ISSUE TITLE
parameters: zero-padding integer values when a parameter template exists

### ISSUE THREAD

**Issue by ColemanTom** [cylc/cylc#2494]
In https://cylc.github.io/cylc/html/single/cug-html.html#9.6.1 it says:

>Zero-Padded Integer Values Integer parameter values are zero-padded according to the size of their largest value, so foo<p> for p = 9..10 expands to foo_p09, foo_p10.
>To get thicker padding, prepend extra zeroes to the upper range value: foo<p> for p = 9..010 expands to foo_p009, foo_p010. 

That seems to work, but, if you want to combine it with a parameter template (e.g. to remove the string `p`), the behaviour changes. I can't seem to figure out a nice way to zero pad my string, whilst removing the parameter name. I tried `%(p)03d`, but that doesn't work, as the docs say, it must be an `%s` string interpolation.

e.g. The below suite.rc fails. But, if you comment out the parameter templates, and then put an "n" in front of the 09, it works fine (i.e. use default behaviour).
```
[cylc]
    [[parameters]]
        n = 0..10
    [[parameter templates]]
        n = %(n)s
[scheduling]
    [[dependencies]]
        graph = """
prep => post_09 => stop
"""
[runtime]
    [[root]]
        script = """
n=${CYLC_TASK_PARAM_n:-}
[[ -n $n ]] && echo "parameter n is $n"
sleep 5"""
    [[prep, stop]]
    [[post<n>]]

-> 
cylc validate $(pwd) --strict
2017-11-24T13:10:20+11 WARNING - naked dummy tasks detected (no entry under [runtime]):
+	post_09
'ERROR: strict validation fails naked dummy tasks'

-> comment out parameter templates, and put an "n" in front of 09 (i.e. post_n09)
cylc validate $(pwd) --strict
Valid for cylc-7.5.0
```

Am I missing something and there is some nice way to zero pad a range of numbers using parameter templates, without needing to have the parameter name in front? I don't want to go down the route of:
```
[[parameters]]
    r_single = 0..9
    r_double = 10..99
    r_triple = 100..240
[[parameter templates]]
    r_single=00%(r_single)s
    r_double=0%(r_double)s
    r_triple=%(r_triple)s
```

NOTE: This used to work how I am wanting in Cylc 7.4.0, but must have been changed in Cylc 7.5.0. Would it be possible to get this functionality back (or is it already in 7.6.0?)?

**Comment by hjoliver** [comment]
@ColemanTom -

Firstly, your example suite above fails strict validation at 7.5.0 because the underscore in `post_09` does not conform to your template `%(n)s` (unlike the default template `_%(n)s`).

**Comment by hjoliver** [comment]
Secondly, padding: between 7.4. and 7.5 we changed to interpreting integer parameters as proper integers, rather than a list of strings. An unfortunate side effect of this that we missed at the time, was we lost the ability to add *extra* zero-padding e.g. 009..010 vs 09..10.   However, for normal zero padding to the width of the largest integer, I do not see the problem you report when overriding the default template.  E.g.:
```
[cylc]
    [[parameters]]
        n = 9..10
[scheduling]
    [[dependencies]]
        graph = "post<n>"
[runtime]
    [[post<n>]]
```
and
```
$ CYLC_VERSION=7.5.0 cylc list suite.rc 
post_n09
post_n10
```
Now override the default template with:
```
    [[parameter templates]]
        n = %(n)s
```
and I get:
```
$ CYLC_VERSION=7.5.0 cylc list suite.rc 
post09
post10
```

**Comment by hjoliver** [comment]
Finally, on current master (ready for 7.6.0) we have already implemented proper integer templating:
```
# (cylc-master)
    [[parameter templates]]
        n = %(n)05d
```
result:
```
$ cylc list suite.rc 
post00009
post00010
```

**Comment by hjoliver** [comment]
Also on **current master**, the job environment variables e.g. ```CYLC_TASK_PARAMETER_n``` are just plain integers (for integer parameters) that are not affected by the task name parameter templates - to avoid problems with shell octal interpretation - but you can also default and template your own parameter variables for job environments, e.g.:
```
        [[[parameter environment templates]]]
            MYFILE = /path/to/run%(run)03d/%(obs)s
```
This is all working and documented on the master branch.

**Comment by hjoliver** [comment]
I think we've got this covered, so I'll close the issue as invalid.  But feel to continue the conversation here or re-open if I've missed something important.
