### ISSUE TITLE
Document how to change GUI font-size

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc#2498]
For `cylc gui` and `cylc scan`.

If you're running a Gnome desktop, GTK apps should pick up your desktop font settings.

Or standalone, this should work (e.g.):

```
$ cat $HOME/.gtkrc-2.0
gtk-font-name = "URW Gothic 16"
```

**Comment by kinow** [comment]
We are now working [on the new Web GUI](https://github.com/cylc/cylc/issues/1873), which will replace the previous Desktop PyGTK GUI in our next major release of Cylc 8.

This issue is being closed for not being applicable to this new Web GUI.
