### ISSUE TITLE
cylc__job_finish (and cylc task message) 'priority' variable name

### ISSUE THREAD

**Issue by ColemanTom** [cylc/cylc#2500]
Hi,

I'm looking at https://github.com/cylc/cylc/blob/master/lib/cylc/job.sh#L176 and noticed that 'priority' is really a `severity`. I would suggest it should be renamed to `severity` to conform better with https://en.wikipedia.org/wiki/Syslog

It looks like this terminology persists throughout cylc-message and task_message.py, and I think they should all be updated to severity to better reflect what they are.

**Comment by ivorblockley** [comment]
I agree, if the `priority` relates to a log-level/message concept then `severity` (usually short for `severity-level`) is a more widely used convention.

**Comment by hjoliver** [comment]
@ColemanTom @ivorblockley - fair enough.  I was going to claim that I got "priority" from Python stdlib logging terminology in the early days of Cylc.  But even on looking back to earlier Python docs, it seems I was just plain wrong 😬

**Comment by ColemanTom** [comment]
Perhaps "level" or "log_level" would be appropriate if following the standard python library?

**Comment by hjoliver** [comment]
Originally this only affected logging in Cylc, but these days it has wider impact (event handling).  So I think "severity" is good ... and I see @matthewrmshin has already put up a pull request to do that (quick!!).
