### ISSUE TITLE
Current parameter deficiencies.

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc#2525]
For parameters `m = cat, dog`:

- [ ]  `graph = foo<m-1> & baz => foo<m>` generates `foo_cat & baz => foo_dog`, whereas it should generate `foo_cat => foo_dog` and `baz => foo_cat & foo_dog`.

- [x] `graph = foo<m> => foo<m-1>` fails strict validation because of a naked dummy task `foo_-32768`

The reason is: the `_REMOVE` regex in `param_expand.py:GraphExpander` is not sufficiently general. It assumes only out-of-range tasks together and only on the left side of a dependency.
  
  
- [x] we should also allow `foo<m+1>` for "next parameter value", like `foo<m-1>`

- [x] and negative integers: `-5..5` 

[credit @ColemanTom]

**Comment by hjoliver** [comment]
Pref. next release if we can do it.

**Comment by hjoliver** [comment]
Assigning @matthewrmshin on account of #2527

**Comment by hjoliver** [comment]
[two more points added to the description]

**Comment by matthewrmshin** [comment]
I have attempted to fix case 2, 3 and 4.

Case 1 is a bit more difficult, and really is quite a bad case to have to handle. (Syntax like this adds to confusion, and would be better off written as `baz => foo<m-1> => foo<m>`.)

**Comment by hjoliver** [comment]
> Case 1 is a bit more difficult, and really is quite a bad case to have to handle. (Syntax like this adds to confusion, and would be better off written explicitly as baz => foo<m> and foo<m-1> => foo<m>.)

Yes, but the fact is current behaviour is a pretty bad error - it wipes tasks out of the graph.  I guess we could just document it in the parameters section of the user guide, in lieu of a fix.

**Comment by hjoliver** [comment]
Items 2, 3, and 4 done (#2527)

**Comment by matthewrmshin** [comment]
Full fix of point 1 unlikely to make the next release.

**Comment by matthewrmshin** [comment]
Remaining issue moved to #2608.
