### ISSUE TITLE
Unable to get cylc to use PBS

### ISSUE THREAD

**Issue by puneet336** [cylc/cylc#2541]
I am trying to compile a weather science related application - OPS  on suse 12 under cray environment. I am familiar with configure & cmake based build systems but i am new to the rose/cylc suite - hence this query might be very "basic".

While trying to "build" i see that  "at" is selected as Batch scheduler, and i want to set PBS as the scheduler. I got hold of this documentation - 
https://cylc.github.io/cylc/html/single/cug-html.html#x1-440007.14

believing that with this file, i can override the "default" setting ,  i generated my own global.rc file as :

cylc get-site-config > $HOME/.cylc/global.rc
and added - "runtime" item (for PBS) as - 

```
    handler retry delays =
    mail to =
    submission timeout =
[runtime]
    [[my_task]]
        [[[job]]]
            batch system = pbs
[hosts]
    [[localhost]]
        retrieve job logs = False
        use login shell = True
```

now, when i run rose stem --task=fcm_make:ops_x86_64_ifort_opt  --new --name=test4, i get :

```
[INFO] create: etc
[INFO] install: etc
[INFO]     source: /home/user1/INSTALLATION_RELATED/01152018/MYOPS/trunk/rose-stem/etc
[INFO] create: app
[INFO] install: app
[INFO]     source: /home/user1/INSTALLATION_RELATED/01152018/MYOPS/trunk/rose-stem/app
[INFO] install: suite.rc
[INFO] REGISTER test4: /home/user1/cylc-run/test4
[INFO] WARNING: ignoring bad site config /home/user1/.cylc/global.rc:
[INFO] Illegal item: runtime
[INFO] WARNING: deprecated items were automatically upgraded in 'global config':
[INFO]  * (6.11.0) [state dump rolling archive length] - DELETED (OBSOLETE)
[INFO] WARNING: ignoring bad site config /home/user1/.cylc/global.rc:
[INFO] Illegal item: runtime
[INFO] 2018-01-16T06:39:01Z WARNING - task "OPS_SOURCE" not used in the graph.
[INFO] 2018-01-16T06:39:01Z WARNING - task "DELETE_X86_64" not used in the graph.
[INFO] 2018-01-16T06:39:01Z WARNING - task "OPS_X86_64_IFORT_OPT_NO_SCRIPT" not used in the graph.
[INFO] 2018-01-16T06:39:01Z WARNING - task "ROSE_ANA_OPS_X86_64_IFORT_OPT" not used in the graph.
[INFO] chdir: log/
[INFO] test4: will run on localhost
[WARN] WARNING: ignoring bad site config /home/user1/.cylc/global.rc:
[WARN] Illegal item: runtime
[INFO]             ._.
[INFO]             | |                 The Cylc Suite Engine [7.5.0]
[INFO] ._____._. ._| |_____.           Copyright (C) 2008-2017 NIWA
[INFO] | .___| | | | | .___|  _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
[INFO] | !___| !_! | | !___.  This program comes with ABSOLUTELY NO WARRANTY;
[INFO] !_____!___. |_!_____!  see `cylc warranty`.  It is free software, you
[INFO]       .___! |           are welcome to redistribute it under certain
[INFO]       !_____!                conditions; see `cylc conditions`.
[INFO]
[INFO] *** listening on elogin01:43005 ***
[INFO]
[INFO] To view suite daemon contact information:
[INFO]  $ cylc get-suite-contact test4
[INFO]
[INFO] Other ways to see if the suite is still running:
[INFO]  $ cylc scan -n '\btest4\b' elogin01
[INFO]  $ cylc ping -v --host=elogin01 test4
[INFO]  $ ssh elogin01 "pgrep -a -P 1 -fu $USER 'cylc-r.* \btest4\b'"
[INFO]
user1@login01:~/INSTALLATION_RELATED/01152018/MYOPS/trunk>
```
I can see in the warnings that runtime is not a valid item. 

and here is what i get in the /home/user1/cylc-run/test4/log/job/1/fcm_make_extract__ops_x86_64/01/job-activity.log

[jobs-submit ret_code] 0
[jobs-submit out] 2018-01-16T06:39:04Z|1/fcm_make_extract__ops_x86_64/01|0|8
2018-01-16T06:39:04Z [STDERR] Can't open /run/atd.pid to signal atd. No atd running?
2018-01-16T06:39:04Z [STDOUT] job 8 at Tue Jan 16 06:39:00 2018

What will be the suitable place to define the PBS batch scheduler and how?

**Comment by puneet336** [comment]
Hi,

I was able to specify the pbs as a batch scheduler in  file -  
./rose-stem/site/ncm/common/suite-families.rc

```
{# Included by: suite.rc #}
# Start: site/ncm/common/suite-families.rc
#------
# LINUX
#------
    [[LINUX]]
        script = "rose task-run -v"
        [[[environment]]]
            OPS_ODB_INSTALL_DIR = {{ OPS_ODB_INSTALL_DIR_DESKTOP|default("/gpfs2/home/indira/rani/odb") }}
            OPS_ODB2_INSTALL_DIR = {{ OPS_ODB2_INSTALL_DIR_DESKTOP|default("/gpfs2/home/indira/rani/odbapi") }}
        [[[job]]]
            batch system = pbs
        [[[remote]]]
#            host = {{ HOST_LINUX|default('`rose config rose-host-select group{rose-stem-linux} >/dev/null; if [[ $? == 0 ]]; then rose host-select --choice=3 rose-stem-linux; else rose host-select --choice=3 ncmlogin3; fi`') }}
            host = localhost
    [[ADMIN_X86_64]]
        inherit = LINUX

    [[DELETE_X86_64]]
        inherit = LINUX

    [[ROSE_ANA_X86_64]]
        inherit = ADMIN_X86_64

# End: site/ncm/common/suite-families.rc

```
Q- Was that the right place to define PBS ?. Could we not do this at someplace like -   $HOME/.cylc/global.rc ?


Now we need to specify a PBS template/jobs script having all necessary PBS directives. The job failed as submission to default queue is not allowed.  How could i define the template ? and where to put the template to that cylc can discover and use it.

We have 3 kinds of queues, so do i need to create 3 script for this case? If so then how would i instruct rose/cylc to select a specific queue?


```
user1@elogin01:~/cylc-run/test6/log/job/1/fcm_make_extract__ops_x86_64/01> cat job-activity.log
[jobs-submit cmd] cylc jobs-submit -- /home/user1/cylc-run/test6/log/job 1/fcm_make_extract__ops_x86_64/01
[jobs-submit ret_code] 173
[jobs-submit out] 2018-01-16T07:12:33Z|1/fcm_make_extract__ops_x86_64/01|173|None
2018-01-16T07:12:33Z [STDERR] qsub: Queue is not enabled
```

**Comment by hjoliver** [comment]
Hi @puneet336 - Cylc repository Issues are for bug reports and development discussions.  Usage questions should be directed to the Cylc forum on Google Groups (see the link here: https://cylc.github.io/cylc/support.html).   Sorry if that wasn't clear.  I'll close this Issue, but If you'd like to redirect your question to the forum we'll be glad to help out there!

**Comment by matthewrmshin** [comment]
Some quick comments any way.

In general, there is no need to generate a local `$HOME/.cylc/global.rc`. It is best to leave the file blank (or remove it) to allow you to pick up coded and/or site default settings.

https://github.com/cylc/cylc/issues/2199 discusses our proposal to improve cluster awareness. This is one of the issues I am keen to solve this calendar year.

https://cylc.github.io/cylc/html/multi/cug-htmlse11.html#11.1.5 has some examples of what you need to do to specify a queue for PBS. E.g.:

```cfg
[runtime]
    [[mytask]]
        [[[job]]]
            batch system = pbs
        [[[directives]]]
            -q = normal 
```

**Comment by hjoliver** [comment]
OK, since we're talking here anyway... @puneet336: On your question "is this the right place..." above, that is really a matter of suite design - specifically, the design of the rather complicated portable (multi-site) rose stem suite that you are trying to run, which is very "advanced" if you are new to Rose and Cylc.  To understand it better, you should start by reading the later sections of the Suite Design Guide https://cylc.github.io/cylc/documentation.html#suite-design-guide .  More generally, in lieu of #2199, we set the batch scheduler in every suite, but all commonality (e.g. common PBS directives) can be shared efficiently across tasks through the inheritance hierarchy.  And if you really have a lot of cross-suite commonality, you can put Jinja2 templates in include files, and include those in your suites - that's usually not worth the effort though because it's really only the highly task-specific PBS directives that are difficult (i.e. you don't gain all that much by not having to write "batch system = pbs" once (under [[root]], say) in each suite).
