### ISSUE TITLE
minor scan bugs?

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc#2544]
Noticed on our new HPC systems today:

- [x] gcylc Open Another Suite dialog show duplicate entries for running suites: one line with the port number, and one without as if the suite was not running
- [x] [invalid] ~~`cylc scan` appears to default to scanning no hosts, in spite of global.rc settings? (but works fine with hosts set explicitly on the command line)~~
- [x] (plus two minor bugs in gscan, addressed in #2542 #2543)

We launch suites with "rose suite-run" onto other Cylc VMs, in a shared filesystem environment.

I'll investigate tomorrow...

**Comment by matthewrmshin** [comment]
I'll have a quick look to see if I can repeat bullet point 1 in my environment.

**Comment by matthewrmshin** [comment]
(Just managed to repeat bullet point 1, and I can see why it is doing so in the logic. Sorry!)
