### ISSUE TITLE
bug in kill task job with retries configured

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc#2549]
Test case:
```
[scheduling]
    [[dependencies]]
          graph = foo
[runtime]
    [[foo]]
        script = sleep 30
        [[[job]]]
            execution retry delays = 3*PT10S
```
If `foo` fails internally (with different `script` than above, obviously) the task proxy goes to the `retrying` state prior to next retry - as expected.

But if I kill `foo` (with `cylc kill` or via the GUI), the task job gets killed, and the task proxy goes to the `held` state.  I'm not 100% sure, but I don't think this is the intended behavior!  What it should do is one of:
 1. go to `retrying`, prior to next retry (same as for an internal failure)
 2. or go to 'failed' on the basis that a manual kill might be intended to stop the retry sequence (and if not, a manual retrigger after a manual kill is reasonable).

I think 1. is current intended behavior, but it should really be 2. (for the reasons just given).  Either 1. or 2. is more sensible than `held`.

**Comment by hjoliver** [comment]
From a quick debug session, the incorrect held status is being set here:
https://github.com/cylc/cylc/blob/master/lib/cylc/task_state.py#L383-L386

For reasons that I have not had a chance to back-diagnose yet, the hold swap status of `foo` is "held" here, so that `_set_state("retrying")` results in setting the task state to `held`.

**Comment by hjoliver** [comment]
(Regarding 2. above - that may not be easy yet, if we don't have a mechanism in place to distinguish fail from kill at that point in the code).  See also #2394

**Comment by matthewrmshin** [comment]
(Kill-to-hold logic was introduced in #1313 for #1308.)

**Comment by hjoliver** [comment]
Ouch - I guess I don't run enough real suites myself anymore!

**Comment by matthewrmshin** [comment]
(You are not the only one!)

**Comment by hjoliver** [comment]
In light of that revelation, I think kill-to-hold is fine because (just tested) the task resumes the retry sequence if released, and can be reset to failed (skipping the retries) if necessary.  However it isn't exactly intuitive (two recent user reports motivated this ticket) and does not seem to be documented.  I'll remove the bug label and change the title to document the current behaviour where 'execution retry delays' are explained.  (And while we're at it, I see a few instances of the old top-task-level "retry delays" syntax that should be corrected in the CUG.

**Comment by hjoliver** [comment]
Scratch that, I'll close this as invalid, and put a new one up for documentation. Else this page will be confusing.
