### ISSUE TITLE
Parameter tasks and inheritance error message bug

### ISSUE THREAD

**Issue by ColemanTom** [cylc/cylc#2551]
Apologies if this already is covered in cylc 7.6.0 or another Issue, but I couldn't see this in my searches.

I'm suggesting this is a bug in the sense that the error message is not very useful. Whether this should be allowed as a feature is up to you, I would like it to be possible (otherwise I would not have encountered it).

```
[cylc]
    [[parameters]]
        obs = ship, buoy, metar
        n = 1..3
    [[parameter templates]]
        obs = o-%(obs)s
        n = n_%(n)s
[scheduling]
    [[dependencies]]
        graph = "a_<obs>_task => b_<n>_task => c_<n>_task<obs>"
[runtime]
    [[root]]
        script = "sleep 10"
    [[TASK<obs>]]
    [[TASK<n>]]
    [[a_<obs>_task]]
        inherit = TASK<obs>
    [[b_<n>_task]]
        inherit = TASK<n>
    [[c_<n>_task<obs>]]
        inherit = TASK<obs>, TASK<n>
```

When performing a `cylc validate` on this the output is:
```
cylc validate x.rc
'obs'
```

This is not a very useful error message. If I change the last task name to be `c_<n,obs>_task`, it validates perfectly. So if the error message said something about the problem being with the task name it would be handy. 

If I remove the inheritance it also appears to validate with the original task name.
```
[runtime]
    [[root]]
        script = "sleep 10"
    [[TASK<obs>]]
    [[TASK<n>]]
    [[a_<obs>_task]]
        inherit = TASK<obs>
    [[b_<n>_task]]
        inherit = TASK<n>
    [[c_<n>_task<obs>]]
```

**Comment by matthewrmshin** [comment]
On latest master, `cylc validate` will give you an error message that points to the `inherit = TASK<obs>, TASK<n>` statement. It is an improvement, but still wrong.

**Comment by matthewrmshin** [comment]
On latest master, `cylc validate` will give you an error message that points to the `inherit = TASK<obs>, TASK<n>` statement. The error looks more sensible, but is still wrong.
