### ISSUE TITLE
graph view of dependencies around a selected task

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc#2566]
(I think we've discussed this before but I haven't found a record of it).

This would make graph view more useful, even for very large suites: select a task (in any view) and open a graph view showing just that task and its immediate dependencies.

**Comment by oliver-sanders** [comment]
To be done with #1873? See https://github.com/cylc/cylc/issues/1873#issuecomment-330254260.

**Comment by hjoliver** [comment]
Yes, closing as a duplicate of #1086 and superseded by #1873.
