### ISSUE TITLE
suite design guide - add 'set -o pipefail' as recommended flag

### ISSUE THREAD

**Issue by ColemanTom** [cylc/cylc#2577]
I'm just skimming the suite design guide again as a refresher. I would like to suggest that in section 3.6.2, it should suggest to add `set -o pipefail` to shell scripts. See https://vaneyckt.io/posts/safer_bash_scripts_with_set_euxo_pipefail/ for some justification. Perhaps there are cases you don't want that, but I think it is safer to have that option set.

**Comment by hjoliver** [comment]
Agreed.  Do you want to put in a pull request? (the SDG is in the Cylc doc dir, in case that's not obvious).

**Comment by hjoliver** [comment]
(sorry - I see you already did!)

**Comment by ColemanTom** [comment]
Haha, yep. I thought, I should just do this, things don't get much simpler than this suggestion.
