### ISSUE TITLE
dynamic 'best fit' in GCylc's graph view

### ISSUE THREAD

**Issue by jonnyhtw** [cylc/cylc#2580]
As raised in the Cylc google group here...

https://groups.google.com/forum/#!topic/cylc/5Xm3Yyj8sjc

'Hi there

I've never managed to get the 'best fit' graph view keyboard shortcut to work and it's something that I use frequently. Is it possible to somehow automate this or invoke this from the command line?

Cheers

Jonny'

**Comment by kinow** [comment]
Hi,

This issue won't be fixed in the 7.8.x release series, and for Cylc 8 it may not be applicable due to the new Web GUI.

Is that alright to close it? I think I missed this one when doing the first sweep of issues.

**Comment by jonnyhtw** [comment]
Hey there

Yes no problem at all to close it.

Thanks for getting in touch.

Jonny
