### ISSUE TITLE
cylc scan now times out on [killed suites] empty ports?

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc#2611]
Now that we use content of `~/cylc-run/` to find the user's local suites, if a suite was killed leaving behind its contact file, `cylc scan` will hang until it times out (only 5 sec, thankfully) with:
```
$ cylc scan
WARNING, scan timed out, no result for the following:
  vagrant.vm:43084
```

Can we detect "dangling contact files" and avoid trying to connect to the associated port, by testing that the record PID still exists first?

**Comment by matthewrmshin** [comment]
Interesting. One would have thought that the call would simply die immediately if it is unable to connect. Why would it be hanging about?

**Comment by hjoliver** [comment]
I agree, I have not test what is actually happening yet...

**Comment by hjoliver** [comment]
I'm wondering if this is due to some kind of misconfiguration on my VM.  Now, with `cylc scan localhost` to force actual port scanning, it times out on all ports in the cylc range!
