### ISSUE TITLE
cylc gui tree view progress bar

### ISSUE THREAD

**Issue by matthewrmshin** [cylc/cylc#2632]
Reported by a user via email:

> In the absence of any suite events, how often should the textview be redrawing itself?
 
> I’m running a suite where there’s one task running and am looking at the progress bar ~15-20 mins in it hasn’t shifted. A change view and back updates it though.

**Comment by hjoliver** [comment]
As I vaguely recall, task progress bars do not update at all in the absence of suite events.  That's something I was aware of when doing the original implementation, but never got back to improving it.

**Comment by kinow** [comment]
We are now working [on the new Web GUI](https://github.com/cylc/cylc/issues/1873), which will replace the previous Desktop PyGTK GUI in our next major release of Cylc 8.

This issue is being closed for not being applicable to this new Web GUI.
