### ISSUE TITLE
GUI: unused view memory release?

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc#2633]
Noticed while monitoring GUI memory use with `top` on a large suite (1000 tasks): if I repeatedly add and remove a "View 2" panel, the resident memory size goes up significantly each time, but does not go down again when the view is removed.  Not sure if this a simply a high water effect with slow garbage collection, or if we're unnecessarily hanging on to a reference to the unused data structures...

**Comment by arjclark** [comment]
What view does adding view 2 add in for? We found something nasty with one of the views several years back whereby Python just doesn't release previously allocated memory (can't find the old bug report for it though, so perhaps it got consolidated into something else).

**Comment by hjoliver** [comment]
@arjclark - #1620 - PyGTK bug, graph view only.  This issues applies to any view in the GUI.

**Comment by kinow** [comment]
We are now working [on the new Web GUI](https://github.com/cylc/cylc/issues/1873), which will replace the previous Desktop PyGTK GUI in our next major release of Cylc 8.

This issue is being closed for not being applicable to this new Web GUI.
