### ISSUE TITLE
Redundant cylc version command?

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc#2634]
You can print version number with:
```
cylc -v
cylc --version
```
These are handled by `bin/cylc`; but we also have:
```
cylc version
```
which invokeds `bin/cylc-version` and has a `--long` option to print the executable path as well.

@cylc/core - does anyone recall why we have both of these?  Presumably we consolidate them into one.

**Comment by oliver-sanders** [comment]
I'm guessing this was to match `rose version --long`. The `--long` option is quite useful, especially when juggling development versions.

**Comment by hjoliver** [comment]
I agree it's useful, but do we need two distrinct implementations (only one of which supports the long option)


⁣Sent from BlueMail ​

**Comment by matthewrmshin** [comment]
I think we should consolidate the logic into `bin/cylc`.

**Comment by sadielbartholomew** [comment]
I agree that one implementation would be best, and a ``--version``/``-v`` option seems standard for software systems, so preferably consolidate into that.

**Comment by arjclark** [comment]
> I'm guessing this was to match rose version --long. The --long option is quite useful, especially when juggling development versions.

@oliver-sanders - yeah, `--long` had to be added for various reasons, ultimately down to needing to be able to tell what version of cylc you were actually using.

**Comment by matthewrmshin** [comment]
Looks like the long mode is already handled by `bin/cylc`. (It handles `cylc --version long` already. I'll make sure it can handle `cylc --version --long` as well. It should also handle `cylc version` automatically if we remove `bin/cylc-version`.)
