### ISSUE TITLE
job log database?

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc#2635]
A wild idea, to help cope with the vast numbers of job logs generated (in a rather verbose directory tree) by large long-running suites: could we write all job logs into a database instead of to disk as text files.  Systems that need to read job logs (rose bush, cylc cat-log, etc.) could read from the DB instead.

@cylc/core - we can close this issue if it is generally thought to be madness.

**Comment by hjoliver** [comment]
See #1159 for a less extreme solution (although that goes beyond job logs).

**Comment by matthewrmshin** [comment]
I think I prefer more aggressive housekeep. Even if it means putting job logs in a tar-gzip archive immediately after:
* the completion of a local job, or
* the completion of a remote job + logs retrieved.

Writing job logs in a tar-gzip archive should achieve the same goal here (if not better):
* We know that text logs compress well.
* A tar-gzip archive stores the path and the file metadata.
* It is more familiar to users.

**Comment by hjoliver** [comment]
Fair enough, I'll close this.  The only reason I can think of to favor the DB approach, aside from extreme inode economy, is that it is presumably - given support in the tools - easier to extract the right information from a DB than from an archive of gzipped tarballs.
