### ISSUE TITLE
small duplication in cylc_xdot.py and suite_srv_files_mgr.py

### ISSUE THREAD

**Issue by ColemanTom** [cylc/cylc#2647]
In cylc_xdot.py:
The methods `on_left_to_right`, `save_action` and `set_orientation` could probably be migrated into `CylcDotViewerCommon` instead of in `MyDotWindow` and `MyDotWindow2` individually as they are identical code. Unless there is a specific reason for them to exist in both classes independently which I did not see from a quick look.

In suite_srv_files_mgr.py:
```python
                if content:
                    value = self._load_local_item(item, path)
                else:
                    value = self._locate_item(item, path)
                if value:
                    return value
```
is repeated three times in quick succession - perhaps worth turning that into a method which takes content, item, path and returns the value?

This comes from a duplication scanner I just ran over the lib/cylc directories. There were a couple more things, but these were the ones I thought worth mentioning as the simplest modifications that could be made.

**Comment by matthewrmshin** [comment]
@ColemanTom please feel free to raise a PR for this sort of stuff.
