### ISSUE TITLE
cylc cat-log: do all remote processes die on exit?

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc#2664]
ref: https://github.com/cylc/cylc/pull/2662#issuecomment-389280352

@matthewrmshin - best to delay the release a bit for this too, if there is a problem.  I'm taking a look myself, but I may not get time to complete the job today, and you'll need to check at your site anyway.

**Comment by hjoliver** [comment]
**Solution?**

Could our `--host=<remote>` command re-invocation mechanism mimic the guts of the new `cylc cat-log`? wherein a remote tail process (on the job host) is now invoked as a sub-process of the remote `cylc cat-log` command which (as the top level remote process) kills it if its own PPID changes due to death of the parent ssh connection.

i.e. instead of `cylc blah --host=<remote>...` resulting in `ssh <remote> cylc blah ...`, it should result in `ssh <remote> cylc remote-cmd-wrapper blah ...`, where `cylc remote-cmd-wrapper` executes `cylc blah ...` as a subprocess and kills it if its own PPID changes.

This might occasionally be beneficial in other contexts too (e.g. if things go down during client command re-invocation in ssh based indirect task comms).

Questions: Is this the right thing to do, and if so, can it be implemented in time for 7.7.0?

**Comment by matthewrmshin** [comment]
I think this is the observed behaviour. I'll do a bit more test to confirm.

Alternate to your suggestion... We can introduce an option `--via-ssh` (or something like this) to `cylc cat-log` so we don't have to introduce a new wrapper command, but should be sufficient to alter the behaviour of `cylc cat-log` to know that it should kill itself if its SSHD is dead.

**Comment by matthewrmshin** [comment]
OK. Confirmed that `cylc gui --host=HOST SUITE` will invoke `cylc cat-log --host=HOST ...` - causing this issue. (That's why I have only able to observe this via suites launched by `rose suite-run`.)

**Comment by matthewrmshin** [comment]
(Rolling out a quick fix. I think it is safe, in general, if PPID becomes 1, we should just kill the `tail` command and exit `cylc cat-log`.)

**Comment by hjoliver** [comment]
Yes, that sounds fine.
