### ISSUE TITLE
Creating Cylc site and user global configuration files

### ISSUE THREAD

**Issue by sungeunbae** [cylc/cylc#2695]
I'm installing Cylc locally to give a test drive, and wonder if the instruction is still relevant?
https://cylc.github.io/cylc/html/multi/cug-htmlse6.html#x7-240006

$ cylc site global config file /opt/cylc/etc/global.rc
cylc site: unknown utility. Abort.

**Comment by hjoliver** [comment]
Hi @sungeunbae - I think you've mis-read the notation in the user guide at that point.  It is a comment `#` character, not a `$` representing a shell prompt.  The comment describes the file location that appears on the line after it.  Note also for a local installation, you may not need a global config file at all, unless you want to experiment with global settings (if by "local" you mean just a VM on your laptop or similar...).

I'll try make that part of the documentation a bit clearer!

(Note that the cylc forum on Google Groups is intended for usage questions like this).

**Comment by sungeunbae** [comment]
Thanks @hjoliver . I noticed "#" too, but some people use that for their prompt. The following sentence in the documentation led me to believe the file is to be auto-generated.

> 3.3.2 Create A Site Config File
> Site and user global config files define some important parameters that affect all suites, some of which may need to be customized for your site. **See 6 for how to generate an initial site file** and where to install it. All legal site and user global config items are defined in B.

**Comment by hjoliver** [comment]
Yes it can be auto-generated, just run "cylc get-global-config" and capture the result to a new file, then follow instructions about deleting all items that you don't need to change.   That is covered in the same page that you linked to above, but down a bit further.

Point taken on sometime use of `#` in shell prompts - I'll rethink our usage in a few parts of the user guide.
