### ISSUE TITLE
cylc-user-guide incorrect mv command in section 7.7

### ISSUE THREAD

**Issue by alanbchristie** [cylc/cylc#2707]
The command in the user guide tutorial (section 7.7, "Rename The Imported Tutorial Suites") appears wrong. Instead of: -

`mv ~/cylc-run/$(cylc --version)/examples/tutorial ~/cylc-run/tut`

The correct command appears to be: -

`mv ~/cylc-run/examples/$(cylc --version)/tutorial ~/cylc-run/tut`

**Comment by hjoliver** [comment]
@oliver-sanders - can you check the typo in Rose docs referred to above?

**Comment by oliver-sanders** [comment]
@alanbchristie Yep! Thanks for reporting this.
