### ISSUE TITLE
gui: job file viewer hangs

### ISSUE THREAD

**Issue by matthewrmshin** [cylc/cylc#2720]
This looks like another victim of the `cylc cat-log` kill logic. To reproduce:
* Start a suite with a local task.
* Open GUI.
* Right click task to view *any* job logs.
* Use drop down box to switch to another file to cause the GUI to hang.

The GUI appears to kill `cylc cat-log` OK, but both `timeout 3h tail ...` and `tail ...` commands are still alive and cause the `.wait()` call to hang the GUI.

🐱 log 🐛

**Comment by matthewrmshin** [comment]
Naively thinking that we would be on the safe side, we have prefixed our tail commands with `timeout 3h ...` in all our `global.rc`. It turns out that `timeout` puts itself and its children in its own process group, so this actually cause the `os.killpg` logic in `cylc.gui.tailer` to misbehave. It only kills `cylc cat-log` but not the `timeout 3h ...` and its child `tail` command.

Not a Cylc bug, but something that we need to be aware of!

**Comment by hjoliver** [comment]
Phew, good result.  `timeout` should not be needed with the new logic -  - I tested it pretty extensively.
