### ISSUE TITLE
gscan: not showing scanned hosts

### ISSUE THREAD

**Issue by oliver-sanders** [cylc/cylc#2731]
`gscan` is no longer showing the configured list of scanned hosts.

![screenshot-configure suite hosts](https://user-images.githubusercontent.com/16705946/42869922-5c0dadc4-8a6e-11e8-9d5b-53a6b082978d.png)
![screenshot-about cylc gscan](https://user-images.githubusercontent.com/16705946/42869923-5c363280-8a6e-11e8-873d-4700a627f5dc.png)

**Comment by matthewrmshin** [comment]
It does if you do `cylc gscan -a`. The default is that `hosts` is not set, so it uses the file system.

**Comment by dpmatthews** [comment]
OK. Perhaps we shouldn't worry about this then given that we're working on a replacement.

**Comment by hjoliver** [comment]
So this is not a bug, but it probably is confusing to most users. Maybe worth a little text to documentation in the dialog box?
