### ISSUE TITLE
cylc version with "git -C" requires newer version of git >= 1.8.5

### ISSUE THREAD

**Issue by dvalters** [cylc/cylc#2743]
Hi Cylc team, :wave: 

_(I hope you don't mind me opening an issue...feel free to move it to email if you think it's more appropriate)_

I'm currently upgrading from 7.6.1 -> 7.7.2, but I notice the way the version is now determined in the `bin/cylc` command is slightly different and uses this `git -C` syntax (if you are installing from a repository clone), which is not supported on older versions of git **< 1.8.5** ~(I couldn't pinpoint the exact version of git where this changes, but it fails on v1.8.3.1)~ (Yes I know...it's ancient `git`, but I can't change it on site unfortunately)

I think older and newer `git` versions can both be supported with a fairly minor change to the `cylc` script (using `--git-dir` instead of `git -C`), unless there are other reasons for using `git -C` that I might have missed?

Edit: the full output is:

```
[dvalters@someplace]$ cylc --version
Unknown option: -C
usage: git [--version] [--help] [-c name=value]
           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]
           [-p|--paginate|--no-pager] [--no-replace-objects] [--bare]
           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]
           <command> [<args>]
No version is set, cylc must be built first. Aborting...
```

**Comment by dvalters** [comment]
The change would be:
```diff
@@ -27,8 +27,8 @@ get_version() {
         CYLC_VERSION="$(cat "${CYLC_DIR}/VERSION")"
     # Otherwise, use git (if in a git repo and not a bare clone)
     # to determine version
-    elif git -C "${CYLC_DIR}" rev-parse && \
-            [[ -n "$(git -C "${CYLC_DIR}" rev-parse --show-toplevel)" ]]; then
+    elif git --git-dir "${CYLC_DIR}/.git" rev-parse && \
+            [[ -n "$(git --git-dir "${CYLC_DIR}/.git" rev-parse --show-toplevel)" ]]; then
         CYLC_VERSION="$(cd "${CYLC_DIR}" && git describe --abbrev=4 --always)"
         # Append "-dirty" if there are uncommitted changes.
         if [[ -n "$(cd "${CYLC_DIR}" && git status \
```

**Comment by matthewrmshin** [comment]
Hi @dvalters Do you want to raise a PR with your diff?

**Comment by oliver-sanders** [comment]
My bad (#2721)! Thanks for posting a fix.
