### ISSUE TITLE
Mismatch between graph example text and graphics in user guide

### ISSUE THREAD

**Issue by MartinDix** [cylc/cylc#2747]
There are a couple of mismatches between the image and text in the graph examples at 
http://cylc.github.io/cylc/html/multi/cug-htmlse9.html#9.3.3

For figs 21 and 22 the text says ```qux``` but image shows ```waz```.

For consistency with Fig 23, the image should probably be changed to ```qux``` rather than vice-versa.

**Comment by wxtim** [comment]
[PR2874](https://github.com/cylc/cylc/pull/2874/files) has been created for this issue. I have also commented on #2651 with some thoughts raised whilst doing this.
