### ISSUE TITLE
registration command line arg order

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc#2758]
Correct arg order is `cylc reg <NAME> <PATH>` 

(Note that suite names can be hierarchical with a `/` delimiter, which can make it difficult to determine if the arg is meant to be a name or a directory path!).

Accidental arg reversal `cylc reg <PATH> <NAME>` causes problems:
 1. if `<NAME>` happens to be an existing suite source directory, this will register that suite with the name `<PATH>` (with run dir `~/cylc-run/<PATH>`)
 2. otherwise, if `<NAME>` is not an existing suite source directory, registration will appear to succeed, but the suite service directory will be created inside the source directory and nothing happens under `~/cylc-run`.

**Comment by hjoliver** [comment]
(companion to #2749?)

**Comment by hjoliver** [comment]
Case 2. above is definitely an error.

Case 1. can only be detected as an error if we assume that the first argument (which is supposed to be the suite name) is not an existing directory path... which probably isn't a reasonable assumption. E.g. the follow should be alllowed:
```
$ vim nwp/one/suite.rc
$ cylc reg nwp/one nwp/one
```

**Comment by matthewrmshin** [comment]
> (companion to #2749?)

Most likely. As `cylc run` now automatically calls the underlying logic of `cylc register` on demand.

**Comment by hjoliver** [comment]
@cylc/core - just wondering if we ever rely on the ability to pre-register a suite directory that doesn't exist yet?  If the suite source dir has to exist already, that's an easy way to avoid case 2 above.

**Comment by hjoliver** [comment]
If we can demand that a suite directory already exists, *and* that it must already contain a `suite.rc` file, then accidental arg reversal could be detected and corrected automatically.

**Comment by hjoliver** [comment]
Proposal: I'll implement as per previous comment  (i.e. the `<PATH>' arg must exist and contain a `suite.rc` file) tomorrow unless I get any objections over night...

**Comment by matthewrmshin** [comment]
Sounds OK.

**Comment by hjoliver** [comment]
(removed bug label - this is just about handling a user error better)
