### ISSUE TITLE
Exiting from cylc monitor with CTRL-C could be more graceful

### ISSUE THREAD

**Issue by jarich** [cylc/cylc#2762]
There's probably a nice way to exit cylc monitor, but I'm not sure what it is, so I hit ctrl-C.  This works, but I tend to get a python backtrace, which may be avoidable if a SIG-INT handler was set via the signal library, or catching the KeyboardInterrupt exception as required.

This is most obvious when one attempts to monitor a suite that is not running. 

```
[jacintar@server ]$ cylc monitor consumer
ERROR Contact info not found for suite "consumer", suite not running?
ERROR Contact info not found for suite "consumer", suite not running?
ERROR Contact info not found for suite "consumer", suite not running?
ERROR Contact info not found for suite "consumer", suite not running?
^CTraceback (most recent call last):
  File "cylc/cylc-7.5.0-ext/bin/cylc-monitor", line 269, in <module>
    SuiteMonitor().run()
  File "cylc/cylc-7.5.0-ext/bin/cylc-monitor", line 140, in run
    sleep(float(options.update_interval))
KeyboardInterrupt
```

Likewise when suite runs, and then ends, you see this behaviour too:

```
runaheadwaitingheldqueuedreadyexpiredsubmittedsubmit-failedsubmit-retryingrunningsucceededfailedretrying
updated: 2018-08-23T01:33:41Z
state summary: 3  1 
_________________________________________________________________________________________s_t_o_p_p_i_n_g
2015 forecast
ERROR Cannot connect: https://<server:port>/get_suite_state_summary: suite "producer" already stopped
ERROR Contact info not found for suite "producer", suite not running?
ERROR Contact info not found for suite "producer", suite not running?
ERROR Contact info not found for suite "producer", suite not running?
^CTraceback (most recent call last):
  File "cylc/cylc-7.5.0-ext/bin/cylc-monitor", line 269, in <module>
    SuiteMonitor().run()
  File "cylc/cylc-7.5.0-ext/bin/cylc-monitor", line 140, in run
    sleep(float(options.update_interval))
KeyboardInterrupt
```

**Comment by jarich** [comment]
I know there's no official version called ``cylc-7.5.0-ext``.  This is a clone of @hjoliver 's x-triggering code that I've been testing.  I don't think this minor lack of gracefulness of cylc monitor is related to those changes.

**Comment by hjoliver** [comment]
@jarich - fair point! `cylc monitor` is, I would say, effective but utterly unsophisticated (about 100 lines of code that simply constructs a string, prints it to the terminal, then clears the screen; then repeat ad infinitum).  One day I'd like to rewrite it: #1685.  For this issue, catching SIGINT in the main loop should be pretty easy - I don't suppose you want to raise a Pull Request?

**Comment by hjoliver** [comment]
Also, no - there is no nice way to exit!  (that needs doing too ... hit 'q' maybe).

**Comment by jarich** [comment]
If I get the chance, I'll definitely have a go at fixing it.  It's not an unwillingness, just time, as you no doubt understand.

**Comment by hjoliver** [comment]
Yes, I do no doubt understand :grimacing:

**Comment by hjoliver** [comment]
OK, I took a look, the graceful exit on Ctrl-C is pretty trivial.  Clean exit on a key-press (like 'q') is another matter, somewhat surprisingingly - but probably isn't necessary as the command help says to exit with Ctrl-C.
