### ISSUE TITLE
xtrigger name to sub-process environment?

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc#2774]
Request from BoM users:
> Adding the Cylc trigger name to the environment where the triggger checking code runs would be useful for debugging.

**Comment by hjoliver** [comment]
> While debugging some external trigger issues, using Jacinta's HandleEvent code and our ~7.5.0 external trigger Cylc version, we noticed that perhaps any logging output from the external trigger handlers is interleaved in the Suites error output (suite.err) file, when more that one trigger is being checked.

> We dumped the environment of the external handler, and noted that there was no identifying info (like task name, suite name etc)

> Would it possible to add the Cylc trigger name to the environment that is set up to run the external trigger checks? This could be used along with some line number logging as per the attached card andwould be quite useful.

**Comment by hjoliver** [comment]
I've thought about this, and discussed with the BoM people.  By xtrigger "name' we mean the label used to represent the xtrigger in the graph, not the xtrigger function name.   Cut 'n paste from my post to the BoM project Trello board:

===

Consider this trigger definition:
```
[[xtriggers]]
    label1 = func_name1(args1...)
```
You want the label label1 (a.k.a. the "trigger name" in the graph) to be accessible inside the function func_name, for use in logging - is that right?

The problem is, cylc keeps track of xtrigger calls (to avoid unnecessary concurrent or repeat calls to the same function) by function signature - i.e. by function name and args - not by label. Different labels would normally be associated with different function signatures, but not necessarily. Two xtriggers with different labels could coalesce into a single function call depending on Jinja2 inputs to the suite, for instance, at least in principle. So there might not be a unique label per function call.

However, you are free define whatever args you like for xtrigger functions, so if your function logs information with identifying info I suggest you pass that in as an addtional argument. E.g.:
```
[[xtriggers]]
     x1 = search_for_match(log_id="analysis", match_string="analysis",...)
     x2 = search_for_match(log_id="forecast", match_string="forecast",...)
```
(or you could just have your logging extract whatever is unique from the other args, of course).

(just be aware that this new arg would result in two unique function signatures - and therefore separate calls - if they were not already unique ... however in your use case - and probably in most - they are unique anyway).

===

So. ... this issue can be closed with a bit of extra user guide documentation, to explain the above info clearly.

**Comment by hjoliver** [comment]
(And marking as invalid, relative to the original description).

**Comment by matthewrmshin** [comment]
Can this be closed if it is _invalid_?

**Comment by hjoliver** [comment]
Yes, I think so.
