### ISSUE TITLE
Traceback restarting simulation mode suite

### ISSUE THREAD

**Issue by oliver-sanders** [cylc/cylc#2788]
Suites run in simulation mode will crash if stopped with `--now --now` and restarted:

```
cylc run $SUITE_NAME --mode=simulation
sleep 5
cylc stop $SUITE_NAME --now --now
sleep 5
cylc restart $SUITE_NAME --mode=simulation
```

Example traceback:

```
2018-10-09T08:29:30Z CRITICAL - Traceback (most recent call last):
	  File "cylc/lib/cylc/scheduler.py", line 243, in start
	    self.configure()
	  File "cylc/lib/cylc/scheduler.py", line 394, in configure
	    self.load_tasks_for_restart()
	  File "cylc/lib/cylc/scheduler.py", line 462, in load_tasks_for_restart
	    self.pool.load_db_task_pool_for_restart, self.options.checkpoint)
	  File "cylc/lib/cylc/rundb.py", line 745, in select_task_pool_for_restart
	    callback(row_idx, list(row))
	  File "cylc/lib/cylc/task_pool.py", line 367, in load_db_task_pool_for_restart
	    itask.task_owner, itask.task_host = user_at_host.split(
	AttributeError: 'NoneType' object has no attribute 'split'
```

Sadly it's not as trivial as just fixing `lib/cylc/task_pool.py#367` as `NoneType` errors will crop up elsewhere in the `TaskPool` as well.

**Comment by hjoliver** [comment]
Hmm, possibly never tried restarting a sim mode suite (my fault, I expect).

**Comment by matthewrmshin** [comment]
Looking at the logic. This is the only value from table `task_jobs` that is used in such a way. All others are protected by `if value:` blocks. The block surrounding the problematic value already catches `ValueError`, so it can catch `AttributeError` as well.

(The key to trigger this bug is to have a task in the submitted or running state on shutdown.)

**Comment by matthewrmshin** [comment]
(Very easy to fix, but not easy to write a test.)
