### ISSUE TITLE
Fixed anchor names in the html cylc user guides.

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc#279]
Rose documentation has direct links into the html user guides on cylc gh-pages.  The internal anchor names generated by ```htlatex``` are nasty and may be (?) subject to change without notice on re-processing after changes to the document source files.

A bit of googling suggests it may be possible to configure htlatex to use the source reference labels as html anchors, in which case it won't be necessary to insert anything extra (e.g. via the hyperref package?) into the document source...

**Comment by matthewrmshin** [comment]
@benfitzpatrick thinks this should now be closed, since #1125 has mostly addressed the issue.
