### ISSUE TITLE
multi-line selection in cylc dbviewer

### ISSUE THREAD

**Issue by cylc** [cylc/cylc#28]
The gcylc suite database viewer currently allows only single line selections (i.e. a single suite or a single group of suites). This means we cannot, via the GUI, operate on multiple suites at once unless we operate on all members of a common group  (command line database operations allow selection of target suites by pattern matching, e.g. all suites starting with the word "test"). 

It would be good to allow multiple individual suites or groups to be selected at once without regard for their position in the registration hierarchy.  And for operations such as copying a suite from one group to another, it would be more intuitive to select the source suite and target group, than to select the source suite and then supply the target group name via dialog box as is done currently. 

This should be simple to implement, but would require some additional logic to check that the selections are appropriate to the chosen operation, and to position all selected suites and/or groups properly on the command line of the subprocess that carries out the operation.

**Comment by hjoliver** [comment]
Closing this, it is not really relevant any more.
