### ISSUE TITLE
Simultaneous message events not handled.

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc#2806]
If N message events occur at ~same time - whether by a single invocation of `cylc message` or N separate invocations - only the first gets handled (as in, passed to a configured event handler).

Example:
```
[scheduling]
   [[dependencies]]
      graph = foo
[runtime]
   [[foo]]
      script = """
cylc message -s WARNING -- ${CYLC_SUITE_NAME} ${CYLC_TASK_JOB} "cat"
#sleep 1
cylc message -s WARNING -- ${CYLC_SUITE_NAME} ${CYLC_TASK_JOB} "dog"
#sleep 1
cylc message -s WARNING -- ${CYLC_SUITE_NAME} ${CYLC_TASK_JOB} "fish"
#sleep 1
      """
      [[[events]]]
        handler events = warning
        handlers = echo "HANDLED %(message)s"
```

Run this.  The messages are all logged:
```
$ cylc cat-log foo | grep WARNING
2018-10-17T19:58:31+13 WARNING - [foo.1] -(current:running)> cat at 2018-10-17T19:58:30+13
2018-10-17T19:58:31+13 WARNING - [foo.1] -(current:running)> dog at 2018-10-17T19:58:31+13
2018-10-17T19:58:32+13 WARNING - [foo.1] -(current:running)> fish at 2018-10-17T19:58:31+13
```
But only the first gets handled:
```
$ cylc cat-log -f a foo foo.1 
[jobs-submit ret_code] 0
[jobs-submit out] 2018-10-17T19:58:30+13|1/foo/01|0|18342
2018-10-17T19:58:30+13 [STDOUT] 18342
[(('event-handler-00', 'warning'), 1) cmd] echo "HANDLED cat"
[(('event-handler-00', 'warning'), 1) ret_code] 0
[(('event-handler-00', 'warning'), 1) out] HANDLED cat
```

However, if I uncomment the `# sleep 1`s above, they all get handled:
```
$ cylc cat-log -f a foo foo.1
[jobs-submit ret_code] 0
[jobs-submit out] 2018-10-17T20:06:31+13|1/foo/01|0|19488
2018-10-17T20:06:31+13 [STDOUT] 19488
[(('event-handler-00', 'warning'), 1) cmd] echo "HANDLED cat"
[(('event-handler-00', 'warning'), 1) ret_code] 0
[(('event-handler-00', 'warning'), 1) out] HANDLED cat
[(('event-handler-00', 'warning'), 1) cmd] echo "HANDLED dog"
[(('event-handler-00', 'warning'), 1) ret_code] 0
[(('event-handler-00', 'warning'), 1) out] HANDLED dog
[(('event-handler-00', 'warning'), 1) cmd] echo "HANDLED fish"
[(('event-handler-00', 'warning'), 1) ret_code] 0
[(('event-handler-00', 'warning'), 1) out] HANDLED fish
```
(Interestingly the final `sleep 1` is required too, even with `foo => bar` so that the suite doesn't shut down immediately after foo runs).

**Comment by hjoliver** [comment]
This is a fairly serious bug that I think needs fixing by next release.

**Comment by matthewrmshin** [comment]
I'll take a look at this today.

**Comment by hjoliver** [comment]
(I suspect my `sleep 1` interval above just needs to be longer than that taken by event handler execution).

**Comment by matthewrmshin** [comment]
The work around is to send a single multi-line message (require >7.7.0):

```sh
cylc message -s WARNING -- ${CYLC_SUITE_NAME} ${CYLC_TASK_JOB} <<'__STDIN__'
cat
dog
fish
__STDIN__
```

**Comment by hjoliver** [comment]
@matthewrmshin - after a look at the code, it seems we're assuming (for a given task job) in-process events are uniquely identified by event type and name. However, here we have a bunch of events at once with same type and name, just different message values.

This quick hack seems to fix the bug, but I'm not sure if it has any bad side-effects:
```diff
diff --git a/lib/cylc/task_events_mgr.py b/lib/cylc/task_events_mgr.py
index 39a1b2246..cd7db929d 100644
--- a/lib/cylc/task_events_mgr.py
+++ b/lib/cylc/task_events_mgr.py
@@ -819,7 +819,7 @@ class TaskEventsManager(object):
             retry_delays = [0]
         # There can be multiple custom event handlers
         for i, handler in enumerate(handlers):
-            key1 = ("%s-%02d" % (self.HANDLER_CUSTOM, i), event)
+            key1 = ("%s-%02d" % (self.HANDLER_CUSTOM, i), event, message)
             id_key = (
                 key1, str(itask.point), itask.tdef.name, itask.submit_num)
             if id_key in self.event_timers:
```

**Comment by hjoliver** [comment]
(sorry, same event name and handler, not event type and name)

**Comment by hjoliver** [comment]
I don't think I agree with your workaround.  The handler would only be invoked once, and would have to know the message is really N different messages joined on newline.

**Comment by matthewrmshin** [comment]
Looks like the system only allows one unique event at a time - and the events are all have "warning" as their keys (in a dict). Oops. We should include the message as part of the key - at least for custom messages.

Related question. If a message is a registered task output (`trigger=message`), should it be possible for `trigger` to be used as the event string - so it can be handled as a separate event?

**Comment by matthewrmshin** [comment]
(Looks like we were typing at the same time.)

**Comment by hjoliver** [comment]
And note that sending 3 separate messages with a single `cylc message` does not work (like your example, but with blank lines in between).

**Comment by matthewrmshin** [comment]
(Note: My example should send one multi-line message as opposed to multiple messages.)

**Comment by hjoliver** [comment]
(yes, that's what I'm disagreeing with as a workaround - because the handler has to be modified to expect that).

**Comment by hjoliver** [comment]
> Related question. If a message is a registered task output ...

Trying to get my head around this... do you mean, should there be an event associated with a normal-severity task output message?

**Comment by hjoliver** [comment]
(over 'n out for the night here ...)

**Comment by matthewrmshin** [comment]
No problem. I'll find a fix for the dict key issue this afternoon.

For the related question, I want to be able to support this:

```
[runtime]
    [[t1]]
        script="""
cylc message -- ${CYLC_SUITE_NAME} ${CYLC_TASK_JOB} 'Hello World'
# Time passes...
cylc message -- ${CYLC_SUITE_NAME} ${CYLC_TASK_JOB} 'Greeting Earthlings'
"""
        [[[outputs]]]
            hello = Hello World
            greet = Greeting Earthlings
        [[[events]]]
            handler events = hello, greet  # ... and so on
            handlers = echo %(message)s

**Comment by hjoliver** [comment]
(Thanks much - in advance - for doing the fix BTW)
