### ISSUE TITLE
cylc jobs-submit gets stuck on submitting several hundred jobs

### ISSUE THREAD

**Issue by matthewrmshin** [cylc/cylc#2857]
The job submission logic batches up ready to submit jobs by their job hosts (mainly to reduce the number of SSH connections). The jobs are submitted sequentially by the `cylc jobs-submit` command that prints to STDOUT to communicate the status of each submitted job back to the suite server program. The is OK until we have a large number of jobs - resulting in a large amount of STDOUT, which appears to hang the `subprocess.Popen.stdout` file handle - causing the `subprocess.Popen.poll` method to always return `None`.

https://github.com/cylc/cylc/blob/337f0938720d8210b1dfaeb430c105a824da97df/lib/cylc/subprocpool.py#L143-L148

The suite server program will therefore think that the subprocess is hanging, and will kill it after 10 minutes - causing task statuses to go funny.

The problem can be fixed by 2 solutions:
* Throttle each `cylc jobs-submit` command to handle a maximum of, say, 100 jobs.
* Handle subprocess communication with a lower level logic:
  * Use `select` to poll readability of `subprocess.Popen.stdout` (and `subprocess.Popen.stderr`).
  * Read the pipes directly when they are available for reading.

**Comment by matthewrmshin** [comment]
(To make matter worse, users can trigger stuffs in panic mode, and get themselves in the situation documented in #2621.)

**Comment by wxtim** [comment]
I had a look at the possibility of using `select` to deal with the pipe but wasn't able to get this working. After spending several hours on it @matthewrmshin suggested looking at throttling the list of jobs submitted at once and this is the approach looked at in my PR #2870 . 

Do we need a new ticket to deal with the underlying PIPE problem, lest it cause some other issue later?

**Comment by hjoliver** [comment]
> Do we need a new ticket to deal with the underlying PIPE problem, ...

Not in my opinion.  Throttling seems fine to me, and much simpler, and I'm not aware of any other context in which we're likely to run into the "underlying PIPE problem".

**Comment by matthewrmshin** [comment]
The pipe buffer problem should still be tackled. I'll probably give it a go - I have just the logic in Perl for `fcm make` to capture long compiler outputs. We just need to translate this logic to Python: https://github.com/metomi/fcm/blob/b0954e36e035212c6119e6ab8f7d9541cbb357bb/lib/FCM/Util/Shell.pm

Note otherwise:
* We still need to throttle poll and kill the same way as submit.
* The `mail` command for event mail should be OK.
* The `rsync` command for remote job log retrieval should be OK, unless it is in verbose mode.
* User defined event handler commands may write too much data to STDOUT/STDERR.

**Comment by hjoliver** [comment]
(we could throttle the other commands too ... but OK)

**Comment by matthewrmshin** [comment]
The last item in the above list is the one that I am most worried about - as we have no control. A user defined event handler command can potential get stuck because it is writing too much output.

**Comment by hjoliver** [comment]
We don't batch multiple event handlers within a single subprocess, unlike the `cylc xxx` commands. But yes, they could potentially generate a lot more output.
