### ISSUE TITLE
Replace pipes.quote by shlex.quote when Py3

### ISSUE THREAD

**Issue by kinow** [cylc/cylc#2864]
We have `from pipes import quote` in a few parts of the code. But the `pipes` module exports in `__all__` only` Template`. The `quote` method was supposed to be internal, but probably due to it being useful, now it is exported/documented in `shlex.quote`, but I believe it's Py3 only

So when moving to Py3, `2to3`/`six`/`futurize` won't alert us about that, and so this ticket as a remainder 😬

**Comment by kinow** [comment]
Found this while reviewing #2809 and finding the pipes.quote usage, which was new for me 🤓

**Comment by oliver-sanders** [comment]
Python unhelpfully deprecated `pipes.quote` in 2.7 but diddn't expose it again until `3.3`!

**Comment by kinow** [comment]
Had no idea that that's what happened hahaha. Bet they got a few angry users demanding a replacement
