### ISSUE TITLE
Cylc Tutorial Problems

### ISSUE THREAD

**Issue by mwolffe** [cylc/cylc#2891]
Hi,

I am a new cylc user and am currently working through the cylc tutorials found here: https://metomi.github.io/rose/doc/html/tutorial/cylc/runtime/runtime-configuration.html

I am having issues with the cylc run and repeatedly get the below error:
Traceback (most recent call last):
  File "/home/mike/.local/cylc/bin/cylc-run", line 31, in <module>
    main(is_restart=False)
  File "/home/mike/.local/cylc/lib/cylc/scheduler_cli.py", line 64, in main
    scheduler = Scheduler(is_restart, options, args)
  File "/home/mike/.local/cylc/lib/cylc/scheduler.py", line 119, in __init__
    self.suite_srv_files_mgr.register(self.suite, options.source)
  File "/home/mike/.local/cylc/lib/cylc/suite_srv_files_mgr.py", line 452, in register
    self._get_ssl_cert(srv_d, pkey_obj)
  File "/home/mike/.local/cylc/lib/cylc/suite_srv_files_mgr.py", line 488, in _get_ssl_cert
    host = get_host()
  File "/home/mike/.local/cylc/lib/cylc/hostuserutil.py", line 221, in get_host
    return HostUtil.get_inst().get_host()
  File "/home/mike/.local/cylc/lib/cylc/hostuserutil.py", line 145, in get_host
    self._host = self._get_host_info()[0]
  File "/home/mike/.local/cylc/lib/cylc/hostuserutil.py", line 119, in _get_host_info
    self._host_exs[target] = socket.gethostbyname_ex(target)
socket.gaierror: [Errno -2] Name or service not known

I wonder if anyone else might have a fix for this problem?

many thanks
Mike

**Comment by kinow** [comment]
Mike, I wonder if you have

```
 [[[remote]]]
   host = computehost
```

Or another value in your configuration? I think Cylc could be using that value to try to SSH to the host... if so try changing to a valid host or removing it to run locally.

HTH,
Bruno

**Comment by matthewrmshin** [comment]
(We need to quickly solve #2875 to give us more info.)

**Comment by matthewrmshin** [comment]
Looks like it is failing to get host information of the current host?

Can you try running this Python snippet? Does it fail?

```python
import socket
print(socket.getfqdn())
print(socket.gethostbyname_ex(socket.getfqdn()))
```

**Comment by hjoliver** [comment]
Actually, looking at the files in the traceback above, it appears that "host or service not known" refers to the suite host - i.e. the host where you are trying to run the suite.  Cylc tries to get the local host name to use in the self-signed SSL certificate used for client-server communications.   This suggests (probably, I think) something wrong with the network configuration on your system.  You can call the same Python function yourself, to get the hostname - what does this return for you?:
```
oliverh@wizard$ PYTHONPATH=<cylc-dir>/lib python  # <--- substitute your <cylc-dir> here
Python 2.7.15rc1 (default, Nov 12 2018, 14:31:15) 
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from cylc.hostuserutil import HostUtil
>>> HostUtil.get_inst().get_host()
'wizard'  # <--- result
```

You should be able to (e.g.) `ping` or `ssh` to the result if it's a valid hostname for your suite host.  If not, make check your `/etc/hosts`?

**Comment by hjoliver** [comment]
(Sorry, missed your comment above @matthewrmshin - we're coming at the some problem from different angles).

**Comment by hjoliver** [comment]
> python is not detecting the cylc modules if I run it this way, just giving the below output:

You just have to set your PYTHONPATH as I've described above, before starting the Python interactive interpreter.

**Comment by hjoliver** [comment]
(however, I think your response to @matthewrmshin's example show's the expected problem anyway...)

**Comment by mwolffe** [comment]
@hjoliver Sorry, this is what it outputs when the path is set properly:

[mike@minerva fcm_make]$ PYTHONPATH=/home/mike/.local/cylc/lib python
Python 2.7.15 |Anaconda, Inc.| (default, Oct 23 2018, 18:31:10) 
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from cylc.hostuserutil import HostUtil
>>> HostUtil.get_inst().get_host()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mike/.local/cylc/lib/cylc/hostuserutil.py", line 145, in get_host
    self._host = self._get_host_info()[0]
  File "/home/mike/.local/cylc/lib/cylc/hostuserutil.py", line 119, in _get_host_info
    self._host_exs[target] = socket.gethostbyname_ex(target)
socket.gaierror: [Errno -2] Name or service not known

**Comment by hjoliver** [comment]
Yes, same problem.  Back to the Python standard library (not Cylc) functions, you should get something like this:
```
>>> import socket
>>> print(socket.getfqdn())
wizard
>>> print socket.gethostbyname_ex(socket.getfqdn())
('wizard', [], ['10.0.2.15'])
```
If not, there must be some network configuration error on your machine (I think).

**Comment by mwolffe** [comment]
Yes, it's returning the same problem.

>>> import socket
>>> print(socket.getfqdn())
minerva
>>> print socket.gethostbyname_ex(socket.getfqdn())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
socket.gaierror: [Errno -2] Name or service not known

Will have to have a look into my network configuration, thank you.

**Comment by hjoliver** [comment]
@mwolffe - I'll close this as I'm pretty sure it's not a Cylc bug.  Note for support issues we have the Cylc forum on Google Groups (we try to keep GitHub Issues for well-defined developments and bugs ... although I know the distinction is not always clear!).
