### ISSUE TITLE
Cylc Review WSGI script not a callable?

### ISSUE THREAD

**Issue by kinow** [cylc/cylc#2896]
The docs currently point to use `review.py` as the WSGI script. But that script has only a class, used by CherryPy.

The WSGI application callable is actually in `bin/cylc-review`. I think `cylc-review` is to [`rose/bush`](https://github.com/metomi/rose/blob/master/lib/python/rose/bush.py).

Perhaps we should move the main method to `review.py`, and call the module as in [`rose/rose-bush`](https://github.com/metomi/rose/blob/master/bin/rose-bush)? Haven't thought much about it, just realized it while trying to set up Nginx + WSGI (which works, by the way, for Cylc Review).

**Comment by kinow** [comment]
A quick way to test it too:

```bash
uwsgi --plugins python,http --need-app --enable-threads --uid uwsgi --pythonpath /opt/cylc/lib/ --wsgi-file /opt/cylc/bin/cylc-review --http :3031
```

That starts the bundled HTTP server, running the WSGI application provided via `--wsgi-file`. Just need [`uwsgi`](https://uwsgi-docs.readthedocs.io/en/latest/) and its Python plug-in package under Ubuntu.

**Comment by hjoliver** [comment]
As a quick fix to close this, I'm going to fix the docs.  Is that OK with you @kinow (you had assigned yourself to this PR).

**Comment by kinow** [comment]
Oh, I think I planned to work on this, but completely forgot. Feel free to re-assign, and +1 to fixing the docs :+1:
