### ISSUE TITLE
Expose suite UUID to event handlers.

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc#2901]
This will allow external systems to identify the unique "suite run", in case a suite is started again from scratch.

**Comment by hjoliver** [comment]
From earlier discussion, UUID is preserved over suite restart, but renewed if the suite is cold- or warm-started again (which may result in re-running tasks from the previous suite run).

**Comment by matthewrmshin** [comment]
Just to confirm, we want this for both suite event handlers and task event handlers?
