### ISSUE TITLE
Use json instead of pickle for broadcast_states in cylc-cat-state?

### ISSUE THREAD

**Issue by kinow** [cylc/cylc#2912]
Hi,

While testing the changes for #2815 I wanted to confirm the task states, so used `cylc cat-state` as below.

```bash
testuser@cylc:~/suites$ cylc cat-state pbs2
run mode : live
time : 2019-01-04T03:00:46Z (1546570846)
initial cycle : 20190104T0251Z
final cycle : None
(dp0
.
Begin task states
```

And that `(dp0` caught my eye. A quick look at the code, showed me that it was the [`broadcast_states`](https://github.com/cylc/cylc/blob/c43c0c3009732358b64114fc4846e33b70989d13/bin/cylc-cat-state#L107) empty dictionary being dumped with `pickle`.

Then I tried an example from the CUG to send a broadcast to the `pbs2` running suite.

```bash
testuser@cylc:~/suites$ cylc broadcast -s " [ environment ] VERSE = the quick brown fox " pbs2
Broadcast set:
+ [root.*] [environment]VERSE=the quick brown fox
```

Running `cat-state` again gives an ugly - and not so useful - output:

```bash
testuser@cylc:~/suites$ cylc cat-state pbs2
run mode : live
time : 2019-01-04T03:07:41Z (1546571261)
initial cycle : 20190104T0251Z
final cycle : None
(dp0
S'*'
p1
(dp2
S'root'
p3
(dp4
S'environment'
p5
(dp6
S'VERSE'
p7
S'the quick brown fox'
p8
ssss.
Begin task states
t1.20200313T0251Z : status=ready, spawned=False
```

Instead of using `pickle`, if we use the `json` module, I think the output is clearer.

```
testuser@cylc:~/suites$ cylc cat-state pbs2
run mode : live
time : 2019-01-04T03:07:05Z (1546571225)
initial cycle : 20190104T0251Z
final cycle : None
{"*": {"root": {"environment": {"VERSE": "the quick brown fox"}}}}
Begin task states
t1.20200228T0251Z : status=ready, spawned=False
```

Here's what I used for this test:

```diff
kinow@kinow-VirtualBox:~/Development/python/workspace/cylc$ git diff
diff --git a/bin/cylc-cat-state b/bin/cylc-cat-state
index 0dffa5507..6543e2e6f 100755
--- a/bin/cylc-cat-state
+++ b/bin/cylc-cat-state
@@ -27,7 +27,7 @@ if remrun():
     sys.exit(0)
 
 import os
-import pickle
+import json
 import re
 import sqlite3
 import traceback
@@ -104,7 +104,7 @@ def _get_state_lines(suite):
         r"time : %(time_str)s (%(time_since_epoch)s)" % data,
         r"initial cycle : %(initial_point)s" % data,
         r"final cycle : %(final_point)s" % data]
-    lines += pickle.dumps(data["broadcast_states"]).splitlines()
+    lines += json.dumps(data["broadcast_states"]).splitlines()
     lines.append(r"Begin task states")
     for item in data["task_pool"]:
         lines.append(
```

Just would have to update some tests, but I think this is doable. Would it be useful, and also would it be a good idea or is it going to disappear with the migration to the web (I don't think so, but just in case). Not sure if the `pickle` output is actually used as-is for troubleshooting/operations...

Cheers
Bruno

**Comment by matthewrmshin** [comment]
@kinow `cylc cat-state` was deprecated (#1827 and see also #1530) and was only retained for backward compatibility - and completed with a layer to print broadcast states in its old ugly pickle form. `cylc ls-checkpoints` is now the preferred command and should give you a nice enough printout of broadcast states. If you want JSON output, you should work on `cylc ls-checkpoints`.

**Comment by kinow** [comment]
Looks like I still have a lot to catch up on Cylc code base changes & deprecations. Thanks for the explanation. Will have another look tomorrow or monday

**Comment by matthewrmshin** [comment]
No problem - `cylc cat-state` is one of those commands that is still in use by some users, and I don't really want to mess with it too much - hence a new command + back compat layer. Not sure if we can get away with removing it from Cylc 8 or not.

**Comment by hjoliver** [comment]
@kinow - a bit more context: `cylc cat-state` used to `cat` the horrible old "state dump" text files that recorded workflow state (for restart purposes) until the files were gradually and eventually replaced with the current sqlite DBs.

This deprecation is recorded and explained in the command help:
```
Usage: cylc [info] cat-state [OPTIONS] REG

Print the suite state in the old state dump file format to stdout.
This command is deprecated; use "cylc ls-checkpoints" instead.
```
So I think we can close this issue as invalid, if that's OK with you...

**Comment by hjoliver** [comment]
@matthewrmshin - in my opinion we should remove this command (and probably more too) in cylc-8. Maybe _a few_ users are parsing its output automatically, but that sort of scripting should be easy to update, and we can't be expected to keep this sort of cruft around for ever (IMO!).

**Comment by kinow** [comment]
>So I think we can close this issue as invalid, if that's OK with you...

Hi @hjoliver ! Thanks for the explanation. And I will admit that I missed that deprecation warning.

>@matthewrmshin - in my opinion we should remove this command (and probably more too) in cylc-8. Maybe a few users are parsing its output automatically, but that sort of scripting should be easy to update, and we can't be expected to keep this sort of cruft around for ever (IMO!).

Chiming in; I'd be fine with less commands... easier to maintain, and there's an alternative anyway. Of course I don't have users to support, large installations to maintain, etc :grimacing:

**Comment by matthewrmshin** [comment]
@hjoliver Taking note to remove `cylc cat-state` for cylc-8.

**Comment by kinow** [comment]
Closing as this won't be implemented :+1:

**Comment by kinow** [comment]
And created an issue to remember us of removing this command in cylc-8 (used milestone cylc-8)
