### ISSUE TITLE
test coverage: CLI host specification: remote host CLI syntax modes

### ISSUE THREAD

**Issue by sadielbartholomew** [cylc/cylc#2923]

**Comment by sadielbartholomew** [comment]
Didn't mean to open this! Working out how to delete it. Oops!

**Comment by sadielbartholomew** [comment]
Sorry for this mistake, @hjoliver. Could you please see if you can remove this completely, as I think it is [possible to do so now](https://help.github.com/articles/deleting-an-issue/)?

**Comment by hjoliver** [comment]
Roger that.  Here goes...
