### ISSUE TITLE
CLI: No handlers could be found for logger "cylc"

### ISSUE THREAD

**Issue by matthewrmshin** [cylc/cylc#2940]
Users are seeing error messages such as: `[FAIL] No handlers could be found for logger "cylc"`. This is an indication that you may have invalid entries in your `~/.cylc/global.rc`. It looks like the CLI command is parsing `global.rc` before the logging stream handler is set up by the option parser when it deals with verbosity. We should either 1) forget about logging at this stage or 2) set up a stream handler any way - regardless of verbosity.

**Comment by kinow** [comment]
Some time ago there were comments (here in GitHub, or in Riot) about having more handlers besides the `cylc` (if I remember well).

Is it something that could be helpful here? Maybe a handler like `command`, or `cylc.command`, etc.

**Comment by matthewrmshin** [comment]
If I understand this correctly, you are talking about *loggers*. The error here is complaining about the lack of *handler* (or *appender* in *log4j* speak).

**Comment by kinow** [comment]
Oh sorry, naming confusions (am still more familiar with log4j,logback,slf4j,etc unfortunately. Need to read more about py's logging!)

**Comment by matthewrmshin** [comment]
They are almost identical - but for reason Python's logging has decided to rename *appender* to *handler*. (Not sure which one came first!)
