### ISSUE TITLE
minor bug: top level Makefile

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc#2950]
The installation instructions say to type "make" in newly unpacked release dirs.  This is supposed to create the VERSION file and build the docs.  Currently doc build fails and prints a lengthy sphinx build usage message. The VERSION file is still created though, before the doc build fails, so this is a confusing but non-fatal message for new installers.

@sadielbartholomew - this should be a very easy fix, but I'm not entirely sure if you should adapt the Makefile to run "cylc make-docs" or remove doc build from the Makefile (so it only creates the VERSiON file) and expect users to run "cylc make-docs").  (I think there was a small discussion about whether "make" should build docs or not, some time back, but I forget the outcome of that...)

**Comment by hjoliver** [comment]
(The fix needs to go to 7.8.x too, of course).

**Comment by sadielbartholomew** [comment]
Sorry for the omission @hjoliver, I did not know (though should have checked) that there was anything that would try to build the docs external to the ``doc`` directory.

> Currently doc build fails

Just for clarify for any other readers here, this is only the build via the top-level Makefile. ``cylc make-docs`` still functions as expected, building cleanly (i.e. no need for major concern!) except for one 'warning' introduced with #2936.

I'll get a PR up (& mirrored to the ``7.8.x`` branch) to address this, along with the warning above, now.

**Comment by hjoliver** [comment]
> Just for clarify for any other readers here,

Correct, thanks for clarifying!
