### ISSUE TITLE
gscan: unstable folding

### ISSUE THREAD

**Issue by oliver-sanders** [cylc/cylc#2956]
When viewing suites from multiple users (`cylc gscan -o foo -o bar -o baz`) the tree folding (i.e. expanding and collapsing of cycle points) is unstable.

When expanding one row others are prone to follow uninvited. I've observed that an equal number of rows to the number of users being scanned unfold suggesting this is probably to do with the data model being updated multiple times (once for each user).

*Note GTK handles folding at the index (`TreeView`) rather than in the data (`TreeModel`)*

**Comment by hjoliver** [comment]
See also #2576

**Comment by oliver-sanders** [comment]
Lets roll #2576 into this issue:

> If one row is expanded in the gscan window, after update all rows will be expanded.
>
> For reference: https://github.com/cylc/cylc/blob/7.6.0/lib/cylc/gui/updater_dot.py#L291
