### ISSUE TITLE
Task suspension in ready state upon suite reload

### ISSUE THREAD

**Issue by sadielbartholomew** [cylc/cylc#2964]
Users have observed, in version ``7.8.1``, abnormalities with job submission timings whereby tasks spend longer than expected, or indeed appear to get stuck, in the ``ready`` state.

From further investigation we have deduced that it results from the reloading of a suite in the middle of job retries.

#### Minimal example

Content of ``suite.rc``:

```ini
[scheduling]
    [[dependencies]]
        graph = """
                foo:submit-fail => stopper
                reload_suite => stopper
                """
[runtime]
    [[foo]]
        [[[job]]]
            batch system = at
            batch submit command template = sleep 5
            submission retry delays = 3*PT5S
    [[stopper]]
        script = sleep 30; cylc stop "${CYLC_SUITE_NAME}"
    [[reload_suite]]
        script = cylc reload "${CYLC_SUITE_NAME}"
```

where, in order to get the reload to occur between retries, it is necessary to bodge the logic of the reload command within ``Scheduler.command_reload_suite()``, as follows:

```diff
diff --git a/lib/cylc/scheduler.py b/lib/cylc/scheduler.py
index f965b8b1a..2342a14d2 100644
--- a/lib/cylc/scheduler.py
+++ b/lib/cylc/scheduler.py
@@ -960,6 +960,7 @@ conditions; see `cylc conditions`.
         LOG.info("Reloading the suite definition.")
         old_tasks = set(self.config.get_task_name_list())
         self.suite_db_mgr.checkpoint("reload-init")
+        sleep(15)
         self.load_suiterc(is_reload=True)
```

Observed behaviour is that the ``foo`` task remains in the ``ready`` state, never progressing to ``submit-failed`` as would be expected & as occurs when the ``reload_suite`` task is removed from the example suite definition.

**Comment by matthewrmshin** [comment]
Related to #2699.
