### ISSUE TITLE
Incorrect event time recorded in the DB when processing message submit failed

### ISSUE THREAD

**Issue by kinow** [cylc/cylc#2977]
I am reading the code of `task_events_mgr.py` and `scheduler.py` to understand #2968. Right now I am slowly reading the code... and while doing it... I noticed that in both `master` and in the PR for the issue mentioned before, the event time used for the DB is always the current time.

However, the function accepts an `event_time`... which is initialized to be the current time if `None`... but then never gets used.

Is that a bug? I think like in that fairy tale, as it nears mid-night, my English starts to disappear. So here's some code to help understanding what I mean.

```python
    def _process_message_submit_failed(self, itask, event_time): # <--- EVENT_TIME
        """Helper for process_message, handle a submit-failed message."""
        LOG.error('[%s] -%s', itask, self.EVENT_SUBMIT_FAILED)
        if event_time is None: # <--- CHECK IF NULL
            event_time = get_current_time_string() # <--- INITIALIZE IF NULL
        self.suite_db_mgr.put_update_task_jobs(itask, {
            "time_submit_exit": get_current_time_string(), # <--- BUT NEVER USED?!
            "submit_status": 1,
        })
        //...
```

And in `_process_message_submitted`, it is correctly used. So I am assuming it to be a minor bug here?

**Comment by kinow** [comment]
(and just realized it was a warning in my IDE for that variable as unused too)

**Comment by matthewrmshin** [comment]
Correct. It should be changed to `event_time`.
