### ISSUE TITLE
Remove cylc cat-state in cylc-8

### ISSUE THREAD

**Issue by kinow** [cylc/cylc#2980]
From comments in #2912, the `cylc cat-state` was deprecated and can be removed in cylc-8

**Comment by kinow** [comment]
Hmmm, so now that Py3 is in `master`. Does it mean to fix this issue all we need to a pull request that removes the command from `bin`?

**Comment by matthewrmshin** [comment]
And anything that references it?

**Comment by kinow** [comment]
Oh yeah, that's right. And maybe docs... but if that's all I can prepare a pull request once the other pull request to add `setup.py` is done.

**Comment by kinow** [comment]
Added under the task list in #2972
