### ISSUE TITLE
Task re-tries not shown in GUI

### ISSUE THREAD

**Issue by dpmatthews** [cylc/cylc#30]
If a task is configured to retry then it will immediately return to the waiting state on failure. One problem with this is that it is not obvious in the GUI that there has been a failure, nor any access to the output from the failed task.

It would be good if the GUI could be enhanced somehow to make re-tries more obvious, perhaps making use of the try number (see issue 29)?

**Comment by matthewrmshin** [comment]
It will also be nice if we can show when the suite will re-submit the task. (`cylc show SUITE TASK.CYCLE` should probably present this sort information as well.)

**Comment by matthewrmshin** [comment]
> nor any access to the output from the failed task.

(This particular problem has been resolved for quite some time already. The task combo log viewer is able to show log files of all submitted jobs of a task.)
