### ISSUE TITLE
Remove GTK labels from `task_state_prop.py`?

### ISSUE THREAD

**Issue by kinow** [cylc/cylc#3012]
Hi,

I am preparing a small pull request for typos, after one was found in #3006, and found some GTK labels in `task_state_prop.py`.

I think it should be removed, but not sure whether it can be done, what would be the impact after that, etc. I think it is used by the `TaskPool` somewhere?

Haven't investigated as I am preparing the other pull request. Just came here to log the issue before I forget :+1: 

Cheers
Bruno

**Comment by hjoliver** [comment]
Good spotting. Definitely removable (and in the unlikely event of consequences beyond the now-gone-GUI, those consequences can be removed).
