### ISSUE TITLE
Error debugging in PyCharm (master branch is 3.7+ only)

### ISSUE THREAD

**Issue by kinow** [cylc/cylc#3063]
Hi!

I am able to run any suite with Cylc `master` in my Linux terminal, but not with PyCharm.

I had a short session about troubleshooting Cylc with @hjoliver (thanks!) and decided to apply that knowledge to keep it fresh in my mind - and also because I wanted to debug something in `TaskPool`.

The symptoms in Cylc were no error messages in the terminal (even with `--debug` and `--verbose`), nothing appeared wrong when I tried debugging. The `Scheduler#run` method would just keep running forever. Nothing found in the `housekeeping`, the first `TaskProxy` was inserted, its job was queued, then ready, then submitted. And then there was nothing else.

That's when I looked at the job error file (oh, and yup, me again using that suite `five` :grin:).

```
cat ~/cylc-run/five/log/job/20130808T0000Z/prep/01/job.err 
Sending DEBUG MODE xtrace to job.xtrace
2019-04-02T21:53:15Z DEBUG - Loading site/user global config files
2019-04-02T21:53:15Z DEBUG - Reading file /home/kinow/.cylc/global.rc
Traceback (most recent call last):
  File "/home/kinow/Development/python/workspace/cylc/bin/cylc-message", line 140, in <module>
    main()
  File "/home/kinow/Development/python/workspace/cylc/bin/cylc-message", line 136, in main
    return record_messages(suite, task_job, messages)
  File "/home/kinow/Development/python/workspace/cylc/lib/cylc/task_message.py", line 86, in record_messages
    {'task_job': task_job, 'event_time': event_time, 'messages': messages}
  File "/home/kinow/Development/python/workspace/cylc/lib/cylc/network/client.py", line 193, in serial_request
    return asyncio.run(
AttributeError: module 'asyncio' has no attribute 'run'
```

Turns out my terminal in Ubuntu/XFCE uses my `.bashrc` file correctly, which is set by default to load Anaconda Python, which is Python 3.7.something.

However, when I run that from PyCharm process, it starts Cylc without the `.bashrc` evaluation, and uses the operating system Python (3.6).

Looks like `asyncio.run` was only [added in 3.7](https://docs.python.org/3/library/asyncio-task.html#asyncio.run). This was not found in Travis-CI, because the unit tests are running 3.6 and 3.7. But functional tests are running only 3.7.

NB: Perhaps our functional test battery should be running against our minimum supported version, instead of against the most recent version?

**Comment by kinow** [comment]
Pull request submitted. Just noticed I had disabled the IDE code compatibility checks while we were transitioning from Py2 to Py3 (it was troublesome going back and forth in pull requests). Have re-enabled it for 3.5, 3.6, and 3.7. Will run a check in the afternoon and see if it finds anything else :+1:

**Comment by hjoliver** [comment]
> NB: Perhaps our functional test battery should be running against our minimum supported version, instead of against the most recent version?

Hmmm, interesting question.  Ideally we should run against all supported versions, but with the test battery being what it is (i.e. a gorilla) that's not really practical.

It would be equally bad (IMO) if we put out a release that doesn't run against the latest supposedly-support Python version.  

I guess my preference, if we can only run the test battery once, is support latest Python (encourages us to use latest coding constructs etc.). ... then respond to bug reports from those stuck on older versions.

OR (better?) routinely run tests against latest Python version, but do some back-compat runs at older versions before making a release?

**Comment by kinow** [comment]
>OR (better?) routinely run tests against latest Python version, but do some back-compat runs at older versions before making a release?

I always like other possible options! This one sounds doable too. We can use a [Travis cron job](https://docs.travis-ci.com/user/cron-jobs/) to test nightly (or at some other schedule) Cylc with different settings (that may take much longer to run).

This would be useful for testing Cylc+PBS with containers too.

Only issue I can think of, is that we don't have the "night" concept, as we have a Cylc team working 24 hours :), over almost 6 days a week (NZ monday morning <-> UK friday afternoon) :grimacing:

**Comment by hjoliver** [comment]
Well if Travis CI can take the pain, we can give the pain 💉 💊

**Comment by kinow** [comment]
Closing as we are now on 3.7.
