### ISSUE TITLE
validate: infinite loop for invalid datetime

### ISSUE THREAD

**Issue by oliver-sanders** [cylc/cylc#3074]
Using the new `next()`, `previous()` syntax it is possible to get `cylc validate` into an infinite loop as it attempts to roll-over an invalid datetime e.g:

```ini
initial_cycle_point=previous(T06:00Z)
```

This is a fault in the `isodatetime` library, https://github.com/metomi/isodatetime/pull/127 presents a solution.

**Comment by oliver-sanders** [comment]
The fix is up against `isodatetime` master (py3), do we want to port this fix to the bundled isodatetime in the 7.8.x branch for next-release?

**Comment by matthewrmshin** [comment]
Yes, if it is not too hard to do - given that it is currently affecting users of Cylc.

**Comment by oliver-sanders** [comment]
Once metomi/isodatetime#127 is approved I'll raise a follow on.

**Comment by kinow** [comment]
Not sure why GitHub did not close this one. @oliver-sanders used _closes #pr-number_. Closing manually.
