### ISSUE TITLE
Cylc 7.8.x will build with Python3 unless we update Travis yaml file before 16th April

### ISSUE THREAD

**Issue by kinow** [cylc/cylc#3099]
See warning in 7.8.x builds on Travis.

> This job ran using the default Python version, which will be updated to 3.6 on April 16th, 2019. You can explicitly stay on the previous version by specifying python: 2.7 in your .travis.yml. 

![image](https://user-images.githubusercontent.com/304786/55844181-2a068780-5b90-11e9-9d4b-e3654740e2ee.png)

**Comment by kinow** [comment]
Found while loooking at the `prove --timer` output after it was merged 👍  hadn't heard about this change in Travis before 😟

**Comment by matthewrmshin** [comment]
Closed by #3102.
