### ISSUE TITLE
Document how to take out failed tasks automatically

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc#310]
Failed tasks can be taken out with suicide triggers. This may be appropriate if the suite has recovery tasks that take action to get around the failure - or else the failed tasks will persist and prevent automatic shutdown when the suite is otherwise finished.  Example suite AutoRecover/suicide2 does this, but it is not documented in the user guide.

**Comment by arjclark** [comment]
I guess this is now covered by the suicide triggers description at: http://cylc.github.io/cylc/html/single/cug-html.html#x1-950009.3.4.8 ?

**Comment by hjoliver** [comment]
Yes, done.

**Comment by matthewrmshin** [comment]
I believe it was implemented by #711 for cylc-5.4.0.
