### ISSUE TITLE
gcylc: File -> Open for switching to suites running on another host

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc#345]
From @benfitzpatrick - "t would be useful for us here if cylc gui --host=X detected suites running on X in the db-viewer part" [i.e. the dialog for opening registered suites].

**Comment by benfitzpatrick** [comment]
Currently, the 'Switch to Another Suite' action will switch suite but not host, which results in a connection failure and a stopped status in the GUI.

**Comment by matthewrmshin** [comment]
See also #1050 and #1285.
