### ISSUE TITLE
rationalize use of suite stdout, stderr, and the log

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc#386]
Currently this is not very well organized. You really have to look at all three files to see what's going on if an error occurs. 

Perhaps we should only use the log: it automatically time-stamps entries, it handles multiple threads nicely, and the amount of logging done is configurable.

**Comment by hjoliver** [comment]
At the least, we should review and document exactly what goes where.

**Comment by matthewrmshin** [comment]
Since #2437, a running suite should no longer write to the `out` file.
