### ISSUE TITLE
gcylc graphview right-click menu for removed tasks

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc#414]
When a task is removed from the suite, the graph node becomes a greyed out base node, but the right-click menu does not change immediately to the minimal menu for base nodes. It does change after a little while.

**Comment by kaday** [comment]
Do you still have this problem as I am unable to reproduce it with a simple test suite?

**Comment by hjoliver** [comment]
I can't reproduce this either, I guess it has been fixed (well, there's been many changes to the GUI in 2 years...)
