### ISSUE TITLE
Replace state dump files with the run-db

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc#421]
Depends on:
 
 * #372 - flag which task proxies are currently live in the suite, so cylc can figure out which ones to resurrect on a restart

**Comment by matthewrmshin** [comment]
I now think this issue can be solved quite easily. What we lack in the runtime database are:
* a table for run mode, initial cycle point, final cycle point.
* a table of current tasks and whether they have spawned.

We'll also need to consider the following:
* Do we need to have the ability equivalent to restarting with a different state dump?
* Do we need to have a way to dump/edit/load the runtime database?
  * (Or simply recommend users to use something like [DB Browser for SQLite](http://sqlitebrowser.org/)?)
