### ISSUE TITLE
Group batch jobs feature request

### ISSUE THREAD

**Issue by areinecke** [cylc/cylc#474]
On shared HPC systems it can be advantageous to limit the number of submitted batch jobs by grouping a larger number of small tasks into a single job.  A nice feature in cylc would be  to allow the suite to group any number of tasks that depend serially on each other into a single batch job.

**Comment by hjoliver** [comment]
@areinecke - if you're still listening in - #1307 is somewhat related.

**Comment by hjoliver** [comment]
Closing, not easy to see how to do this usefully.
