### ISSUE TITLE
Remote run-directory housekeeping.

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc#480]
**For task polling to work under all circumstances, old task-status files have to be cleaned up at suite start-up**. Since #453 we can do this housekeeping on the suite host, but it is currently turned off by default for Rose compatibility, and it has not been implemented for task hosts.

The following link details a specific case where task polling can get the wrong result if old task status files are left lying about from a previous suite run: https://github.com/cylc/cylc/pull/462#issuecomment-18185769.

**Comment by benfitzpatrick** [comment]
We could remove all the old job submit number directories (`log/job/CYCLE/NAME/*`) in the first (01) submission's job.
