### ISSUE TITLE
Remaining task communications issues...

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc#517]
This cleans up the leftovers from #67, which I closed on completion of task polling changes. 

 * Currently each task poll opens and then closes a new ssh connection to the task host; should we attempt to keep a single ssh connection open per task (or per task host) for task polling. 

 * it should at least be documented that polling may (will?) cause excessive network chatter (/OS jitter?) on HPCs, so polling should be used as a last resort (also because it is a less efficient way of tracking task progress).

@m214089 @dpmatthews @matthewrmshin - at your leisure, please check that there are no other issues arising from #67 that we still need to consider.

**Comment by matthewrmshin** [comment]
The situation described by bullet point 1 should be relieved some what by #1591.

**Comment by matthewrmshin** [comment]
Bullet point 2 has been in CUG for a very long time.

**Comment by matthewrmshin** [comment]
@hjoliver Should we close this issue down?

**Comment by hjoliver** [comment]
Closing...
