### ISSUE TITLE
Attempt access to contact files via the filesystem

### ISSUE THREAD

**Issue by trwhitcomb** [cylc/cylc#526]
From a discussion on the cylc-dev mailing list, it seems that when using `cylc monitor` to check on the progress of another user's task, it's necessary to have both the passphrase file as well as passwordless SSH access into their account.

For checking up on other users on the same system, the following should be possible:
1. If `--owner` and `--host` are supplied, the `cylc monitor` command will work as normal.
2. However if _just_ `--owner` is supplied, the `cylc monitor` command will attempt to find the ~port~ contact file via the local filesystem instead of an SSH login.

**Comment by hjoliver** [comment]
[meeting] - review needed, I don't understand this one fully...

**Comment by matthewrmshin** [comment]
I have re-read the original description of this issue. Looks pretty easy to implement.
