### ISSUE TITLE
Improved security layer

### ISSUE THREAD

**Issue by matthewrmshin** [cylc/cylc#537]
Some ideas have been discussed recently via email and in person. Currently Pyro is used to control access with a single passphrase. You either have access to everything or none. Logically, access to a running suite can be classified as:

1. Task job communication.
2. People access:
   * a. read-only.
   * b. owner/administrator.

For 1. Task jobs communication. As the suite generate a suite contact file for a task host, it can introduce a unique key for each task job host, and the value written to the suite contact file. (Does it mean that the suite contact file should be user read-only?) The only usage of such a key is for a task job to communicate to the suite. Attempt to use the key for anything else will fail. (Maybe we can even limit the number of connections per task job host by counting the maximum number of messages expected from the current number of submitted task jobs to a given host.)

For 2. People access. We need to introduce an authentication layer. (Some kind of public-private key system?) And maybe a session token system so people only have to login once per session.

For 2a. Read-only access. Default to allow everyone? Or authenticated users only?

For 2b. Full access. Authorised authenticated users (normally the owner) only.

See also #72, #526.

**Comment by hjoliver** [comment]
Superseded (and largely addressed) by #1475.
