### ISSUE TITLE
Some Gnome-3 equivalent of the cylc gnome-2 panel app. 

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc#570]
See:
- https://github.com/cylc/cylc/issues/79#issuecomment-13921932
- https://github.com/cylc/cylc/issues/79#issuecomment-13935341

**Comment by hjoliver** [comment]
[meeting] - no hurry on this, but it may need to be addressed before RHEL7 is deployed at the MO.

**Comment by matthewrmshin** [comment]
Marked as a duplicate of #112.
