### ISSUE TITLE
Command line equivalent of "cylc gsummary"?

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc#578]
A command line tool that prints multiple suite state summaries to the terminal would be useful - e.g. to get a quick overview of your suites over a slow non-X connection, or to make it very easy to script up a custom uber-monitor that could email you, or whatever, if any task failed in any of your suites on any of your suite hosts.

@benfitzpatrick - this would be quite easy to do reusing the guts of your gsummary code, no?  We could just replace the graphical task state dots with proper state names, and print once instead of repeatedly polling.

**Comment by benfitzpatrick** [comment]
We now definitely have a platform where users can't use GUIs, so this would be good.

**Comment by hjoliver** [comment]
Update: #1480 achieves this.
