### ISSUE TITLE
collapsible named groups of suites in gscan gui?

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc#601]
@benfitzpatrick - with reference to #600, it might be useful to have collapsible named groups of suites in the summary gui, to distinguish related/interdependent suites from others.

I think it would be sensible to use the existing hierarchical suite naming convention as displayed in the former cylc reg db viewer / current gcylc File->Switch Suites dialog (e.g. oper.atmos, oper.streamflow, oper.seastate etc.). But we may also need the ability to define groups of suites with unrelated names (to work with Rose?)

**Comment by hjoliver** [comment]
Group by some kind of "tag" defined in the suite definition.

**Comment by oliver-sanders** [comment]
Closed by #2024
