### ISSUE TITLE
cylc CLI: add bash tab completion

### ISSUE THREAD

**Issue by benfitzpatrick** [cylc/cylc#667]
We should add a cylc-specific [bash tab-completion](http://www.debian-administration.org/article/317/An_introduction_to_bash_completion_part_2) script to enhance the CLI, as has been done for [git](http://git.kernel.org/cgit/git/git.git/plain/contrib/completion/git-completion.bash?id=HEAD).

**Comment by hjoliver** [comment]
c.f. the Rose CLI.
