### ISSUE TITLE
cylc suite database: suite events

### ISSUE THREAD

**Issue by arjclark** [cylc/cylc#705]
It would be good to record suite level events in the cylc suite database such as the timeout handler being fired off, suite shutting down etc. This would be key events that may be useful for monitoring purposes rather than as a replacement for the suite log.

metomi/rose#918 relates.

**Comment by arjclark** [comment]
@matthewrmshin - is this issue still relevant given all the database changes over the past year and forthcoming #1827 pull request?

**Comment by matthewrmshin** [comment]
This is still relevant, as there is not yet a change to add a suite events table.

**Comment by benfitzpatrick** [comment]
@matthewrmshin might do this as a follow on to #1827.

**Comment by matthewrmshin** [comment]
> settings broadcast to suite/tasks

Done #1827.

> We should record any other user requests that may result in changes to the suite state.
> We should include the origin of the requests.
> Do we want to store any other query requests?

These are in the suite log since #1480.

> Not necessarily in the database, but we should keep a record of suite.rc (processed?) for each run, restart and reload.

Done #1272 as files under `log/suiterc/`.

**Comment by matthewrmshin** [comment]
Closing as superseded, as I have consolidated the items of this issue to #1032, and or commented on them above.
