### ISSUE TITLE
main loop: configurable delay and more

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc#715]
See comments https://github.com/cylc/cylc/pull/714#issuecomment-25751924 (and after).  Current hardwired 1 sec sleep each time through these loops keeps CPU usage low, but it delays task spawning a bit and suite shutdown by a couple of seconds.  Changing to say 0.1 sec results in snappier performance - good for quick test suites in particular - and faster shutdown, but higher CPU usage.  So ... might be good to make this configurable as per @matthewrmshin's comment https://github.com/cylc/cylc/pull/714#issuecomment-25794081

**Comment by hjoliver** [comment]
Or longer!  Or dynamic.

**Comment by hjoliver** [comment]
(event-driven scheduling model better)

**Comment by matthewrmshin** [comment]
Related to this (somewhat) is that I would like a more direct control of the multiprocess pool using the main loop. The use of the standard library multiprocess pool has been causing headache, e.g. having to start the pool early and having child processes alive even when they are doing nothing.

A better approach is to write our own child process management logic and have it integrated with the main loop. This approach will give us more flexibility, e.g. child processes on demand, better external command management, control of number of child processes in run time, prioritisation of items in processing queue, etc.

**Comment by dpmatthews** [comment]
@hjoliver - are you happy to close this?  We don't have a configurable delay but hopefully the dynamic timing removes the need for this.

**Comment by matthewrmshin** [comment]
@hjoliver I think this is superseded by #2866, which will address the issue in a more standard way?

**Comment by hjoliver** [comment]
Yep, I'll close this; thanks for flagging it.  Only 166 issues to go now :grimacing: ...
