### ISSUE TITLE
Network communication: Pyro4 or another protocol?

### ISSUE THREAD

**Issue by cylc** [cylc/cylc#72]
Currently cylc uses Pyro3 as a rather minimal object oriented RPC interface, for network communication between cylc clients (tasks, commands, GUIs) and cylc servers (running suites).

Pyro3 is now in maintenance; Pyro4, which is compatible with Python 3, is recommended for new projects. In the future we will clearly have to upgrade to Pyro4, or switch to something else - possibly a custom protocol because cylc's needs in this respect are quite simple.

Unfortunately Pyro3's built in "connection authentication" is currently critical to cylc's operation (i.e. suite passphrases),  and as of mid 2012 Pyro4 does not have any built in connection authentication.  However, a mid-2011 post to the Pyro mailing list by the Pyro maintainer Irmen de Jong suggests that connection authentication is on his To Do list, and it will likely take a similar form to that in Pyro3.  Options:

 * wait on Pyro4 connection authentication before switching to Pyro4
 * convert to Pyro4 regardless and build our own authentication mechanism into cylc 
 * drop Pyro and build our own network communication and authentication protocols

**Comment by hjoliver** [comment]
Closing this, nothing has changed here - we'll soon be moving ahead with HTTP.
