### ISSUE TITLE
Job polled submission failed when job is still in queueing system

### ISSUE THREAD

**Issue by matthewrmshin** [cylc/cylc#798]
Topic was raised on cylc-dev:
https://groups.google.com/forum/#!topic/cylc-dev/aRrLmuqhYVw

When Cylc polls a job on a queueing system, it can currently cause a submission failure on an unknown queueing system status.

We should simplify the system so that:
1. If the job is in the queueing system and has a status file, it should be considered running.
2. If the job is in the queueing system and has no status file, it should be considered submitted.
3. A poll should report the result of the poll, and perhaps warn users of any unusual status.

Other considerations:

1. If status file says the job is running, but it is no longer in the queueing system. Chances are, it has reached its resource limits, but it could have been kicked out for other reasons. I think the current system mark the job as failed, which could potentially trigger a retry? However, if this happens because the job has reached its resource limit, a retry would probably do no good (unless the job application has an incremental mode or some such). It will simply fail again.
2. If status file says the job is running, and it is in the queueing system. The most we can do is check for a known good status. Any unknown status should trigger a user notification, but the state of the job should still be `running`.
3. If there is no status file, and the job has disappeared from the queueing system, Currently it causes a submission failed. However, one can argue that it is not really a submission failure, because it has been submitted to the queueing system successfully. Would a submission retry help? Hard to say.
4. If there is no status file, and the job is in the queueing system. Like 2, the most we can do is check for a known good status. Any unknown status should trigger a user notification, but the status should still be `submitted`.

**Comment by hjoliver** [comment]
@matthewrmshin - can this be closed thanks to #808?
