### ISSUE TITLE
siterc: configurable event hooks and timeouts

### ISSUE THREAD

**Issue by arjclark** [cylc/cylc#802]
We should be able to set site defaults for ~~batch sizes~~, timeouts and event hooks.

These would be brought into the suite from the site/user config in much the same way as polling intervals.

**Comment by arjclark** [comment]
#1277 covers timeouts. Default/site configured event hooks still to be covered.

**Comment by matthewrmshin** [comment]
@arjclark Can we close this?

**Comment by arjclark** [comment]
Yeah, now superseded by #1529

**Comment by arjclark** [comment]
And by #1528
