### ISSUE TITLE
cylc gui: improve compatibility with GTK themes

### ISSUE THREAD

**Issue by benfitzpatrick** [cylc/cylc#885]
Some users have quite radically different GTK themes such as High Contrast Inverse that interact badly with some hardcoded colours in the cylc gui. We should try and find
alternatives to hardcoding in colours.

**Comment by hjoliver** [comment]
[meeting] - apparently the hardwired white background (graph view) looks wrong with dark desktop themes.  @benfitzpatrick to investigate at some point.

**Comment by matthewrmshin** [comment]
Superseded by #1873.
