### ISSUE TITLE
offset unit and value in task environment

### ISSUE THREAD

**Issue by m214089** [cylc/cylc#899]
Hi Hilary,
it would be nice to have beside CYLC_TASK_CYCLE_TIME as well the offset and unit available in the task scripts. I kno that it should not be necessary, but for getting a lot of legacy scripting working, it would help quite a lot.
Cheerio,
Luis

**Comment by hjoliver** [comment]
@m214089 - my argument above suggests it is not possible *in general* to automatically identify the interval you want here.  Let me know if you agree and I'll close this issue.

**Comment by hjoliver** [comment]
Closing this - if I understood the issue correctly, it can't be done.  @m214089 can reopen if he thinks I'm wrong.
