### ISSUE TITLE
Bug in xdot.py

### ISSUE THREAD

**Issue by m214089** [cylc/cylc#902]
Hi Hilary,

in cylc 5.4.7: xdot.py line 490 is a code line int(string) and this does not work properly.
If i change it to int(float(string)) it works. As the solution does not look that nice I just
tell you about it. Maybe someone knows a nicer solution.

Cheerio,
Luis

**Comment by benfitzpatrick** [comment]
The latest xdot.py solves this - it's a compatibility problem with later versions of graphviz:

https://bugs.launchpad.net/ubuntu/+source/xdot/+bug/1317688

I'm intending to upgrade the version of xdot that cylc uses.

**Comment by hjoliver** [comment]
> I'm intending to upgrade the version of xdot that cylc uses.

That would be great. Apologies in advance if you find it a bit messy.  I
bodged it in ages ago, and never got back for a good clean up [?]
