### ISSUE TITLE
Task URLs

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc#903]
A feature request from NIWA's operations manager:

> one feature that I would like to see in cylc: an info tag for each task with
> a URL to link to documentation. We could have several URLs to link to e.g.
> metadata, what to do, problems, etc.), but to start one URL should be sufficient

Seems a good idea.

**Comment by matthewrmshin** [comment]
Does #1405 close this?

**Comment by hjoliver** [comment]
Yes it does.  I had forgotten about this earlier version of #1399 (which adds suite and task URLs).
