### ISSUE TITLE
suite-state polling for "message outputs"

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc#925]
We should be able to trigger off internal "message outputs" in tasks from other suites.
Somewhat related: https://github.com/cylc/cylc/issues/522

**Comment by hjoliver** [comment]
[meeting] - we agreed:
 * this needs doing
 * should be easy: message outputs are now stored in the DB
    * however, the `suite-state` command current works on "events" not messages

**Comment by arjclark** [comment]
@hjoliver - currently have this 90% implemented. Did we want to be able to filter on message priority level too or should we just go off message value alone?

**Comment by hjoliver** [comment]
@arjclark - message value is fine (we can't trigger off message priority even within a single suite, I'm not aware of a good use case for it...)
