### ISSUE TITLE
More customisation options in gcylc.rc

### ISSUE THREAD

**Issue by stevewardle** [cylc/cylc#934]
It would be nice if it were possible to set more of the default display options in the gcylc.rc file (in the same way that the default View 1 and View 2 can be set).  For example:

- [x] side-by-side views
- [ ] left-to-right graphing for the graph view
- [x] visibility of the different states in text view

There are probably others - these are just a few that I seem to end up messing with nearly every single time

**Comment by oliver-sanders** [comment]
- side-by-size views, closed by #1581 
- visibility of the different states in text view, closed by #1833
