### ISSUE TITLE
Trigger (etc.) all failed family members

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc#960]
Triggering a task family triggers all members regardless of their current states. It would be useful to be able to trigger (or reset etc.) all failed members without re-triggering members that already succeeded.

**Comment by hjoliver** [comment]
For the record, here's how this sort of thing can be scripted already:
```
$ cylc dump -t SUITE | awk -F, '/failed/{print $1,$2}' | xargs -n 2 cylc trigger SUITE
```
(credit @trwhitcomb)

**Comment by benfitzpatrick** [comment]
Something like `cylc trigger --state=failed --state=submit-failed SUITE MATCH`?

**Comment by benfitzpatrick** [comment]
Might as well have a similar option for `cylc reset`, etc.

**Comment by matthewrmshin** [comment]
Unfortunately, `cylc reset` already has a `--state=STATE` option to set the state! Should we have an interface that is more generic? E.g.:

```sh
cylc trigger [OPTIONS] REG IDENTIFIER-1 [IDENTIFIER-2 ...]
```

Where the general syntax for an identifier is `NAME.POINT:STATE`. Each component can be missing (as long as it is not ambiguous) or written as a glob pattern. E.g.:
* `cylc trigger REG :failed :submit-failed` to re-trigger all failed and submit-failed tasks.
* `cylc reset --state=succeeded REG archive.20150715T*:failed` to reset all failed archive tasks for all cycle points in a day.

(We can continue to support the old `MATCH POINT` argument list. If 2 new style identifiers are specified after `REG`, they must use a syntax that cannot cause ambiguity.)

**Comment by hjoliver** [comment]
That seems a good idea.
