### ISSUE TITLE
cylc gui: catch incorrect cat-state output

### ISSUE THREAD

**Issue by benfitzpatrick** [cylc/cylc#962]
It is not that rare for users to have `.profile` files that print to standard
out whenever they are sourced.

This causes a quite nasty fail of the `cylc cat-state` functions call from
`cylc gui`, because the e.g. `echo Hello $LOGNAME` effectively appears
at the top of the state file, as read. We should be able to handle this
error in a nicer way - maybe an `IsYourProfileWrongError`...

**Comment by hjoliver** [comment]
We can't have stdout from .profile anyway, because of a documented limitation of ssh.
