### ISSUE TITLE
response to XCPU job kill (wall clock time limit exceeded)

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc#970]
Loadleveler lets users determine the interval between SIGTERM and SIGKILL signals, to allow graceful shutdown if the CPU time limit is exceeded.  In our case this means updating the task status file and sending a message back to the suite daemon.

In PBS this interval is apparently a system level setting, and typically only 10 seconds. At NCI in Australia the system is apparently quite frequently loaded up to the point that our shutdown procedure takes more than 10 seconds and the job gets killed dead before the "failed" message can get through.  The only way to automatically recover from this is use of polling.  I wonder if there's anything we can do to ensure the message gets sent no matter what?

**Comment by hjoliver** [comment]
Is the consensus here that users will just have to convince their PBS admins to extent the system wide time interval between signals?

**Comment by matthewrmshin** [comment]
> Is the consensus here that users will just have to convince their PBS admins to extent the system wide time interval between signals?

Yes. There is nothing we can do.

**Comment by matthewrmshin** [comment]
To clarify:

In practice, the best way is to convince their PBS admins to extent the system wide time interval between signals.

In theory, there is one thing we can do, which is to submit another PBS job for the purpose of sending the message for the 1st job.

**Comment by benfitzpatrick** [comment]
> In practice, the best way is to convince their PBS admins to extent the system wide time interval between signals.

10 seconds is the default in PBS (12.2), according to the documentation. I think this is
unacceptably quick. 30 or 60 seconds is more sensible.

**Comment by hjoliver** [comment]
Closing this; the consensus is: persuade PBS admins to increase the unreasonably low default interval between kill signals.
