### ISSUE TITLE
Allow initial cycle point relative to current time

### ISSUE THREAD

**Issue by benfitzpatrick** [cylc/cylc#984]
We may want to allow users to run a suite with an initial
cycle point based around the current date-time with more
functionality than the `--now` option to `cylc run` gives.

For example, the initial cycle point might be the first day
of the current month or 00:00 on the current day.

**Comment by benfitzpatrick** [comment]
Maybe we want the initial cycle point to be scriptable:
```
[scheduling]
    initial cycle point = $(rose date -f=%Y%m%d)
```

or maybe provide the current date and time as a Jinja2 variable that could be altered.

Things like rounding down the time to the nearest `00Z, 06Z, 12Z, 18Z` are really difficult
to accommodate without some kind of scripting or Jinja-ninja-ing.

**Comment by hjoliver** [comment]
Need for truncation of "now": https://github.com/cylc/cylc/pull/1494#issuecomment-112250501

**Comment by hjoliver** [comment]
[meeting] - "small" issue.

**Comment by arjclark** [comment]
@cylc/core - to clarify, is this ultimately about re-formatting the "now" string in some way? (I read "Allow initial cycle point relative to current time" as wanting something like `initial cycle point = +P1D`)

**Comment by matthewrmshin** [comment]
I am thinking of things like:
* today (at 00:00 or some other fix times).
* tomorrow (ditto).
* beginning of the current year/month/week.
* beginning of next year/month/week.
* etc.
