### ISSUE TITLE
Builtin event handler functionalities

### ISSUE THREAD

**Issue by matthewrmshin** [cylc/cylc#992]
This is to migrate functionalities currently provided by `rose suite-hook` into cylc proper. Functionalities should be easily configurable via cylc site, user and suite configurations.
- [x] Pull job logs from remote job hosts.
  * File size needs to be configurable. See also metomi/rose#1300.
- [x] Add job log meta information to suite run time database.
- [x] ~~Add job log meta information to suite run time database, on housekeep.~~ (Not necessary in hindsight.)
- [x] Send emails on events.
  * Configurable sender.
    * (default = `suite-name@suite-host-name`?)
  * Configurable recipients.
    * (default = user ID of owner of suite)
    * Make owner name and email configurable?
  * Configurable SMTP server.
  * Configurable templates for email subject and content?
- [ ] ~~Kill job on submission time out. (E.g. To handle job stuck in the queue for some reason.)~~
  * If a job is stuck in the queue, it is likely to involve manual intervention.
    An automated kill is not likely to be useful, therefore.
- [ ] ~~Kill job on execution time out. Requested by @steoxley. (E.g. To handle, e.g. a background job stuck in a loop.)~~
  * This is superseded by #1718.
- [ ] ~~Shut down (with options) on events.~~
  * ~~Handle family event, e.g. shut down when whole family completes but with some failed tasks?~~
  * This is not as useful as before as we now handle stalled suites.

**Comment by benfitzpatrick** [comment]
> `kill job when submission|execution timeout`

It would also be nice if we could `poll job when submission|execution timeout` - this is nearly always what we would expect people to do manually anyway. I'd argue that it should default to True as well.

**Comment by hjoliver** [comment]
Don't we do this already?

**Comment by matthewrmshin** [comment]
> Kill job on submission/execution time out.

Can now be done by specifying `cylc kill %(suite)s %(task)s %(point)s` as an event handler command.

> Shut down (with options) on events.

Can now be done by specifying `cylc stop %(suite)s` as an event handler command.

The question is, do we still want these functions to be more integrated, i.e. with built-in `suite.rc` settings?

**Comment by benfitzpatrick** [comment]
> Don't we do this already?

Yes (now from proper testing) - whoops. I had thought that a poll would always show up in the suite log, but it doesn't (it did at 6.4.1, but not at the current master).

I'm not sure why the poll didn't work for the user who reported it (job disappeared from the scheduler).

**Comment by hjoliver** [comment]
[meeting] - @matthewrmshin - to determine what's left to do on this, and finish it off.

**Comment by matthewrmshin** [comment]
I have updated the description of this issue with why we are skipping the remaining 3 check boxes. Automatic kill on submission timeout is unlikely to be useful. Shutdown on event is better done using the suite level event handlers such as `abort if any task fails` or the stalled event handler. Automatic kill (for `background` and `at`) on execution timeout will be done as part of #1718.

**Comment by matthewrmshin** [comment]
(Reset milestone to align with #1503.)
