### ISSUE TITLE
task job log housekeeping, from Rose

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc#994]
One of the cylc-specific Rose functions that will be moved into cylc itself is automatic housekeeping of job logs.  Currently (@matthewrmshin - correct me if I'm wrong) Rose combines this with housekeeping the share and work directories, but we decided that these functionalities should be separated.

**Comment by matthewrmshin** [comment]
#1159 supersedes this, so I'll close this down as a duplicate.
