### ISSUE TITLE
effect of bad cylc-suite-env file

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc#998]
Something that caused some trouble at NIWA while I was away - a suite had the wrong port number in its ```cylc-suite-env``` file on a particular task host.  Because there was a suite running at the bad port, this resulted in task messages failing with the "security reasons" error that implies a bad passphrase. This was confusing because the passphrase appeared to be correct (but it was the wrong passphrase for the wrong suite!).

We should figure out how the wrong port number could end up in an env file, and prevent it or at least document the possible reasons for "security reasons" errors (perhaps in task stderr, if it happens, to ensure it doesn't go unnoticed).

**Comment by matthewrmshin** [comment]
Is there anything we can do for this issue? If not, perhaps it should be closed?

**Comment by hjoliver** [comment]
I haven't had any more reports of this problem, so I'll close it for now.

**Comment by matthewrmshin** [comment]
(I am marking this as a wontfix, as we don't really know what we need to fix!)
